### ISSUE TITLE
Bridging long messages to telegram fails

### ISSUE THREAD

**Issue by tulir** [tulir/mautrix-telegram#117]
Not sure what the bridge should do, but it should definitely not throw an error.

```
[2018-04-16 23:49:39,270] [ERROR@mau.as] Exception in Matrix event handler
Traceback (most recent call last):
  File "/lib/python3.6/site-packages/mautrix_appservice/appservice.py", line 186, in try_handle
    await handler_func(event)
  File "/mautrix_telegram/matrix.py", line 257, in handle_event
    await self.handle_message(evt["room_id"], evt["sender"], content, evt["event_id"])
  File "/mautrix_telegram/matrix.py", line 177, in handle_message
    await portal.handle_matrix_message(sender, message, event_id)
  File "/mautrix_telegram/portal.py", line 681, in handle_matrix_message
    response = await self._handle_matrix_text(client, message, reply_to)
  File "/mautrix_telegram/portal.py", line 639, in _handle_matrix_text
    return await client.send_message(self.peer, message, entities=entities, reply_to=reply_to)
  File "/mautrix_telegram/tgclient.py", line 40, in send_message
    result = await self(request)
  File "/lib/python3.6/site-packages/telethon/telegram_bare_client.py", line 435, in __call__
    result = await self._invoke(call_receive, retry, *requests)
  File "/lib/python3.6/site-packages/telethon/telegram_bare_client.py", line 520, in _invoke
    raise next(x.rpc_error for x in requests if x.rpc_error)
telethon.errors.rpc_error_list.MessageTooLongError: Message was too long. Current maximum length is 4096 UTF-8 characters
```

**Comment by alfredonodo** [comment]
Telegram supports messages of up to [4096 characters](https://bugs.telegram.org/c/1423) and splits a message over the limit into several messages while matrix has a UTF-8 encoded character limit of [65536 bytes ](https://spec.matrix.org/v1.6/client-server-api/#size-limits)(16384 and 65536 characters).
It would be appropriate for the bot to forward a message from matrix to telegram by splitting it into N messages of 4096 characters instead of truncating it as now.
Thank you
