### ISSUE TITLE
Rooms that had a canonical alias but don't anymore cannot be bridged

### ISSUE THREAD

**Issue by turt2live** [tulir/mautrix-telegram#171]
Reproduction steps:
1. Create a new room
2. Give it a canonical alias
3. Wait for the event to go through, then set the `m.room.canonical_alias` event to `{}` (remove the alias)
4. Try to bridge the room as a portal

This leaves the bridge in a half-broken state: it believes it has bridged, however it complains about a fatal error. This means that bridging does not work, but when someone goes to retry the bridge they are met with "this room is already bridged" or "that chat is already in use by #current_room".

**Comment by turt2live** [comment]
The actual error is:
```
[2018-07-03 20:14:22,082] [ERROR@mau.commands] Fatal error handling command  continue from @redacted:user.com
Traceback (most recent call last):
  File "/opt/mautrixtelegram/mautrix_telegram/commands/handler.py", line 98, in handle
    await command(evt)
  File "/opt/mautrixtelegram/mautrix_telegram/commands/portal.py", line 276, in confirm_bridge
    portal.title, portal.about, levels = await _get_initial_state(evt)
  File "/opt/mautrixtelegram/mautrix_telegram/commands/portal.py", line 299, in _get_initial_state
    title = title or event["content"]["alias"]
KeyError: 'alias'
```
