### ISSUE TITLE
Kicking a Telegram user from Matrix results in an error

### ISSUE THREAD

**Issue by turt2live** [tulir/mautrix-telegram#191]
```
[2018-07-21 02:58:06,419] [INFO@mau.portal] Peer type: channel
[2018-07-21 02:58:06,419] [ERROR@mau.as] Exception in Matrix event handler
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/mautrix_appservice/appservice.py", line 170, in try_handle
    await handler_func(event)
  File "/opt/mautrix-telegram/mautrix_telegram/matrix.py", line 318, in handle_event
    await self.handle_part(room_id, state_key, sender, event_id)
  File "/opt/mautrix-telegram/mautrix_telegram/matrix.py", line 187, in handle_part
    await portal.leave_matrix(puppet, sender, event_id)
  File "/opt/mautrix-telegram/mautrix_telegram/portal.py", line 681, in leave_matrix
    channel = await self.get_input_entity(source)
  File "/opt/mautrix-telegram/mautrix_telegram/portal.py", line 202, in get_input_entity
    return user.client.get_input_entity(self.peer)
AttributeError: 'NoneType' object has no attribute 'get_input_entity'
```

The `Peer type` log line is something I added to debug the problem. It does not affect the line numbers in the stack trace.

**Comment by tulir** [comment]
I think the problem is that kicking Telegram users from Matrix is only implemented for users who have logged in, but some check is missing. Either the missing check needs to be added or kicking through the relaybot needs to be implemented (with appropriate checks/catches for telegram-side permissions)
