### ISSUE TITLE
Setting up Telegram puppeting twice results in the second one being silent

### ISSUE THREAD

**Issue by turt2live** [tulir/mautrix-telegram#198]
1. Log in to telegram on one matrix user
2. Log in to the same telegram account with a different matrix user
3. Try to send messages as the second matrix user
4. Nothing is bridged

**Comment by turt2live** [comment]
This actually causes the bridge to crash and stop working now:

```
[2018-08-15 14:54:13,050] [ERROR@mau.as] Exception in Matrix event handler
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/mautrix_appservice/appservice.py", line 173, in try_handle
    await handler_func(event)
  File "/opt/mautrix-telegram/mautrix_telegram/matrix.py", line 381, in handle_event
    await self.handle_join(room_id, state_key, event_id)
  File "/opt/mautrix-telegram/mautrix_telegram/matrix.py", line 154, in handle_join
    user = await u.User.get_by_mxid(user_id).ensure_started()
  File "/opt/mautrix-telegram/mautrix_telegram/abstract_user.py", line 170, in ensure_started
    self.session_container.Session.session_id == self.mxid).count())
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3160, in count
    return self.from_self(col).scalar()
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2913, in scalar
    ret = self.one()
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2884, in one
    ret = self.one_or_none()
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2854, in one_or_none
    ret = list(self)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2925, in __iter__
    return self._execute_and_instances(context)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2946, in _execute_and_instances
    close_with_result=True)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2955, in _get_bind_args
    **kw
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2937, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1035, in connection
    execution_options=execution_options)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1040, in _connection_for_bind
    engine, execution_options)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 388, in _connection_for_bind
    self._assert_active()
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 276, in _assert_active
    % self._rollback_exception
sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (psycopg2.IntegrityError) duplicate key value violates unique constraint "user_tgid_key"
DETAIL:  Key (tgid)=(123redacted) already exists.
 [SQL: 'UPDATE "user" SET tgid=%(tgid)s WHERE "user".mxid = %(user_mxid)s'] [parameters: {'tgid': 123redacted, 'user_mxid': '@redacted:domain.com'}] (Background on this error at: http://sqlalche.me/e/gkpj)
```
