### ISSUE TITLE
Relay bot disconnected

### ISSUE THREAD

**Issue by vurpo** [tulir/mautrix-telegram#215]
Occasionally when sending messages from non-puppeted users from Matrix to Telegram, the message fails to go through, with this error appearing in the logs:

```
[2018-08-17 05:46:53,244] [ERROR@mau.as] Exception in Matrix event handler
Traceback (most recent call last):
  File "/home/vurpo/mautrix-telegram/lib/python3.6/site-packages/mautrix_appservice/appservice.py", line 173, in try_handle
    await handler_func(event)
  File "/home/vurpo/mautrix-telegram/lib/python3.6/site-packages/mautrix_telegram/matrix.py", line 407, in handle_event
    await self.handle_message(room_id, sender, content, event_id)
  File "/home/vurpo/mautrix-telegram/lib/python3.6/site-packages/mautrix_telegram/matrix.py", line 233, in handle_message
    if not is_command and portal and (await sender.is_logged_in() or portal.has_bot):
  File "/home/vurpo/mautrix-telegram/lib/python3.6/site-packages/mautrix_telegram/abstract_user.py", line 152, in is_logged_in
    return self.client and await self.client.is_user_authorized()
  File "/home/vurpo/mautrix-telegram/lib/python3.6/site-packages/telethon/client/users.py", line 118, in is_user_authorized
    self._state = await self(functions.updates.GetStateRequest())
  File "/home/vurpo/mautrix-telegram/lib/python3.6/site-packages/telethon/client/users.py", line 38, in __call__
    future = self._sender.send(request, ordered=ordered)
  File "/home/vurpo/mautrix-telegram/lib/python3.6/site-packages/telethon/network/mtprotosender.py", line 202, in send
    raise ConnectionError('Cannot send requests while disconnected')
ConnectionError: Cannot send requests while disconnected
```

I don't know when this happens and what would cause it, but something more than just giving up should be done if this happens.

**Comment by tulir** [comment]
That actually looks like a bug. A TelegramClient was created for the user, but not connected, and `is_logged_in` doesn't account for that case.

**Comment by vurpo** [comment]
This user has never tried to connect their Telegram account to the bridge, so it should only have been bridged through the relay bot.

**Comment by tulir** [comment]
There's a lot of code shared between puppeted users and relaybot users, so it's definitely possible it creates an unnecessary TelegramClient for a relaybot user in some cases.
