### ISSUE TITLE
"Could not find input entity" and lost messages

### ISSUE THREAD

**Issue by Valodim** [tulir/mautrix-telegram#229]
```
[2018-09-21 17:39:42,884] [ERROR@mau.user] Failed to handle Telegram update
Traceback (most recent call last):
  File "/home/matrix/matrix-appservice-tg/lib/python3.5/site-packages/mautrix_telegram/abstract_user.py", line 133, in _update_catch
    await self._update(update)
  File "/home/matrix/matrix-appservice-tg/lib/python3.5/site-packages/mautrix_telegram/abstract_user.py", line 189, in _update
    await self.update_message(update)
  File "/home/matrix/matrix-appservice-tg/lib/python3.5/site-packages/mautrix_telegram/abstract_user.py", line 370, in update_message
    return await portal.handle_telegram_message(self, sender, update)
  File "/home/matrix/matrix-appservice-tg/lib/python3.5/site-packages/mautrix_telegram/portal.py", line 1394, in handle_telegram_message
    await self.create_matrix_room(source, invites=[source.mxid], update_if_exists=False)
  File "/home/matrix/matrix-appservice-tg/lib/python3.5/site-packages/mautrix_telegram/portal.py", line 304, in create_matrix_room
    return await self._create_matrix_room(user, entity, invites)
  File "/home/matrix/matrix-appservice-tg/lib/python3.5/site-packages/mautrix_telegram/portal.py", line 317, in _create_matrix_room
    entity = await user.client.get_entity(self.peer)
  File "/home/matrix/matrix-appservice-tg/lib/python3.5/site-packages/telethon/client/users.py", line 168, in get_entity
    inputs.append(await self.get_input_entity(x))
  File "/home/matrix/matrix-appservice-tg/lib/python3.5/site-packages/telethon/client/users.py", line 297, in get_input_entity
    .format(peer)
ValueError: Could not find the input entity for "PeerUser(user_id=680809749)". Please read https://telethon.readthedocs.io/en/latest/extra/basic/entities.html to find out more details.
```

got a bunch of these in my log, and reports from one user that messages from a specific other user consistently don't get through

**Comment by Pneumaticat** [comment]
I just got the same error when making a new p2p chat with a new user that I hadn't talked to before:

```
[2018-11-12 15:29:00,587] [ERROR@mau.user] Failed to handle Telegram update
Traceback (most recent call last):
  File "/opt/mautrix-telegram/mautrix_telegram/abstract_user.py", line 133, in _update_catch
    await self._update(update)
  File "/opt/mautrix-telegram/mautrix_telegram/abstract_user.py", line 189, in _update
    await self.update_message(update)
  File "/opt/mautrix-telegram/mautrix_telegram/abstract_user.py", line 382, in update_message
    return await portal.handle_telegram_message(self, sender, update)
  File "/opt/mautrix-telegram/mautrix_telegram/portal.py", line 1439, in handle_telegram_message
    await self.create_matrix_room(source, invites=[source.mxid], update_if_exists=False)
  File "/opt/mautrix-telegram/mautrix_telegram/portal.py", line 328, in create_matrix_room
    return await self._create_matrix_room(user, entity, invites)
  File "/opt/mautrix-telegram/mautrix_telegram/portal.py", line 341, in _create_matrix_room
    entity = await user.client.get_entity(self.peer)
  File "/usr/lib/python3.6/site-packages/telethon/client/users.py", line 180, in get_entity
    inputs.append(await self.get_input_entity(x))
  File "/usr/lib/python3.6/site-packages/telethon/client/users.py", line 310, in get_input_entity
    .format(peer)
ValueError: Could not find the input entity for "PeerUser(user_id=16223347)". Please read https://telethon.readthedocs.io/en/latest/extra/basic/entities.html to find out more details.
```
