### ISSUE TITLE
Duplicate Telegram user tries to update itself into the database

### ISSUE THREAD

**Issue by turt2live** [tulir/mautrix-telegram#246]
```
[2018-12-03 18:14:27,170] [ERROR@mau.user] Failed to handle Telegram update
Traceback (most recent call last):
  File "/opt/mautrix-telegram/mautrix_telegram/abstract_user.py", line 133, in _update_catch
    await self._update(update)
  File "/opt/mautrix-telegram/mautrix_telegram/abstract_user.py", line 189, in _update
    await self.update_message(update)
  File "/opt/mautrix-telegram/mautrix_telegram/abstract_user.py", line 382, in update_message
    return await portal.handle_telegram_message(self, sender, update)
  File "/opt/mautrix-telegram/mautrix_telegram/portal.py", line 1498, in handle_telegram_message
    response = await self.handle_telegram_text(source, intent, is_bot, evt)
  File "/opt/mautrix-telegram/mautrix_telegram/portal.py", line 1403, in handle_telegram_text
    await intent.set_typing(self.mxid, is_typing=False)
  File "/usr/lib/python3.6/site-packages/mautrix_appservice/intent_api.py", line 642, in set_typing
    await self.ensure_joined(room_id)
  File "/usr/lib/python3.6/site-packages/mautrix_appservice/intent_api.py", line 871, in ensure_joined
    if not ignore_cache and self.state_store.is_joined(room_id, self.mxid):
  File "/usr/lib/python3.6/site-packages/mautrix_appservice/state_store.py", line 76, in is_joined
    return self.get_membership(room, user) == "join"
  File "/usr/lib/python3.6/site-packages/mautrix_appservice/state_store.py", line 73, in get_membership
    return self.get_member(room, user).get("membership", "left")
  File "/opt/mautrix-telegram/mautrix_telegram/sqlstatestore.py", line 73, in get_member
    return self._get_user_profile(room, user).dict()
  File "/opt/mautrix-telegram/mautrix_telegram/sqlstatestore.py", line 62, in _get_user_profile
    profile = UserProfile.query.get(key)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 882, in get
    ident, loading.load_on_pk_identity)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 952, in _get_impl
    return db_load_fn(self, primary_key_identity)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 247, in load_on_pk_identity
    return q.one()
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2884, in one
    ret = self.one_or_none()
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2854, in one_or_none
    ret = list(self)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2924, in __iter__
    self.session._autoflush()
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1434, in _autoflush
    self.flush()
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2254, in flush
    self._flush(objects)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2340, in _flush
    subtransactions=True)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 854, in begin
    nested=nested)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 297, in _begin
    self._assert_active()
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 276, in _assert_active
    % self._rollback_exception
sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.IntegrityError) duplicate key value violates unique constraint "user_tgid_key"
DETAIL:  Key (tgid)=(REDACTED) already exists.
 [SQL: 'UPDATE "user" SET tgid=%(tgid)s, tg_phone=%(tg_phone)s WHERE "user".mxid = %(user_mxid)s'] [parameters: {'tgid': REDACTED, 'tg_phone': 'REDACTED', 'user_mxid': '@REDACTED:REDACTED'}] (Background on this error at: http://sqlalche.me/e/gkpj)
```

**Comment by turt2live** [comment]
I'm not sure what caused this, but here's a couple other things I noticed when trying to fix it myself:
* The user referenced in the `UPDATE` was (obviously) different from the one that already had the `tgid`
* The user in the `UPDATE` had a telethon session, while the user holding the `tgid` didn't

**Comment by tulir** [comment]
This is an old issue from sqlalchemy orm times. If someone encounters it again, create a new issue with new stack traces
