### ISSUE TITLE
Error on startup: ImportError: cannot import name 'UpdatePinnedMessageRequest'

### ISSUE THREAD

**Issue by turt2live** [tulir/mautrix-telegram#259]
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/mautrix-telegram/mautrix_telegram/__main__.py", line 31, in <module>
    from .web.provisioning import ProvisioningAPI
  File "/opt/mautrix-telegram/mautrix_telegram/web/__init__.py", line 1, in <module>
    from .provisioning import ProvisioningAPI
  File "/opt/mautrix-telegram/mautrix_telegram/web/provisioning/__init__.py", line 28, in <module>
    from ...user import User
  File "/opt/mautrix-telegram/mautrix_telegram/user.py", line 32, in <module>
    from .abstract_user import AbstractUser
  File "/opt/mautrix-telegram/mautrix_telegram/abstract_user.py", line 36, in <module>
    from . import portal as po, puppet as pu, __version__
  File "/opt/mautrix-telegram/mautrix_telegram/portal.py", line 41, in <module>
    from telethon.tl.functions.channels import (
ImportError: cannot import name 'UpdatePinnedMessageRequest'
```

This is using the current master in a Docker image.

**Comment by turt2live** [comment]
It looks like it has gone missing from https://lonamiwebs.github.io/Telethon/methods/channels/index.html

For now, I've worked around this using 1e4607efd8385b74caa5772410defd8058020fd4
