### ISSUE TITLE
Invalid chat ID error spamming console

### ISSUE THREAD

**Issue by turt2live** [tulir/mautrix-telegram#261]
```
[2018-12-30 16:03:55,562] [ERROR@mau.user] Failed to handle Telegram update
Traceback (most recent call last):
  File "/opt/mautrix-telegram/mautrix_telegram/abstract_user.py", line 138, in _update_catch
    await self._update(update)
  File "/opt/mautrix-telegram/mautrix_telegram/abstract_user.py", line 191, in _update
    await self.update_message(update)
  File "/opt/mautrix-telegram/mautrix_telegram/abstract_user.py", line 386, in update_message
    return await portal.handle_telegram_message(self, sender, update)
  File "/opt/mautrix-telegram/mautrix_telegram/portal.py", line 1530, in handle_telegram_message
    await self.create_matrix_room(source, invites=[source.mxid], update_if_exists=False)
  File "/opt/mautrix-telegram/mautrix_telegram/portal.py", line 348, in create_matrix_room
    return await self._create_matrix_room(user, entity, invites)
  File "/opt/mautrix-telegram/mautrix_telegram/portal.py", line 361, in _create_matrix_room
    entity = await self.get_entity(user)
  File "/opt/mautrix-telegram/mautrix_telegram/portal.py", line 292, in get_entity
    return await user.client.get_entity(self.peer)
  File "/usr/lib/python3.6/site-packages/telethon/client/users.py", line 208, in get_entity
    functions.messages.GetChatsRequest(chats))).chats
  File "/usr/lib/python3.6/site-packages/telethon/client/users.py", line 60, in __call__
    result = await future
telethon.errors.rpcerrorlist.ChatIdInvalidError: Invalid object ID for a chat. Make sure to pass the right types, for instance making sure that the request is designed for chats (not channels/megagroups) or otherwise look for a different one more suited\nAn example working with a megagroup and AddChatUserRequest, it will fail because megagroups are channels. Use InviteToChannelRequest instead (caused by GetChatsRequest)
```

**Comment by tulir** [comment]
Most likely invalid handling of a deleted or upgraded telegram group

**Comment by tulir** [comment]
If this was invalid handling of a upgraded telegram group, it's probably fixed now.
