### ISSUE TITLE
Crash loop on startup due to sqlalchemy error from telethon

### ISSUE THREAD

**Issue by Pneumaticat** [tulir/mautrix-telegram#262]
Startup:

```
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
chown: /data/registration.yaml: Read-only file system
[2018-12-31 19:27:40,765] [DEBUG@mau.init] Initializing mautrix-telegram 0.5.0+dev
[2018-12-31 19:27:47,015] [DEBUG@mau.init] Initialization complete, running startup actions
[2018-12-31 19:27:48,313] [DEBUG@mau.user] ensure_started(@kevin:potatofrom.space, even_if_no_session=False, session_count=1)
[2018-12-31 19:27:48,313] [DEBUG@mau.user] Initializing client for @kevin:potatofrom.space
[2018-12-31 19:27:48,333] [DEBUG@mau.as.api] POST /register {"username": "telegrambot"} as user No identity
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/mautrix-telegram/mautrix_telegram/__main__.py", line 134, in <module>
    loop.run_until_complete(asyncio.gather(*startup_actions, loop=loop))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "/opt/mautrix-telegram/mautrix_telegram/abstract_user.py", line 179, in ensure_started
    await self.start(delete_unless_authenticated=not even_if_no_session)
  File "/opt/mautrix-telegram/mautrix_telegram/user.py", line 169, in start
    await super().start()
  File "/opt/mautrix-telegram/mautrix_telegram/abstract_user.py", line 166, in start
    self._init_client()
  File "/opt/mautrix-telegram/mautrix_telegram/abstract_user.py", line 116, in _init_client
    proxy=self._proxy_settings)
  File "/usr/lib/python3.6/site-packages/telethon/client/telegrambaseclient.py", line 273, in __init__
    self._state = (self.session.get_update_state(0)
  File "/usr/lib/python3.6/site-packages/alchemysession/sqlalchemy.py", line 193, in get_update_state
    row.date = datetime.datetime.utcfromtimestamp(row.date)
TypeError: an integer is required (got type str)
```

Turns out there's a `date` column that actually stores an ASCII date? in `telethon_update_state`. By editing the db entry and converting it to a unix timestamp, the bridge starts, but this breaks yet again when you restart the bridge.

Using the latest tag of the Docker image, on Kubernetes.

**Comment by tulir** [comment]
This should be fixed now with the latest telethon-session-sqlalchemy version (0.2.6). Edit or remove the invalid db rows if they still exist and it shouldn't happen again.
