### ISSUE TITLE
InvalidRequestError: Duplicate portal attempting to be inserted

### ISSUE THREAD

**Issue by turt2live** [tulir/mautrix-telegram#264]
Unknown cause.

```
[2019-01-09 16:21:33,881] [ERROR@mau.as] Exception in Matrix event handler
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/mautrix_appservice/appservice.py", line 173, in try_handle
    await handler_func(event)
  File "/opt/mautrix-telegram/mautrix_telegram/matrix.py", line 404, in handle_event
    await self.handle_message(room_id, sender, content, event_id)
  File "/opt/mautrix-telegram/mautrix_telegram/matrix.py", line 222, in handle_message
    sender = await u.User.get_by_mxid(sender_id).ensure_started()
  File "/opt/mautrix-telegram/mautrix_telegram/abstract_user.py", line 175, in ensure_started
    self.session_container.Session.session_id == self.mxid).count()
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3160, in count
    return self.from_self(col).scalar()
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2913, in scalar
    ret = self.one()
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2884, in one
    ret = self.one_or_none()
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2854, in one_or_none
    ret = list(self)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2924, in __iter__
    self.session._autoflush()
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1434, in _autoflush
    self.flush()
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2254, in flush
    self._flush(objects)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2340, in _flush
    subtransactions=True)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 854, in begin
    nested=nested)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 297, in _begin
    self._assert_active()
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 276, in _assert_active
    % self._rollback_exception
sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.IntegrityError) duplicate key value violates unique constraint "portal_pkey"
DETAIL:  Key (tgid, tg_receiver)=(REDACTED309, REDACTED309) already exists.
 [SQL: 'INSERT INTO portal (tgid, tg_receiver, peer_type, megagroup, mxid, config, username, title, about, photo_id) VALUES (%(tgid)s, %(tg_receiver)s, %(peer_type)s, %(megagroup)s, %(mxid)s, %(config)s, %(username)s, %(title)s, %(about)s, %(photo_id)s)'] [parameters: {'tgid': REDACTED309, 'tg_receiver': REDACTED309, 'peer_type': 'channel', 'megagroup': False, 'mxid': '!REDACTED:t2bot.io', 'config': '{}', 'username': None, 'title': 'REDACTED', 'about': None, 'photo_id': None}] (Background on this error at: http://sqlalche.me/e/gkpj)
```

**Comment by turt2live** [comment]
fwiw this is the row it is conflicting with:
```
mautrix_telegram=> select * from portal where tgid = 1206262309;
    tgid    | tg_receiver | peer_type | mxid | username | title | about | photo_id | megagroup | config
------------+-------------+-----------+------+----------+-------+-------+----------+-----------+--------
REDACTED309 | REDACTED309 | channel   |      |          |       |       |          | f         | {}
(1 row)

```

**Comment by tulir** [comment]
That stack trace is unrelated to the actual error and was caused by the ORM getting stuck (i.e. it's useless). The bridge doesn't use the ORM anymore, so future database error stack traces should show the real error. Please reopen if this happens again.
