### ISSUE TITLE
Unable to sync chats: Channel has no attribute admins_enabled

### ISSUE THREAD

**Issue by turt2live** [tulir/mautrix-telegram#268]
```
[2019-01-20 17:02:02,170] [ERROR@mau.commands] Unhandled error while handling command sync chats from @redacted
Traceback (most recent call last):
  File "/opt/mautrix-telegram/mautrix_telegram/commands/handler.py", line 193, in handle
    await handler(evt)
  File "/opt/mautrix-telegram/mautrix_telegram/commands/handler.py", line 135, in __call__
    return await self._handler(evt)
  File "/opt/mautrix-telegram/mautrix_telegram/commands/telegram.py", line 160, in sync
    await evt.sender.sync_dialogs(synchronous_create=True)
  File "/opt/mautrix-telegram/mautrix_telegram/user.py", line 307, in sync_dialogs
    await asyncio.gather(*creators, loop=self.loop)
  File "/opt/mautrix-telegram/mautrix_telegram/portal.py", line 350, in create_matrix_room
    return await self._create_matrix_room(user, entity, invites)
  File "/opt/mautrix-telegram/mautrix_telegram/portal.py", line 392, in _create_matrix_room
    power_levels = self._get_base_power_levels({}, entity)
  File "/opt/mautrix-telegram/mautrix_telegram/portal.py", line 422, in _get_base_power_levels
    power_level_requirement = (0 if self.peer_type == "chat" and not entity.admins_enabled
AttributeError: 'Channel' object has no attribute 'admins_enabled'
```

**Comment by tulir** [comment]
Fixed in 165f286bfdd7082f2f21564fa500e929bf474c06
