### ISSUE TITLE
Install fails on ImportError: cannot import name 'UpdateChatAdmins'

### ISSUE THREAD

**Issue by alexthorsrud** [tulir/mautrix-telegram#274]
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/bridge/telegram/mautrix_telegram/__main__.py", line 31, in <module>
    from .web.provisioning import ProvisioningAPI
  File "/usr/local/bridge/telegram/mautrix_telegram/web/__init__.py", line 1, in <module>
    from .provisioning import ProvisioningAPI
  File "/usr/local/bridge/telegram/mautrix_telegram/web/provisioning/__init__.py", line 28, in <module>
    from ...user import User
  File "/usr/local/bridge/telegram/mautrix_telegram/user.py", line 32, in <module>
    from .abstract_user import AbstractUser
  File "/usr/local/bridge/telegram/mautrix_telegram/abstract_user.py", line 25, in <module>
    from telethon.tl.types import (
ImportError: cannot import name 'UpdateChatAdmins'

**Comment by tulir** [comment]
Probably too new telethon, temporarily fixed by 2480578bd989baf14894eb3f13905bcd95e7e41b until I get around to updating stuff. If pip upgrading doesn't downgrade telethon, install version 1.5.3 manually.
