### ISSUE TITLE
sqlalchemy / psycopg2 type cast error when starting the bridge

### ISSUE THREAD

**Issue by Georg311** [tulir/mautrix-telegram#275]
Used version 0.5.0+dev

When trying to start the bridge i get following error

```python
Feb 05 10:14:51 matrix.example.com python[7297]: [2019-02-05 10:14:51,892] [DEBUG@mau.init] Initializing mautrix-telegram 0.5.0+dev
Feb 05 10:14:51 matrix.example.com python[7297]: [2019-02-05 10:14:51,995] [DEBUG@mau.init] Initialization complete, running startup actions
Feb 05 10:14:52 matrix.example.com python[7297]: [2019-02-05 10:14:52,001] [DEBUG@mau.user] ensure_started(@user:example.com, even_if_no_session=False, session_count=1)
Feb 05 10:14:52 matrix.example.com python[7297]: [2019-02-05 10:14:52,002] [DEBUG@mau.user] Initializing client for @user:example.com
Feb 05 10:14:52 matrix.example.com python[7297]: [2019-02-05 10:14:52,007] [INFO@telethon.network.mtprotosender] Connecting to 149.154.167.92:443/TcpFull...
Feb 05 10:14:52 matrix.example.com python[7297]: [2019-02-05 10:14:52,009] [DEBUG@telethon.network.mtprotosender] Connection attempt 1...
Feb 05 10:14:52 matrix.example.com python[7297]: [2019-02-05 10:14:52,009] [DEBUG@mau.as.api] POST /register {"username": "telegrambot"} as user No identity
Feb 05 10:14:52 matrix.example.com python[7297]: [2019-02-05 10:14:52,025] [DEBUG@mau.bot] Initializing client for bot
Feb 05 10:14:52 matrix.example.com python[7297]: Traceback (most recent call last):
Feb 05 10:14:52 matrix.example.com python[7297]: File "/home/telnpm/telegram/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
Feb 05 10:14:52 matrix.example.com python[7297]: context)
Feb 05 10:14:52 matrix.example.com python[7297]: File "/home/telnpm/telegram/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
Feb 05 10:14:52 matrix.example.com python[7297]: cursor.execute(statement, parameters)
Feb 05 10:14:52 matrix.example.com python[7297]: psycopg2.ProgrammingError: FEHLER:  Spalte »date« hat Typ bigint, aber der Ausdruck hat Typ timestamp without time zone
Feb 05 10:14:52 matrix.example.com python[7297]: LINE 1: UPDATE telethon_update_state SET date='2019-01-31T10:58:33':...
Feb 05 10:14:52 matrix.example.com python[7297]: ^
Feb 05 10:14:52 matrix.example.com python[7297]: HINT:  Sie müssen den Ausdruck umschreiben oder eine Typumwandlung vornehmen.
Feb 05 10:14:52 matrix.example.com python[7297]: The above exception was the direct cause of the following exception:
Feb 05 10:14:52 matrix.example.com python[7297]: Traceback (most recent call last):
Feb 05 10:14:52 matrix.example.com python[7297]: File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
Feb 05 10:14:52 matrix.example.com python[7297]: "__main__", mod_spec)
Feb 05 10:14:52 matrix.example.com python[7297]: File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
Feb 05 10:14:52 matrix.example.com python[7297]: exec(code, run_globals)
Feb 05 10:14:52 matrix.example.com python[7297]: File "/home/telnpm/telegram/lib/python3.6/site-packages/mautrix_telegram/__main__.py", line 134, in <module>
Feb 05 10:14:52 matrix.example.com python[7297]: loop.run_until_complete(asyncio.gather(*startup_actions, loop=loop))
Feb 05 10:14:52 matrix.example.com python[7297]: File "/usr/lib64/python3.6/asyncio/base_events.py", line 468, in run_until_complete
Feb 05 10:14:52 matrix.example.com python[7297]: return future.result()
Feb 05 10:14:52 matrix.example.com python[7297]: File "/home/telnpm/telegram/lib/python3.6/site-packages/mautrix_telegram/bot.py", line 77, in start
Feb 05 10:14:52 matrix.example.com python[7297]: await super().start(delete_unless_authenticated)
Feb 05 10:14:52 matrix.example.com python[7297]: File "/home/telnpm/telegram/lib/python3.6/site-packages/mautrix_telegram/abstract_user.py", line 166, in start
Feb 05 10:14:52 matrix.example.com python[7297]: self._init_client()
Feb 05 10:14:52 matrix.example.com python[7297]: File "/home/telnpm/telegram/lib/python3.6/site-packages/mautrix_telegram/abstract_user.py", line 103, in _init_client
Feb 05 10:14:52 matrix.example.com python[7297]: self.session = self.session_container.new_session(self.name)
Feb 05 10:14:52 matrix.example.com python[7297]: File "/home/telnpm/telegram/lib/python3.6/site-packages/alchemysession/sqlalchemy.py", line 146, in new_session
Feb 05 10:14:52 matrix.example.com python[7297]: return AlchemySession(self, session_id)
Feb 05 10:14:52 matrix.example.com python[7297]: File "/home/telnpm/telegram/lib/python3.6/site-packages/alchemysession/sqlalchemy.py", line 165, in __init__
Feb 05 10:14:52 matrix.example.com python[7297]: self._load_session()
Feb 05 10:14:52 matrix.example.com python[7297]: File "/home/telnpm/telegram/lib/python3.6/site-packages/alchemysession/sqlalchemy.py", line 168, in _load_session
Feb 05 10:14:52 matrix.example.com python[7297]: sessions = self._db_query(self.Session).all()
Feb 05 10:14:52 matrix.example.com python[7297]: File "/home/telnpm/telegram/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2843, in all
Feb 05 10:14:52 matrix.example.com python[7297]: return list(self)
Feb 05 10:14:52 matrix.example.com python[7297]: File "/home/telnpm/telegram/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2994, in __iter__
Feb 05 10:14:52 matrix.example.com python[7297]: self.session._autoflush()
Feb 05 10:14:52 matrix.example.com python[7297]: File "/home/telnpm/telegram/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1444, in _autoflush
Feb 05 10:14:52 matrix.example.com python[7297]: util.raise_from_cause(e)
Feb 05 10:14:52 matrix.example.com python[7297]: File "/home/telnpm/telegram/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
Feb 05 10:14:52 matrix.example.com python[7297]: reraise(type(exception), exception, tb=exc_tb, cause=cause)
Feb 05 10:14:52 matrix.example.com python[7297]: File "/home/telnpm/telegram/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
Feb 05 10:14:52 matrix.example.com python[7297]: raise value
Feb 05 10:14:52 matrix.example.com python[7297]: File "/home/telnpm/telegram/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1434, in _autoflush
Feb 05 10:14:52 matrix.example.com python[7297]: self.flush()
Feb 05 10:14:52 matrix.example.com python[7297]: File "/home/telnpm/telegram/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2254, in flush
Feb 05 10:14:52 matrix.example.com python[7297]: self._flush(objects)
Feb 05 10:14:52 matrix.example.com python[7297]: File "/home/telnpm/telegram/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2381, in _flush
Feb 05 10:14:52 matrix.example.com python[7297]: transaction.rollback(_capture_exception=True)
Feb 05 10:14:52 matrix.example.com python[7297]: File "/home/telnpm/telegram/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
Feb 05 10:14:52 matrix.example.com python[7297]: compat.reraise(exc_type, exc_value, exc_tb)
Feb 05 10:14:52 matrix.example.com python[7297]: File "/home/telnpm/telegram/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
Feb 05 10:14:52 matrix.example.com python[7297]: raise value
Feb 05 10:14:52 matrix.example.com python[7297]: File "/home/telnpm/telegram/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2345, in _flush
Feb 05 10:14:52 matrix.example.com python[7297]: flush_context.execute()
Feb 05 10:14:52 matrix.example.com python[7297]: File "/home/telnpm/telegram/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 395, in execute
Feb 05 10:14:52 matrix.example.com python[7297]: rec.execute(self)
Feb 05 10:14:52 matrix.example.com python[7297]: File "/home/telnpm/telegram/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 560, in execute
Feb 05 10:14:52 matrix.example.com python[7297]: uow
Feb 05 10:14:52 matrix.example.com python[7297]: File "/home/telnpm/telegram/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 177, in save_obj
Feb 05 10:14:52 matrix.example.com python[7297]: mapper, table, update)
Feb 05 10:14:52 matrix.example.com python[7297]: File "/home/telnpm/telegram/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 768, in _emit_update_statements
Feb 05 10:14:52 matrix.example.com python[7297]: execute(statement, multiparams)
Feb 05 10:14:52 matrix.example.com python[7297]: File "/home/telnpm/telegram/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 948, in execute
Feb 05 10:14:52 matrix.example.com python[7297]: return meth(self, multiparams, params)
Feb 05 10:14:52 matrix.example.com python[7297]: File "/home/telnpm/telegram/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
Feb 05 10:14:52 matrix.example.com python[7297]: return connection._execute_clauseelement(self, multiparams, params)
Feb 05 10:14:52 matrix.example.com python[7297]: File "/home/telnpm/telegram/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
Feb 05 10:14:52 matrix.example.com python[7297]: compiled_sql, distilled_params
Feb 05 10:14:52 matrix.example.com python[7297]: File "/home/telnpm/telegram/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
Feb 05 10:14:52 matrix.example.com python[7297]: context)
Feb 05 10:14:52 matrix.example.com python[7297]: File "/home/telnpm/telegram/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
Feb 05 10:14:52 matrix.example.com python[7297]: exc_info
Feb 05 10:14:52 matrix.example.com python[7297]: File "/home/telnpm/telegram/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
Feb 05 10:14:52 matrix.example.com python[7297]: reraise(type(exception), exception, tb=exc_tb, cause=cause)
Feb 05 10:14:52 matrix.example.com python[7297]: File "/home/telnpm/telegram/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 248, in reraise
Feb 05 10:14:52 matrix.example.com python[7297]: raise value.with_traceback(tb)
Feb 05 10:14:52 matrix.example.com python[7297]: File "/home/telnpm/telegram/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
Feb 05 10:14:52 matrix.example.com python[7297]: context)
Feb 05 10:14:52 matrix.example.com python[7297]: File "/home/telnpm/telegram/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
Feb 05 10:14:52 matrix.example.com python[7297]: cursor.execute(statement, parameters)
Feb 05 10:14:52 matrix.example.com python[7297]: sqlalchemy.exc.ProgrammingError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (psycopg2.ProgrammingError) FEHLER:  Spalte »date« hat Typ bigint, aber der Ausdruck hat Typ timestamp without time zone
Feb 05 10:14:52 matrix.example.com python[7297]: LINE 1: UPDATE telethon_update_state SET date='2019-01-31T10:58:33':...
Feb 05 10:14:52 matrix.example.com python[7297]: ^
Feb 05 10:14:52 matrix.example.com python[7297]: HINT:  Sie müssen den Ausdruck umschreiben oder eine Typumwandlung vornehmen.
Feb 05 10:14:52 matrix.example.com python[7297]: [SQL: 'UPDATE telethon_update_state SET date=%(date)s WHERE telethon_update_state.session_id = %(telethon_update_state_session_id)s AND telethon_update_state.entity_id = %(telethon_update_state_entity_id)s'] [parameters: {'date': datetime.datetime(2019, 1, 31, 10, 58, 33), 'telethon_update_state_session_id': '@user:example.com', 'telethon_update_state_entity_id': 0}] (Background on this error at: http://sqlalche.me/e/f405)
```

As backend a postgres (v9.2.24)  DB is used.

Following DB entry is the problem

```sql
telnpm=> select * from telethon_update_state
telnpm-> ;
    session_id    | entity_id |  pts   | qts |    date    | seq | unread_count
------------------+-----------+--------+-----+------------+-----+--------------
 @user:example.com |         0 | 649184 |   0 | 1548932313 |   0 |            0
(1 Zeile)
```

schema looks like:
```sql
telnpm=> \d+ telethon_update_state;
                          Tabelle »public.telethon_update_state«
    Spalte    |        Typ        | Attribute | Speicherung | Statistikziel | Beschreibung
--------------+-------------------+-----------+-------------+---------------+--------------
 session_id   | character varying | not null  | extended    |               |
 entity_id    | bigint            | not null  | plain       |               |
 pts          | bigint            |           | plain       |               |
 qts          | bigint            |           | plain       |               |
 date         | bigint            |           | plain       |               |
 seq          | bigint            |           | plain       |               |
 unread_count | integer           |           | plain       |               |
Indexe:
    "telethon_update_state_pkey" PRIMARY KEY, btree (session_id, entity_id)
Hat OIDs: nein
```
I've already checked if i missed upgrading the database with 
```bash
(telegram) [telnpm@matrix telegram]$ alembic upgrade head
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
```

But it does not change anything.

Any idea what I could do to fix this?

**Comment by tulir** [comment]
Update telethon-session-sqlalchemy

**Comment by Georg311** [comment]
Had version 0.2.5, upgraded manually to 0.2.6, works now, thank you!

```bash
(telegram) [telnpm@matrix telegram]$ pip install telethon-session-sqlalchemy==0.2.6
Collecting telethon-session-sqlalchemy==0.2.6
  Downloading https://files.pythonhosted.org/packages/a9/80/bf4cb3af88643a003293fb161f92184366573007c387427e27e3e7f5b52c/telethon_session_sqlalchemy-0.2.6-py3-none-any.whl
Requirement already satisfied: SQLAlchemy<2,>=1.2 in ./lib/python3.6/site-packages (from telethon-session-sqlalchemy==0.2.6) (1.2.13)
Installing collected packages: telethon-session-sqlalchemy
  Found existing installation: telethon-session-sqlalchemy 0.2.5
    Uninstalling telethon-session-sqlalchemy-0.2.5:
      Successfully uninstalled telethon-session-sqlalchemy-0.2.5
Successfully installed telethon-session-sqlalchemy-0.2.6
```

**Comment by Georg311** [comment]
Changed install command to 
```
pip install telethon-session-sqlalchemy>=0.2.6
```
to also upgrade telethon-session-sqlalchemy
if anyone has the same problem

thanks again
