### ISSUE TITLE
Integrity error inserting contacts

### ISSUE THREAD

**Issue by tulir** [tulir/mautrix-telegram#284]
```
[2019-02-15 16:52:35,193] [WARNING@py.warnings] /sqlalchemy/sql/crud.py:700: SAWarning: Column 'contact.user' is marked as a member of the primary key for table 'contact', but has no Python-side or server-side default generator indicated, nor does it indicate 'autoincrement=True' or 'nullable=True', and no explicit value is passed.  Primary key columns typically may not store NULL. Note that as of SQLAlchemy 1.1, 'autoincrement=True' must be indicated explicitly for composite (e.g. multicolumn) primary keys if AUTO_INCREMENT/SERIAL/IDENTITY behavior is expected for one of the columns in the primary key. CREATE TABLE statements are impacted by this change as well on most backends.
  util.warn(msg)

[2019-02-15 16:52:35,193] [WARNING@py.warnings] /sqlalchemy/sql/crud.py:700: SAWarning: Column 'contact.contact' is marked as a member of the primary key for table 'contact', but has no Python-side or server-side default generator indicated, nor does it indicate 'autoincrement=True' or 'nullable=True', and no explicit value is passed.  Primary key columns typically may not store NULL. Note that as of SQLAlchemy 1.1, 'autoincrement=True' must be indicated explicitly for composite (e.g. multicolumn) primary keys if AUTO_INCREMENT/SERIAL/IDENTITY behavior is expected for one of the columns in the primary key. CREATE TABLE statements are impacted by this change as well on most backends.
  util.warn(msg)

[2019-02-15 16:52:35,193] [ERROR@mau.as] Exception in Matrix event handler
Traceback (most recent call last):
  File "/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: NOT NULL constraint failed: contact.user

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mautrix_appservice/appservice.py", line 173, in try_handle
    await handler_func(event)
  File "mautrix-telegram/mautrix_telegram/matrix.py", line 410, in handle_event
    await self.handle_message(room_id, sender, content, event_id)
  File "mautrix-telegram/mautrix_telegram/matrix.py", line 222, in handle_message
    sender = await u.User.get_by_mxid(sender_id).ensure_started()
  File "mautrix-telegram/mautrix_telegram/user.py", line 360, in get_by_mxid
    user.db_instance.insert()
  File "mautrix-telegram/mautrix_telegram/user.py", line 127, in db_instance
    self._db_instance = self.new_db_instance()
  File "mautrix-telegram/mautrix_telegram/user.py", line 133, in new_db_instance
    portals=self.db_portals)
  File "<string>", line 4, in __init__
  File "/sqlalchemy/orm/state.py", line 424, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/sqlalchemy/orm/state.py", line 421, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/sqlalchemy/ext/declarative/base.py", line 748, in _declarative_constructor
    setattr(self, k, kwargs[k])
  File "mautrix-telegram/mautrix_telegram/db/user.py", line 84, in contacts
    for tgid in puppets])
  File "/sqlalchemy/engine/base.py", line 2075, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/sqlalchemy/util/compat.py", line 248, in reraise
    raise value.with_traceback(tb)
  File "/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) NOT NULL constraint failed: contact.user [SQL: 'INSERT INTO contact DEFAULT VALUES'] (Background on this error at: http://sqlalche.me/e/gkpj)
```

**Comment by TheReverend403** [comment]
Not sure this is fixed. ![log](https://a.pste.pw/kjc.png)
