### ISSUE TITLE
Remove puppets when UserDeactivatedError is received

### ISSUE THREAD

**Issue by turt2live** [tulir/mautrix-telegram#287]
```
[2019-03-03 01:46:59,339] [ERROR@mau.as] Exception in Matrix event handler
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/mautrix_appservice/appservice.py", line 173, in try_handle
    await handler_func(event)
  File "/opt/mautrix-telegram/mautrix_telegram/matrix.py", line 410, in handle_event
    await self.handle_message(room_id, sender, content, event_id)
  File "/opt/mautrix-telegram/mautrix_telegram/matrix.py", line 231, in handle_message
    await portal.handle_matrix_message(sender, message, event_id)
  File "/opt/mautrix-telegram/mautrix_telegram/portal.py", line 1057, in handle_matrix_message
    await self._handle_matrix_text(sender_id, event_id, space, client, message, reply_to)
  File "/opt/mautrix-telegram/mautrix_telegram/portal.py", line 960, in _handle_matrix_text
    link_preview=lp)
  File "/usr/lib/python3.6/site-packages/telethon/client/messages.py", line 513, in send_message
    result = await self(request)
  File "/usr/lib/python3.6/site-packages/telethon/client/users.py", line 59, in __call__
    result = await future
telethon.errors.rpcerrorlist.UserDeactivatedError: The user has been deleted/deactivated (caused by SendMessageRequest)
```

**Comment by tulir** [comment]
Moved to #543
