### ISSUE TITLE
Relay bot invites proxy's to Matrix channels, but those proxy's don't join.

### ISSUE THREAD

**Issue by Ryonez** [tulir/mautrix-telegram#310]
As the title says, I've linked a room to telegram.

When someone speaks, the bridge bot invites a proxy into the matrix room, but that proxy sits there without accepting the invite. This leaves the chat in a way way state only.

Example userlist:
![image](https://user-images.githubusercontent.com/16157130/56074812-b02f0200-5e0c-11e9-87be-04cd1ebcbb34.png)

**Comment by Ryonez** [comment]
Seems like nothing is posting to matrix from telegram.

**Comment by Ryonez** [comment]
Some logs, seems it can't make the accounts:

```
Traceback (most recent call last):
File "/opt/mautrix-telegram/mautrix_telegram/user.py", line 182, in post_login
await self.sync_dialogs()
File "/opt/mautrix-telegram/mautrix_telegram/user.py", line 306, in sync_dialogs
await asyncio.gather(*creators, loop=self.loop)
File "/opt/mautrix-telegram/mautrix_telegram/portal.py", line 349, in create_matrix_room
return await self._create_matrix_room(user, entity, invites)
File "/opt/mautrix-telegram/mautrix_telegram/portal.py", line 389, in _create_matrix_room
await self.main_intent.remove_room_alias(alias)
File "/usr/lib/python3.6/site-packages/mautrix_appservice/intent_api.py", line 136, in _send
errcode=errcode, message=message)
mautrix_appservice.errors.MatrixRequestError: 400: {"errcode":"M_EXCLUSIVE","error":"This application service has not reserved this kind of alias"}
[2019-04-13 20:44:10,728] [DEBUG@telethon.209554724.network.mtprotosender] Handling container
[2019-04-13 20:44:10,729] [DEBUG@telethon.209554724.network.mtprotosender] Handling RPC result for message 6679482674935947204
[2019-04-13 20:44:10,730] [DEBUG@telethon.209554724.network.mtprotosender] Handling acknowledge for [6679482674937414908, 6679482674938856864, 6679482674940222524, 6679482674941633964]
[2019-04-13 20:44:10,731] [DEBUG@telethon.209554724.network.mtprotosender] Receiving items from the network...
[2019-04-13 20:44:10,743] [DEBUG@telethon.209554724.extensions.messagepacker] Assigned msg_id = 6679482675848367476 to GetParticipantsRequest (146f1720f0f0)
[2019-04-13 20:44:10,744] [DEBUG@telethon.209554724.network.mtprotosender] Encrypting 1 message(s) in 56 bytes for sending
[2019-04-13 20:44:10,744] [DEBUG@telethon.209554724.network.mtprotosender] Encrypted messages put in a queue to be sent
[2019-04-13 20:44:10,744] [DEBUG@telethon.209554724.network.mtprotosender] Waiting for messages to send...
[2019-04-13 20:44:10,744] [DEBUG@telethon.209554724.extensions.messagepacker] Assigned msg_id = 6679482675853117728 to MsgsAck (146f1720f7b8)
[2019-04-13 20:44:10,745] [DEBUG@telethon.209554724.network.mtprotosender] Encrypting 1 message(s) in 52 bytes for sending
[2019-04-13 20:44:10,745] [DEBUG@telethon.209554724.network.mtprotosender] Encrypted messages put in a queue to be sent
[2019-04-13 20:44:10,746] [DEBUG@telethon.209554724.network.mtprotosender] Waiting for messages to send...
[2019-04-13 20:44:10,746] [DEBUG@telethon.209554724.network.mtprotosender] Handling RPC result for message 6679482674937414908
[2019-04-13 20:44:10,748] [DEBUG@telethon.209554724.network.mtprotosender] Receiving items from the network...
[2019-04-13 20:44:10,765] [DEBUG@mau.as.api] POST /register {"username": "telegram_598393830"} as user @telegram_598393830:matrix.alteria.xyz
[2019-04-13 20:44:10,768] [DEBUG@telethon.209554724.network.mtprotosender] Handling RPC result for message 6679482674938856864
[2019-04-13 20:44:10,769] [DEBUG@telethon.209554724.network.mtprotosender] Receiving items from the network...
[2019-04-13 20:44:10,784] [DEBUG@telethon.relaybot.network.mtprotosender] Handling RPC result for message 6679482675015989088
[2019-04-13 20:44:10,784] [DEBUG@telethon.relaybot.network.mtprotosender] Receiving items from the network...
[2019-04-13 20:44:10,785] [DEBUG@telethon.209554724.network.mtprotosender] Handling RPC result for message 6679482674940222524
[2019-04-13 20:44:10,787] [DEBUG@telethon.209554724.network.mtprotosender] Receiving items from the network...
[2019-04-13 20:44:10,787] [DEBUG@telethon.209554724.extensions.messagepacker] Assigned msg_id = 6679482676022469304 to GetParticipantsRequest (146f174cf588)
[2019-04-13 20:44:10,787] [DEBUG@telethon.209554724.network.mtprotosender] Encrypting 1 message(s) in 56 bytes for sending
[2019-04-13 20:44:10,787] [DEBUG@telethon.209554724.network.mtprotosender] Encrypted messages put in a queue to be sent
[2019-04-13 20:44:10,788] [DEBUG@telethon.209554724.network.mtprotosender] Waiting for messages to send...
[2019-04-13 20:44:10,788] [DEBUG@telethon.209554724.extensions.messagepacker] Assigned msg_id = 6679482676027036452 to MsgsAck (146f171ed2e8)
[2019-04-13 20:44:10,788] [DEBUG@telethon.209554724.network.mtprotosender] Encrypting 1 message(s) in 52 bytes for sending
[2019-04-13 20:44:10,814] [DEBUG@mau.as.api] POST /register {"username": "telegram_328551769"} as user @telegram_328551769:matrix.alteria.xyz
[2019-04-13 20:44:10,817] [ERROR@mau.as.intent] Failed to register @telegram_598393830:matrix.alteria.xyz!
Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/mautrix_appservice/intent_api.py", line 898, in ensure_registered
await self._register()
File "/usr/lib/python3.6/site-packages/mautrix_appservice/intent_api.py", line 136, in _send
errcode=errcode, message=message)
mautrix_appservice.errors.MatrixRequestError: 400: {"errcode":"M_EXCLUSIVE","error":"Invalid user localpart for this application service."}
[2019-04-13 20:44:10,818] [DEBUG@mau.as.api] POST /join/%21ptGFgOiVvFBuewkJKi%3Amatrix.alteria.xyz {} as user @telegram_598393830:matrix.alteria.xyz
[2019-04-13 20:44:10,821] [DEBUG@telethon.209554724.network.mtprotosender] Handling RPC result for message 6679482674941633964
[2019-04-13 20:44:10,822] [DEBUG@telethon.209554724.network.mtprotosender] Receiving items from the network...
[2019-04-13 20:44:10,823] [DEBUG@telethon.209554724.network.mtprotosender] Encrypted messages put in a queue to be sent
[2019-04-13 20:44:10,823] [DEBUG@telethon.209554724.network.mtprotosender] Waiting for messages to send...
[2019-04-13 20:44:10,824] [DEBUG@telethon.209554724.extensions.messagepacker] Assigned msg_id = 6679482676169502044 to MsgsAck (146f1721a0b8)
[2019-04-13 20:44:10,824] [DEBUG@telethon.209554724.network.mtprotosender] Encrypting 1 message(s) in 36 bytes for sending
[2019-04-13 20:44:10,825] [DEBUG@mau.init] Startup actions complete in 1.79 seconds, now running forever
[2019-04-13 20:44:10,841] [DEBUG@mau.as.api] POST /register {"username": "telegram_813014854"} as user @telegram_813014854:matrix.alteria.xyz
[2019-04-13 20:44:10,843] [DEBUG@telethon.209554724.network.mtprotosender] Encrypted messages put in a queue to be sent
[2019-04-13 20:44:10,844] [DEBUG@telethon.209554724.network.mtprotosender] Waiting for messages to send...
[2019-04-13 20:44:10,845] [ERROR@mau.as.intent] Failed to register @telegram_328551769:matrix.alteria.xyz!
Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/mautrix_appservice/intent_api.py", line 898, in ensure_registered
await self._register()
File "/usr/lib/python3.6/site-packages/mautrix_appservice/intent_api.py", line 136, in _send
errcode=errcode, message=message)
mautrix_appservice.errors.MatrixRequestError: 400: {"errcode":"M_EXCLUSIVE","error":"Invalid user localpart for this application service."}
```

**Comment by Ryonez** [comment]
Okay, I did resolve this.

It seems I had some incorrect values in the registration file, and the namespace regex was incorrect (The domain wasn't fully in place).

Sorry for the trouble.
