### ISSUE TITLE
telethon ImportError preventing startup

### ISSUE THREAD

**Issue by TheReverend403** [tulir/mautrix-telegram#320]
Running commit fce22b08e9e64b9c41763747bff95e3e36009c8d (current HEAD at time of writing)

```
May 06 16:33:38 firefly.revthefox.co.uk systemd[1]: Started Telegram-Matrix bridge.
May 06 16:33:39 firefly.revthefox.co.uk mautrix[1294]: Traceback (most recent call last):
May 06 16:33:39 firefly.revthefox.co.uk mautrix[1294]:   File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
May 06 16:33:39 firefly.revthefox.co.uk mautrix[1294]:     "__main__", mod_spec)
May 06 16:33:39 firefly.revthefox.co.uk mautrix[1294]:   File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
May 06 16:33:39 firefly.revthefox.co.uk mautrix[1294]:     exec(code, run_globals)
May 06 16:33:39 firefly.revthefox.co.uk mautrix[1294]:   File "/opt/synapse/mautrix-telegram/mautrix_telegram/__main__.py", line 31, in <module>
May 06 16:33:39 firefly.revthefox.co.uk mautrix[1294]:     from .web.provisioning import ProvisioningAPI
May 06 16:33:39 firefly.revthefox.co.uk mautrix[1294]:   File "/opt/synapse/mautrix-telegram/mautrix_telegram/web/__init__.py", line 1, in <module>
May 06 16:33:39 firefly.revthefox.co.uk mautrix[1294]:     from .provisioning import ProvisioningAPI
May 06 16:33:39 firefly.revthefox.co.uk mautrix[1294]:   File "/opt/synapse/mautrix-telegram/mautrix_telegram/web/provisioning/__init__.py", line 28, in <module>
May 06 16:33:39 firefly.revthefox.co.uk mautrix[1294]:     from ...user import User
May 06 16:33:39 firefly.revthefox.co.uk mautrix[1294]:   File "/opt/synapse/mautrix-telegram/mautrix_telegram/user.py", line 32, in <module>
May 06 16:33:39 firefly.revthefox.co.uk mautrix[1294]:     from .abstract_user import AbstractUser
May 06 16:33:39 firefly.revthefox.co.uk mautrix[1294]:   File "/opt/synapse/mautrix-telegram/mautrix_telegram/abstract_user.py", line 35, in <module>
May 06 16:33:39 firefly.revthefox.co.uk mautrix[1294]:     from . import portal as po, puppet as pu, __version__
May 06 16:33:39 firefly.revthefox.co.uk mautrix[1294]:   File "/opt/synapse/mautrix-telegram/mautrix_telegram/portal.py", line 48, in <module>
May 06 16:33:39 firefly.revthefox.co.uk mautrix[1294]:     from telethon.tl.types import (
May 06 16:33:39 firefly.revthefox.co.uk mautrix[1294]: ImportError: cannot import name 'FileLocation' from 'telethon.tl.types' (/opt/synapse/mautrix-telegram/env/lib/python3.7/site-packages/telethon/tl/types/__init__.py)
```

**Comment by tulir** [comment]
Too new Telethon, 1.7 isn't supported yet. Added warning about dependency versions in development setup guide.
