### ISSUE TITLE
Error preventing startup: readexactly() called while another coroutine is already waiting for incoming data

### ISSUE THREAD

**Issue by turt2live** [tulir/mautrix-telegram#329]
Happens to a random puppet during startup, preventing the bridge from running. 

```
Jun  3 15:12:37 integrations python[863]: [2019-06-03 15:12:37,269] [ERROR@telethon.582redacted.network.connection.connection] Unexpected exception in the receive loop
Jun  3 15:12:37 integrations python[863]: Traceback (most recent call last):
Jun  3 15:12:37 integrations python[863]:   File "/home/telegram/tgenv/lib/python3.6/site-packages/telethon/network/connection/connection.py", line 149, in _recv_loop
Jun  3 15:12:37 integrations python[863]:     data = await self._recv()
Jun  3 15:12:37 integrations python[863]:   File "/home/telegram/tgenv/lib/python3.6/site-packages/telethon/network/connection/tcpfull.py", line 33, in _recv
Jun  3 15:12:37 integrations python[863]:     body = await self._reader.readexactly(packet_len - 8)
Jun  3 15:12:37 integrations python[863]:   File "/usr/lib/python3.6/asyncio/streams.py", line 674, in readexactly
Jun  3 15:12:37 integrations python[863]:     yield from self._wait_for_data('readexactly')
Jun  3 15:12:37 integrations python[863]:   File "/usr/lib/python3.6/asyncio/streams.py", line 452, in _wait_for_data
Jun  3 15:12:37 integrations python[863]:     'already waiting for incoming data' % func_name)
Jun  3 15:12:37 integrations python[863]: RuntimeError: readexactly() called while another coroutine is already waiting for incoming data
```

**Comment by turt2live** [comment]
workaround: https://github.com/t2bot/mautrix-telegram/commit/51f6dd74baf4d8945b4503d148cfadfc006df71e

**Comment by tulir** [comment]
This is hopefully fixed by locking client.connect() calls
