### ISSUE TITLE
Cannot login using phone_number + code mechanism over Matrix

### ISSUE THREAD

**Issue by Half-Shot** [tulir/mautrix-telegram#354]
Using the `latest` docker image.

Telethon seems to struggle:

```
[2019-08-16 16:52:23,468] [ERROR@mau.commands] Error requesting phone code
Traceback (most recent call last):
  File "/opt/mautrix-telegram/mautrix_telegram/commands/telegram/auth.py", line 150, in _request_code
    await evt.sender.client.sign_in(phone_number)
  File "/usr/lib/python3.7/site-packages/telethon/client/auth.py", line 319, in sign_in
    return await self.send_code_request(phone)
  File "/usr/lib/python3.7/site-packages/telethon/client/auth.py", line 478, in send_code_request
    self._tos = result.terms_of_service
AttributeError: 'SentCode' object has no attribute 'terms_of_service'
```

**Comment by Lonami** [comment]
Thanks for the report. Could you check if https://github.com/LonamiWebs/Telethon/commit/42874de2b263c6050349c0c9df0ef6cb954b151c fixed it?

**Comment by Half-Shot** [comment]
*looks to @tulir to see if he wants to fold the bugfix into `master`*

**Comment by tulir** [comment]
I rebuilt the docker image
