### ISSUE TITLE
"Fatal error updating Matrix room"

### ISSUE THREAD

**Issue by olmari** [tulir/mautrix-telegram#356]
6bccf5595ba94325d9b58f2f87a4ae103ff8c797 of master gives these occasionally, but genreally stuff seems to still work

```
Aug 16 20:42:31 matrix python[22065]: [2019-08-16 20:42:31,536] [INFO@telethon.72343648.client.downloads] Starting direct file download in chunks of 65536 at 0, stride 65536
Aug 16 20:42:32 matrix python[22065]: [2019-08-16 20:42:32,402] [ERROR@mau.portal.1239518599] Fatal error updating Matrix room
Aug 16 20:42:32 matrix python[22065]: Traceback (most recent call last):
Aug 16 20:42:32 matrix python[22065]:   File "/opt/mautrix-telegram/lib/python3.6/site-packages/mautrix_telegram/portal/metadata.py", line 200, in update_matrix_room
Aug 16 20:42:32 matrix python[22065]:     participants)
Aug 16 20:42:32 matrix python[22065]:   File "/opt/mautrix-telegram/lib/python3.6/site-packages/mautrix_telegram/portal/metadata.py", line 214, in _update_matrix_room
Aug 16 20:42:32 matrix python[22065]:     await self.update_telegram_participants(participants, levels)
Aug 16 20:42:32 matrix python[22065]:   File "/opt/mautrix-telegram/lib/python3.6/site-packages/mautrix_telegram/portal/metadata.py", line 412, in update_telegram_participants
Aug 16 20:42:32 matrix python[22065]:     await self.main_intent.set_power_levels(self.mxid, levels)
Aug 16 20:42:32 matrix python[22065]:   File "/opt/mautrix-telegram/lib/python3.6/site-packages/mautrix/appservice/api/intent.py", line 200, in set_power_levels
Aug 16 20:42:32 matrix python[22065]:     **kwargs)
Aug 16 20:42:32 matrix python[22065]:   File "/opt/mautrix-telegram/lib/python3.6/site-packages/mautrix/appservice/api/intent.py", line 88, in wrapper
Aug 16 20:42:32 matrix python[22065]:     return await __method(*args, **kwargs)
Aug 16 20:42:32 matrix python[22065]:   File "/opt/mautrix-telegram/lib/python3.6/site-packages/mautrix/appservice/api/intent.py", line 296, in send_state_event
Aug 16 20:42:32 matrix python[22065]:     return await super().send_state_event(room_id, event_type, content, state_key, **kwargs)
Aug 16 20:42:32 matrix python[22065]:   File "/opt/mautrix-telegram/lib/python3.6/site-packages/mautrix/client/api/events.py", line 245, in send_state_event
Aug 16 20:42:32 matrix python[22065]:     content, **kwargs)
Aug 16 20:42:32 matrix python[22065]:   File "/opt/mautrix-telegram/lib/python3.6/site-packages/mautrix/api/http.py", line 199, in request
Aug 16 20:42:32 matrix python[22065]:     content = json.dumps(content)
Aug 16 20:42:32 matrix python[22065]:   File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
Aug 16 20:42:32 matrix python[22065]:     return _default_encoder.encode(obj)
Aug 16 20:42:32 matrix python[22065]:   File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
Aug 16 20:42:32 matrix python[22065]:     chunks = self.iterencode(o, _one_shot=True)
Aug 16 20:42:32 matrix python[22065]:   File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
Aug 16 20:42:32 matrix python[22065]:     return _iterencode(o, 0)
Aug 16 20:42:32 matrix python[22065]: TypeError: keys must be a string
```

Used these commands to upgrade, if that matters:

```
telegrambot@matrix:~$ source bin/activate
(mautrix-telegram) telegrambot@matrix:~$ pip install --upgrade https://github.com/tulir/mautrix-telegram/tarball/master#egg=mautrix-telegram[all]
(mautrix-telegram) telegrambot@matrix:~$ alembic upgrade head
```

No errors reported.

**Comment by olmari** [comment]
After de4c16431dd71ec7d55e270006b2a865b24ce1e2 I get more info on error:

```
Aug 17 13:55:11 matrix python[3724]: [2019-08-17 13:55:11,983] [ERROR@mau.portal.1102287046] Fatal error updating Matrix room
Aug 17 13:55:11 matrix python[3724]: Traceback (most recent call last):
Aug 17 13:55:11 matrix python[3724]:   File "/opt/mautrix-telegram/lib/python3.6/site-packages/mautrix_telegram/portal/metadata.py", line 200, in update_matrix_room
Aug 17 13:55:11 matrix python[3724]:     participants)
Aug 17 13:55:11 matrix python[3724]:   File "/opt/mautrix-telegram/lib/python3.6/site-packages/mautrix_telegram/portal/metadata.py", line 214, in _update_matrix_room
Aug 17 13:55:11 matrix python[3724]:     await self.update_telegram_participants(participants, levels)
Aug 17 13:55:11 matrix python[3724]:   File "/opt/mautrix-telegram/lib/python3.6/site-packages/mautrix_telegram/portal/metadata.py", line 412, in update_telegram_participants
Aug 17 13:55:11 matrix python[3724]:     await self.main_intent.set_power_levels(self.mxid, levels)
Aug 17 13:55:11 matrix python[3724]:   File "/opt/mautrix-telegram/lib/python3.6/site-packages/mautrix/appservice/api/intent.py", line 200, in set_power_levels
Aug 17 13:55:11 matrix python[3724]:     **kwargs)
Aug 17 13:55:11 matrix python[3724]:   File "/opt/mautrix-telegram/lib/python3.6/site-packages/mautrix/appservice/api/intent.py", line 88, in wrapper
Aug 17 13:55:11 matrix python[3724]:     return await __method(*args, **kwargs)
Aug 17 13:55:11 matrix python[3724]:   File "/opt/mautrix-telegram/lib/python3.6/site-packages/mautrix/appservice/api/intent.py", line 296, in send_state_event
Aug 17 13:55:11 matrix python[3724]:     return await super().send_state_event(room_id, event_type, content, state_key, **kwargs)
Aug 17 13:55:11 matrix python[3724]:   File "/opt/mautrix-telegram/lib/python3.6/site-packages/mautrix/client/api/events.py", line 245, in send_state_event
Aug 17 13:55:11 matrix python[3724]:     content, **kwargs)
Aug 17 13:55:11 matrix python[3724]:   File "/opt/mautrix-telegram/lib/python3.6/site-packages/mautrix/api/http.py", line 199, in request
Aug 17 13:55:11 matrix python[3724]:     content = json.dumps(content)
Aug 17 13:55:11 matrix python[3724]:   File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
Aug 17 13:55:11 matrix python[3724]:     return _default_encoder.encode(obj)
Aug 17 13:55:11 matrix python[3724]:   File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
Aug 17 13:55:11 matrix python[3724]:     chunks = self.iterencode(o, _one_shot=True)
Aug 17 13:55:11 matrix python[3724]:   File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
Aug 17 13:55:11 matrix python[3724]:     return _iterencode(o, 0)
Aug 17 13:55:11 matrix python[3724]: TypeError: keys must be a string
```

**Comment by olmari** [comment]
```
Aug 17 14:11:22 matrix python[4038]: [2019-08-17 14:11:22,170] [DEBUG@telethon.72343648.network.mtprotosender] Encrypting 1 message(s) in 52 bytes for sending
Aug 17 14:11:22 matrix python[4038]: [2019-08-17 14:11:22,172] [ERROR@mau.portal.1105400496] Fatal error updating Matrix room
Aug 17 14:11:22 matrix python[4038]: Traceback (most recent call last):
Aug 17 14:11:22 matrix python[4038]:   File "/opt/mautrix-telegram/lib/python3.6/site-packages/mautrix_telegram/portal/metadata.py", line 200, in update_matrix_room
Aug 17 14:11:22 matrix python[4038]:     participants)
Aug 17 14:11:22 matrix python[4038]:   File "/opt/mautrix-telegram/lib/python3.6/site-packages/mautrix_telegram/portal/metadata.py", line 214, in _update_matrix_room
Aug 17 14:11:22 matrix python[4038]:     await self.update_telegram_participants(participants, levels)
Aug 17 14:11:22 matrix python[4038]:   File "/opt/mautrix-telegram/lib/python3.6/site-packages/mautrix_telegram/portal/metadata.py", line 412, in update_telegram_participants
Aug 17 14:11:22 matrix python[4038]:     await self.main_intent.set_power_levels(self.mxid, levels)
Aug 17 14:11:22 matrix python[4038]:   File "/opt/mautrix-telegram/lib/python3.6/site-packages/mautrix/appservice/api/intent.py", line 200, in set_power_levels
Aug 17 14:11:22 matrix python[4038]:     **kwargs)
Aug 17 14:11:22 matrix python[4038]:   File "/opt/mautrix-telegram/lib/python3.6/site-packages/mautrix/appservice/api/intent.py", line 88, in wrapper
Aug 17 14:11:22 matrix python[4038]:     return await __method(*args, **kwargs)
Aug 17 14:11:22 matrix python[4038]:   File "/opt/mautrix-telegram/lib/python3.6/site-packages/mautrix/appservice/api/intent.py", line 296, in send_state_event
Aug 17 14:11:22 matrix python[4038]:     return await super().send_state_event(room_id, event_type, content, state_key, **kwargs)
Aug 17 14:11:22 matrix python[4038]:   File "/opt/mautrix-telegram/lib/python3.6/site-packages/mautrix/client/api/events.py", line 245, in send_state_event
Aug 17 14:11:22 matrix python[4038]:     content, **kwargs)
Aug 17 14:11:22 matrix python[4038]:   File "/opt/mautrix-telegram/lib/python3.6/site-packages/mautrix/api/http.py", line 199, in request
Aug 17 14:11:22 matrix python[4038]:     content = json.dumps(content)
Aug 17 14:11:22 matrix python[4038]:   File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
Aug 17 14:11:22 matrix python[4038]:     return _default_encoder.encode(obj)
Aug 17 14:11:22 matrix python[4038]:   File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
Aug 17 14:11:22 matrix python[4038]:     chunks = self.iterencode(o, _one_shot=True)
Aug 17 14:11:22 matrix python[4038]:   File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
Aug 17 14:11:22 matrix python[4038]:     return _iterencode(o, 0)
Aug 17 14:11:22 matrix python[4038]: TypeError: keys must be a string
```

**Comment by olmari** [comment]
```
Aug 19 18:10:42 matrix python[16956]: [2019-08-19 18:10:42,760] [DEBUG@mau.portal.1102287046] LOGSPAM update_telegram_participants 1
Aug 19 18:10:42 matrix python[16956]: [2019-08-19 18:10:42,766] [DEBUG@mau.portal.1102287046] LOGSPAM update_telegram_participants 2: PowerLevelStateEventContent(users={'@telegrambot:hacklab.fi': 100, '@_telegram_205542298:hacklab.fi': 95, '@_telegram_260510821:hacklab.fi': 50, '@_telegram_234518096:hacklab.fi': 50}, users_default=0, events={'m.room.name': 50, 'm.room.avatar': 50, 'm.room.topic': 50, 'm.room.pinned_events': 50, 'm.room.power_levels': 75, 'm.room.history_visibility': 75, 'm.sticker': 50}, events_default=0, state_default=50, invite=50, kick=50, ban=99, redact=50)
Aug 19 18:10:42 matrix python[16956]: [2019-08-19 18:10:42,766] [DEBUG@mau.portal.1102287046] LOGSPAM update_telegram_participants 3: {'users': {'@telegrambot:hacklab.fi': 100, '@_telegram_205542298:hacklab.fi': 95, '@_telegram_260510821:hacklab.fi': 50, '@_telegram_234518096:hacklab.fi': 50}, 'users_default': 0, 'events': {'m.room.name': 50, 'm.room.avatar': 50, 'm.room.topic': 50, 'm.room.pinned_events': 50, 'm.room.power_levels': 75, 'm.room.history_visibility': 75, 'm.sticker': 50}, 'events_default': 0, 'state_default': 50, 'invite': 50, 'kick': 50, 'ban': 99, 'redact': 50}
Aug 19 18:10:42 matrix python[16956]: [2019-08-19 18:10:42,893] [DEBUG@mau.portal.1102287046] LOGSPAM update_telegram_participants 4: {'users': {'@telegrambot:hacklab.fi': 100, '@_telegram_205542298:hacklab.fi': 95, '@_telegram_260510821:hacklab.fi': 50, '@_telegram_234518096:hacklab.fi': 50}, 'users_default': 0, 'events': {'m.room.name': 50, 'm.room.avatar': 50, 'm.room.topic': 50, 'm.room.pinned_events': 50, 'm.room.power_levels': 75, 'm.room.history_visibility': 75, 'm.sticker': 50, EventType("m.room.power_levels", EventType.Class.STATE): 75}, 'events_default': 0, 'state_default': 50, 'invite': 50, 'kick': 50, 'ban': 99, 'redact': 50}
Aug 19 18:10:42 matrix python[16956]: [2019-08-19 18:10:42,894] [DEBUG@mau.as.api.bot] Failed to json.dumps({'users': {'@telegrambot:hacklab.fi': 100, '@_telegram_205542298:hacklab.fi': 95, '@_telegram_260510821:hacklab.fi': 50, '@_telegram_234518096:hacklab.fi': 50}, 'users_default': 0, 'events': {'m.room.name': 50, 'm.room.avatar': 50, 'm.room.topic': 50, 'm.room.pinned_events': 50, 'm.room.power_levels': 75, 'm.room.history_visibility': 75, 'm.sticker': 50, EventType("m.room.power_levels", EventType.Class.STATE): 75}, 'events_default': 0, 'state_default': 50, 'invite': 50, 'kick': 50, 'ban': 99, 'redact': 50})
Aug 19 18:10:42 matrix python[16956]: [2019-08-19 18:10:42,894] [ERROR@mau.portal.1102287046] LOGSPAM failed to update telegram participants
Aug 19 18:10:42 matrix python[16956]: Traceback (most recent call last):
Aug 19 18:10:42 matrix python[16956]:   File "/opt/mautrix-telegram/lib/python3.6/site-packages/mautrix_telegram/portal/metadata.py", line 215, in _update_matrix_room
Aug 19 18:10:42 matrix python[16956]:     await self.update_telegram_participants(participants, levels)
Aug 19 18:10:42 matrix python[16956]:   File "/opt/mautrix-telegram/lib/python3.6/site-packages/mautrix_telegram/portal/metadata.py", line 419, in update_telegram_participants
Aug 19 18:10:42 matrix python[16956]:     await self.main_intent.set_power_levels(self.mxid, levels)
Aug 19 18:10:42 matrix python[16956]:   File "/opt/mautrix-telegram/lib/python3.6/site-packages/mautrix/appservice/api/intent.py", line 200, in set_power_levels
Aug 19 18:10:42 matrix python[16956]:     **kwargs)
Aug 19 18:10:42 matrix python[16956]:   File "/opt/mautrix-telegram/lib/python3.6/site-packages/mautrix/appservice/api/intent.py", line 88, in wrapper
Aug 19 18:10:42 matrix python[16956]:     return await __method(*args, **kwargs)
Aug 19 18:10:42 matrix python[16956]:   File "/opt/mautrix-telegram/lib/python3.6/site-packages/mautrix/appservice/api/intent.py", line 296, in send_state_event
Aug 19 18:10:42 matrix python[16956]:     return await super().send_state_event(room_id, event_type, content, state_key, **kwargs)
Aug 19 18:10:42 matrix python[16956]:   File "/opt/mautrix-telegram/lib/python3.6/site-packages/mautrix/client/api/events.py", line 251, in send_state_event
Aug 19 18:10:42 matrix python[16956]:     content, **kwargs)
Aug 19 18:10:42 matrix python[16956]:   File "/opt/mautrix-telegram/lib/python3.6/site-packages/mautrix/api/http.py", line 200, in request
Aug 19 18:10:42 matrix python[16956]:     content = json.dumps(content)
Aug 19 18:10:42 matrix python[16956]:   File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
Aug 19 18:10:42 matrix python[16956]:     return _default_encoder.encode(obj)
Aug 19 18:10:42 matrix python[16956]:   File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
Aug 19 18:10:42 matrix python[16956]:     chunks = self.iterencode(o, _one_shot=True)
Aug 19 18:10:42 matrix python[16956]:   File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
Aug 19 18:10:42 matrix python[16956]:     return _iterencode(o, 0)
Aug 19 18:10:42 matrix python[16956]: TypeError: keys must be a string
```

**Comment by olmari** [comment]
With latest debug builds for this problem seems to be fixed now. :)
