### ISSUE TITLE
ChatIdInvalidError should not prevent `sync chats` from working

### ISSUE THREAD

**Issue by turt2live** [tulir/mautrix-telegram#358]
```
Aug 22 15:06:25 integrations python[11187]: [2019-08-22 15:06:25,548] [ERROR@mau.commands] Unhandled error while handling command sync chats from @redacted:example.org
Aug 22 15:06:25 integrations python[11187]: Traceback (most recent call last):
Aug 22 15:06:25 integrations python[11187]:   File "/home/telegram/tgenv/lib/python3.6/site-packages/mautrix_telegram/commands/handler.py", line 352, in handle
Aug 22 15:06:25 integrations python[11187]:     await handler(evt)
Aug 22 15:06:25 integrations python[11187]:   File "/home/telegram/tgenv/lib/python3.6/site-packages/mautrix_telegram/commands/handler.py", line 274, in __call__
Aug 22 15:06:25 integrations python[11187]:     return await self._handler(evt)
Aug 22 15:06:25 integrations python[11187]:   File "/home/telegram/tgenv/lib/python3.6/site-packages/mautrix_telegram/commands/telegram/misc.py", line 162, in sync
Aug 22 15:06:25 integrations python[11187]:     await evt.sender.sync_dialogs(synchronous_create=True)
Aug 22 15:06:25 integrations python[11187]:   File "/home/telegram/tgenv/lib/python3.6/site-packages/mautrix_telegram/user.py", line 306, in sync_dialogs
Aug 22 15:06:25 integrations python[11187]:     await asyncio.gather(*creators, loop=self.loop)
Aug 22 15:06:25 integrations python[11187]:   File "/home/telegram/tgenv/lib/python3.6/site-packages/mautrix_telegram/portal.py", line 349, in create_matrix_room
Aug 22 15:06:25 integrations python[11187]:     return await self._create_matrix_room(user, entity, invites)
Aug 22 15:06:25 integrations python[11187]:   File "/home/telegram/tgenv/lib/python3.6/site-packages/mautrix_telegram/portal.py", line 394, in _create_matrix_room
Aug 22 15:06:25 integrations python[11187]:     users, participants = await self._get_users(user, entity)
Aug 22 15:06:25 integrations python[11187]:   File "/home/telegram/tgenv/lib/python3.6/site-packages/mautrix_telegram/portal.py", line 685, in _get_users
Aug 22 15:06:25 integrations python[11187]:     chat = await user.client(GetFullChatRequest(chat_id=self.tgid))
Aug 22 15:06:25 integrations python[11187]:   File "/home/telegram/tgenv/lib/python3.6/site-packages/telethon/client/users.py", line 64, in __call__
Aug 22 15:06:25 integrations python[11187]:     result = await future
Aug 22 15:06:25 integrations python[11187]: telethon.errors.rpcerrorlist.ChatIdInvalidError: Invalid object ID for a chat. Make sure to pass the right types, for instance making sure that the request is designed for chats (not channels/megagroups) or otherwise look for a different one more suited\nAn example working with a megagroup and AddChatUserRequest, it will fail because megagroups are channels. Use InviteToChannelRequest instead (caused by GetFullChatRequest)
```

It might want to warn that a room wasn't updated, but it shouldn't prevent all other rooms from updating.

**Comment by tulir** [comment]
Looks like this was already fixed at some point earlier.
