### ISSUE TITLE
YAML errors are not handled in !tg config

### ISSUE THREAD

**Issue by Zauberstuhl** [tulir/mautrix-telegram#377]
Since I am completely unfamiliar how the backend works I am not sure if that is a real bug/feature still I want to report it.

It would be nice if I execute `!tg config add bridge_notices.exceptions @gitlab:t2bot.io` the command succeeds. It would be more intuitive! Currently this doesn't work because of the `@` symbol:

```
8262:[2019-11-06 11:25:36,231] [ERROR@mau.commands] Unhandled error while handling command config add bridge_notices.exceptions @gitlab:t2bot.io from @zauberstuhl:feneas.org (ref: 156738335)
8263-Traceback (most recent call last):
8264-  File "/usr/lib/python3.7/site-packages/mautrix/bridge/commands/handler.py", line 371, in handle
8265-    await self._run_handler(handler, evt)
8266-  File "/opt/mautrix-telegram/mautrix_telegram/commands/handler.py", line 126, in _run_handler
8267-    return await handler(evt)
8268-  File "/usr/lib/python3.7/site-packages/mautrix/bridge/commands/handler.py", line 269, in __call__
8269-    return await self._handler(evt)
8270-  File "/opt/mautrix-telegram/mautrix_telegram/commands/portal/config.py", line 47, in config
8271-    value = yaml.load(" ".join(evt.args[2:])) if len(evt.args) > 2 else None
8272-  File "/usr/lib/python3.7/site-packages/ruamel/yaml/main.py", line 331, in load
8273-    return constructor.get_single_data()
8274-  File "/usr/lib/python3.7/site-packages/ruamel/yaml/constructor.py", line 109, in get_single_data
8275-    node = self.composer.get_single_node()
8276-  File "/usr/lib/python3.7/site-packages/ruamel/yaml/composer.py", line 73, in get_single_node
8277-    self.parser.get_event()
8278-  File "/usr/lib/python3.7/site-packages/ruamel/yaml/parser.py", line 163, in get_event
8279-    self.current_event = self.state()
8280-  File "/usr/lib/python3.7/site-packages/ruamel/yaml/parser.py", line 176, in parse_stream_start
8281-    token = self.scanner.get_token()
8282-  File "/usr/lib/python3.7/site-packages/ruamel/yaml/scanner.py", line 1810, in get_token
8283-    self._gather_comments()
8284-  File "/usr/lib/python3.7/site-packages/ruamel/yaml/scanner.py", line 1803, in _gather_comments
8285-    self.fetch_more_tokens()
8286-  File "/usr/lib/python3.7/site-packages/ruamel/yaml/scanner.py", line 321, in fetch_more_tokens
8287-    self.reader.get_mark(),
8288-ruamel.yaml.scanner.ScannerError: while scanning for the next token
8289-found character '@' that cannot start any token
8290-  in "<unicode string>", line 1, column 1:
8291-    @gitlab:t2bot.io
8292-    ^ (line: 1)
8293:[2019-11-06 11:25:36,285] [DEBUG@mau.as.api.bot] PUT /_matrix/client/r0/rooms/%21XTcFGXYoSwwJPindtt%3Afeneas.org/send/m.room.message/747791573039536284 {"msgtype": "m.notice", "body": "Unhandled error while handling command. Check logs for more details (ref: 1567383350).", "format": "org.matrix.custom.html", "formatted_body": "<p>Unhandled error while handling command. Check logs for more details (ref: 1567383350).</p>\n"}
```

**Comment by tulir** [comment]
Not sure if there's any safe way to do this (other than maybe making simpler alternative commands), the `!tg config` command wants YAML as input
