### ISSUE TITLE
Anti-flood spews errors

### ISSUE THREAD

**Issue by turt2live** [tulir/mautrix-telegram#380]
Someone set up a bot to post roughly 15Hz of events into a room, which caused the Telegram bridge to try and bridge them all. This is repeated over and over in my logs:

```
Nov 18 05:21:43 integrations python[8124]: [2019-11-18 05:21:43,069] [ERROR@mau.as] Exception in Matrix event handler
Nov 18 05:21:43 integrations python[8124]: Traceback (most recent call last):
Nov 18 05:21:43 integrations python[8124]:   File "/home/telegram/tgenv/lib/python3.6/site-packages/mautrix_appservice/appservice.py", line 173, in try_handle
Nov 18 05:21:43 integrations python[8124]:     await handler_func(event)
Nov 18 05:21:43 integrations python[8124]:   File "/home/telegram/tgenv/lib/python3.6/site-packages/mautrix_telegram/matrix.py", line 470, in handle_event
Nov 18 05:21:43 integrations python[8124]:     await self.handle_message(room_id, sender, content, event_id)
Nov 18 05:21:43 integrations python[8124]:   File "/home/telegram/tgenv/lib/python3.6/site-packages/mautrix_telegram/matrix.py", line 260, in handle_message
Nov 18 05:21:43 integrations python[8124]:     await portal.handle_matrix_message(sender, message, event_id)
Nov 18 05:21:43 integrations python[8124]:   File "/home/telegram/tgenv/lib/python3.6/site-packages/mautrix_telegram/portal.py", line 1135, in handle_matrix_message
Nov 18 05:21:43 integrations python[8124]:     await self._handle_matrix_text(sender_id, event_id, space, client, message, reply_to)
Nov 18 05:21:43 integrations python[8124]:   File "/home/telegram/tgenv/lib/python3.6/site-packages/mautrix_telegram/portal.py", line 1012, in _handle_matrix_text
Nov 18 05:21:43 integrations python[8124]:     link_preview=lp)
Nov 18 05:21:43 integrations python[8124]:   File "/home/telegram/tgenv/lib/python3.6/site-packages/telethon/client/messages.py", line 715, in send_message
Nov 18 05:21:43 integrations python[8124]:     result = await self(request)
Nov 18 05:21:43 integrations python[8124]:   File "/home/telegram/tgenv/lib/python3.6/site-packages/telethon/client/users.py", line 31, in __call__
Nov 18 05:21:43 integrations python[8124]:     elif diff <= self.flood_sleep_threshold:
Nov 18 05:21:43 integrations python[8124]: TypeError: '<=' not supported between instances of 'int' and 'NoneType'
```

Version: 0.6.1

**Comment by tulir** [comment]
Do you have [`telegram.connection.flood_sleep_threshold`](https://github.com/tulir/mautrix-telegram/blob/master/example-config.yaml#L331-L335) set to a non-null value?

**Comment by turt2live** [comment]
Looks like not. Fixed now.
