### ISSUE TITLE
T>M throws Exeption LookupError

### ISSUE THREAD

**Issue by L0ric0** [tulir/mautrix-telegram#382]
When recieving a message from telegram i'm getting the following error

```
[ERROR@mau.portal.1493557676] Fatal error updating Matrix room
  Traceback (most recent call last):
    File "/opt/matrix/mautrix-telegram/lib/python3.8/site-packages/sqlalchemy/sql/sqltypes.py", line 1513, in _object_value_for_elem
      return self._object_lookup[elem]
    KeyError: 'join'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/matrix/mautrix-telegram/lib/python3.8/site-packages/mautrix_telegram/portal/metadata.py", line 200, in update_matrix_room
    await self._update_matrix_room(user, entity, direct, puppet, levels, users,
  File "/opt/matrix/mautrix-telegram/lib/python3.8/site-packages/mautrix_telegram/portal/metadata.py", line 214, in _update_matrix_room
    await self._sync_telegram_users(user, users)
  File "/opt/matrix/mautrix-telegram/lib/python3.8/site-packages/mautrix_telegram/portal/metadata.py", line 472, in _sync_telegram_users
    await puppet.intent_for(self).ensure_joined(self.mxid)
  File "/opt/matrix/mautrix-telegram/lib/python3.8/site-packages/mautrix/appservice/api/intent.py", line 353, in ensure_joined
    if not ignore_cache and self.state_store.is_joined(room_id, self.mxid):
  File "/opt/matrix/mautrix-telegram/lib/python3.8/site-packages/mautrix/appservice/state_store/abstract.py", line 100, in is_joined
    return self.get_membership(room_id, user_id) == Membership.JOIN
  File "/opt/matrix/mautrix-telegram/lib/python3.8/site-packages/mautrix/appservice/state_store/abstract.py", line 97, in get_membership
    return self.get_member(room_id, user_id).membership or Membership.LEAVE
  File "/opt/matrix/mautrix-telegram/lib/python3.8/site-packages/mautrix/bridge/db/sqlstatestore.py", line 62, in get_member
    return self._get_user_profile(room_id, user_id).member()
  File "/opt/matrix/mautrix-telegram/lib/python3.8/site-packages/mautrix/bridge/db/sqlstatestore.py", line 48, in _get_user_profile
    profile = UserProfile.get(*key)
  File "/opt/matrix/mautrix-telegram/lib/python3.8/site-packages/mautrix/bridge/db/mx_user_profile.py", line 30, in get
    return cls._select_one_or_none(and_(cls.c.room_id == room_id, cls.c.user_id == user_id))
  File "/opt/matrix/mautrix-telegram/lib/python3.8/site-packages/mautrix/util/db/base.py", line 135, in _select_one_or_none
    return cls._one_or_none(cls.db.execute(cls._make_simple_select(*args)))
  File "/opt/matrix/mautrix-telegram/lib/python3.8/site-packages/mautrix/util/db/base.py", line 59, in _one_or_none
    return cls.scan(next(rows))
  File "/opt/matrix/mautrix-telegram/lib/python3.8/site-packages/mautrix/util/db/base.py", line 88, in scan
    return cls(**dict(zip(cls.column_names, row)))
  File "/opt/matrix/mautrix-telegram/lib/python3.8/site-packages/sqlalchemy/sql/sqltypes.py", line 1599, in process
    value = self._object_value_for_elem(value)
  File "/opt/matrix/mautrix-telegram/lib/python3.8/site-packages/sqlalchemy/sql/sqltypes.py", line 1515, in _object_value_for_elem
    raise LookupError(
  LookupError: "join" is not among the defined enum values
```

**Comment by L0ric0** [comment]
fixed it with `UPDATE mx_user_profile SET membership=UPPER(membership);`
