### ISSUE TITLE
The bridge is constantly crashing with struct.error

### ISSUE THREAD

**Issue by verymilan** [tulir/mautrix-telegram#383]
Hi there, i've reported this in the matrix group some time ago already, at that time, my setup was a bit messy - however, this time it is cleanly installed, as recommended in your wiki for a production setup - i didn't find any other report for this which kinda surprises, but maybe it is because i've migrated from telematrix(?).

Due to systemd, it is kinda working anyway but is down like every few seconds, which is not very ...nice - for example for the public endpoint.^^

````
[2019-11-22 12:35:14,749] [ERROR@mau.init] Unexpected error
Traceback (most recent call last):
  File "mautrix-telegram-bridge/lib/python3.7/site-packages/mautrix_telegram/__main__.py", line 150, in <module>
    loop.run_until_complete(asyncio.gather(*startup_actions, loop=loop))
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "mautrix-telegram-bridge/lib/python3.7/site-packages/mautrix_telegram/bot.py", line 89, in start
    await self.post_login()
  File "mautrix-telegram-bridge/lib/python3.7/site-packages/mautrix_telegram/bot.py", line 110, in post_login
    await self.client(GetChannelsRequest([channel_id]))
  File "mautrix-telegram-bridge/lib/python3.7/site-packages/telethon/client/users.py", line 43, in __call__
    future = self._sender.send(request, ordered=ordered)
  File "mautrix-telegram-bridge/lib/python3.7/site-packages/telethon/network/mtprotosender.py", line 162, in send
    state = RequestState(request, self._loop)
  File "mautrix-telegram-bridge/lib/python3.7/site-packages/telethon/network/requeststate.py", line 17, in __init__
    self.data = bytes(request)
  File "mautrix-telegram-bridge/lib/python3.7/site-packages/telethon/tl/functions/channels.py", line 652, in __bytes__
    b'\x15\xc4\xb5\x1c',struct.pack('<i', len(self.id)),b''.join(bytes(x) for x in self.id),
  File "mautrix-telegram-bridge/lib/python3.7/site-packages/telethon/tl/functions/channels.py", line 652, in <genexpr>
    b'\x15\xc4\xb5\x1c',struct.pack('<i', len(self.id)),b''.join(bytes(x) for x in self.id),
  File "mautrix-telegram-bridge/lib/python3.7/site-packages/telethon/tl/types/__init__.py", line 6223, in __bytes__
    struct.pack('<i', self.channel_id),
struct.error: 'i' format requires -2147483648 <= number <= 2147483647
````
I've tried different telethon versions already, as i read about some compatibility issue somewhere in a similar sounding context, but this didn't solve anything.

Regards :)

**Comment by tulir** [comment]
check `SELECT tgid FROM portal WHERE tgid > 2147483647 OR tgid < -2147483648;`

**Comment by verymilan** [comment]
Thanks for your quick reply - i am not sure what the both entries before `|channel...` mean, so i rather don't just paste it here - it returned on entry, with a room that i am not able to join (no known servers) ...on my server.

**Comment by tulir** [comment]
You can either try removing the `-100` in front of the `tgid` or just remove the row altogether.

**Comment by verymilan** [comment]
Not sure if it is some valuable information, but the two numbers before `|channel...` are beginning with `105...` and are both equal.
If there is nothing else to worry about, i think i rather remove that row, thanks again.

**Comment by verymilan** [comment]
Oh... the error is actually still happening without that row.

**Comment by tulir** [comment]
Oh, check the same query but for the `bot_chats` table and `id` column

**Comment by verymilan** [comment]
Woo, now it seems to be gone 🎉
