### ISSUE TITLE
Update to .0.7.0 breaks SQL

### ISSUE THREAD

**Issue by vmario89** [tulir/mautrix-telegram#405]
Hi, i updated to newest release (from 0.7.0rc2 to 0.7.0)

that brought the following stack trace which im not able to solve
```
5293 tty:(none) cwd:/opt/matrix-bridges/mautrix-telegram filename:/opt/matrix-bridges/mautrix-telegram/mautrix-telegram.sh]: /opt/matrix-bridges/mautrix-telegram/mautrix-telegram.sh start
5293 tty:(none) cwd:/opt/matrix-bridges/mautrix-telegram filename:/usr/bin/basename]: basename /opt/matrix-bridges/mautrix-telegram
5293 tty:(none) cwd:/opt/matrix-bridges/mautrix-telegram filename:/opt/matrix-bridges/mautrix-telegram/bin/alembic]: alembic upgrade head
5293 tty:(none) cwd:/opt/matrix-bridges/mautrix-telegram filename:/sbin/ldconfig]: /sbin/ldconfig -p
5293 tty:(none) cwd:/opt/matrix-bridges/mautrix-telegram filename:/sbin/ldconfig.real]: /sbin/ldconfig.real -p
5293 tty:(none) cwd:/opt/matrix-bridges/mautrix-telegram filename:/sbin/ldconfig]: /sbin/ldconfig -p
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
5293 tty:(none) cwd:/opt/matrix-bridges/mautrix-telegram filename:/opt/matrix-bridges/mautrix-telegram/bin/python]: python -m mautrix_telegram
5293 tty:(none) cwd:/opt/matrix-bridges/mautrix-telegram filename:/sbin/ldconfig]: /sbin/ldconfig -p
5293 tty:(none) cwd:/opt/matrix-bridges/mautrix-telegram filename:/sbin/ldconfig.real]: /sbin/ldconfig.real -p
5293 tty:(none) cwd:/opt/matrix-bridges/mautrix-telegram filename:/sbin/ldconfig]: /sbin/ldconfig -p
5293 tty:(none) cwd:/opt/matrix-bridges/mautrix-telegram filename:/sbin/ldconfig.real]: /sbin/ldconfig.real -p
5293 tty:(none) cwd:/opt/matrix-bridges/mautrix-telegram filename:/bin/sh]: /bin/sh -c uname -p 2> /dev/null
5293 tty:(none) cwd:/opt/matrix-bridges/mautrix-telegram filename:/bin/uname]: uname -p
5293 tty:(none) cwd:/opt/matrix-bridges/mautrix-telegram filename:/opt/matrix-bridges/mautrix-telegram/bin/convert]: convert
5293 tty:(none) cwd:/opt/matrix-bridges/mautrix-telegram filename:/usr/local/sbin/convert]: convert
5293 tty:(none) cwd:/opt/matrix-bridges/mautrix-telegram filename:/usr/local/bin/convert]: convert
5293 tty:(none) cwd:/opt/matrix-bridges/mautrix-telegram filename:/usr/sbin/convert]: convert
5293 tty:(none) cwd:/opt/matrix-bridges/mautrix-telegram filename:/usr/bin/convert]: convert
[2019-12-28 12:12:49,155] [INFO@mau.mx] Ensuring connectivity to homeserver
[2019-12-28 12:12:49,529] [INFO@telethon.506726267.network.mtprotosender] Connecting to 149.154.167.51:443/TcpFull...
[2019-12-28 12:12:49,544] [INFO@telethon.506726267.network.mtprotosender] Connection to 149.154.167.51:443/TcpFull complete!
[2019-12-28 12:12:49,749] [ERROR@mau.user.@vmario89:matrix.fablabchemnitz.de] Failed to run post-login sync
Traceback (most recent call last):
  File "/opt/matrix-bridges/mautrix-telegram/lib/python3.7/site-packages/sqlalchemy/sql/sqltypes.py", line 1513, in _object_value_for_elem
    return self._object_lookup[elem]
KeyError: 'join'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/matrix-bridges/mautrix-telegram/lib/python3.7/site-packages/mautrix_telegram/user.py", line 219, in post_login
    await self.sync_dialogs()
  File "/opt/matrix-bridges/mautrix-telegram/lib/python3.7/site-packages/mautrix_telegram/user.py", line 357, in sync_dialogs
    await asyncio.gather(*creators, loop=self.loop)
  File "/opt/matrix-bridges/mautrix-telegram/lib/python3.7/site-packages/mautrix_telegram/portal/metadata.py", line 240, in create_matrix_room
    await self.invite_to_matrix(invites or [])
  File "/opt/matrix-bridges/mautrix-telegram/lib/python3.7/site-packages/mautrix_telegram/portal/metadata.py", line 188, in invite_to_matrix
    await self.main_intent.invite_user(self.mxid, user, check_cache=True)
  File "/opt/matrix-bridges/mautrix-telegram/lib/python3.7/site-packages/mautrix/appservice/api/intent.py", line 86, in wrapper
    await __self.ensure_joined(room_id)
  File "/opt/matrix-bridges/mautrix-telegram/lib/python3.7/site-packages/mautrix/appservice/api/intent.py", line 353, in ensure_joined
    if not ignore_cache and self.state_store.is_joined(room_id, self.mxid):
  File "/opt/matrix-bridges/mautrix-telegram/lib/python3.7/site-packages/mautrix/appservice/state_store/abstract.py", line 100, in is_joined
    return self.get_membership(room_id, user_id) == Membership.JOIN
  File "/opt/matrix-bridges/mautrix-telegram/lib/python3.7/site-packages/mautrix/appservice/state_store/abstract.py", line 97, in get_membership
    return self.get_member(room_id, user_id).membership or Membership.LEAVE
  File "/opt/matrix-bridges/mautrix-telegram/lib/python3.7/site-packages/mautrix/bridge/db/sqlstatestore.py", line 62, in get_member
    return self._get_user_profile(room_id, user_id).member()
  File "/opt/matrix-bridges/mautrix-telegram/lib/python3.7/site-packages/mautrix/bridge/db/sqlstatestore.py", line 48, in _get_user_profile
    profile = UserProfile.get(*key)
  File "/opt/matrix-bridges/mautrix-telegram/lib/python3.7/site-packages/mautrix/bridge/db/mx_user_profile.py", line 30, in get
    return cls._select_one_or_none(and_(cls.c.room_id == room_id, cls.c.user_id == user_id))
  File "/opt/matrix-bridges/mautrix-telegram/lib/python3.7/site-packages/mautrix/util/db/base.py", line 135, in _select_one_or_none
    return cls._one_or_none(cls.db.execute(cls._make_simple_select(*args)))
  File "/opt/matrix-bridges/mautrix-telegram/lib/python3.7/site-packages/mautrix/util/db/base.py", line 59, in _one_or_none
    return cls.scan(next(rows))
  File "/opt/matrix-bridges/mautrix-telegram/lib/python3.7/site-packages/mautrix/util/db/base.py", line 88, in scan
    return cls(**dict(zip(cls.column_names, row)))
  File "/opt/matrix-bridges/mautrix-telegram/lib/python3.7/site-packages/sqlalchemy/sql/sqltypes.py", line 1599, in process
    value = self._object_value_for_elem(value)
  File "/opt/matrix-bridges/mautrix-telegram/lib/python3.7/site-packages/sqlalchemy/sql/sqltypes.py", line 1516, in _object_value_for_elem
    '"%s" is not among the defined enum values' % elem
LookupError: "join" is not among the defined enum values
[2019-12-28 12:12:49,791] [ERROR@mau.portal.381745312] Fatal error updating Matrix room
Traceback (most recent call last):
  File "/opt/matrix-bridges/mautrix-telegram/lib/python3.7/site-packages/sqlalchemy/sql/sqltypes.py", line 1513, in _object_value_for_elem
    return self._object_lookup[elem]
KeyError: 'join'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/matrix-bridges/mautrix-telegram/lib/python3.7/site-packages/mautrix_telegram/portal/metadata.py", line 201, in update_matrix_room
    participants)
  File "/opt/matrix-bridges/mautrix-telegram/lib/python3.7/site-packages/mautrix_telegram/portal/metadata.py", line 214, in _update_matrix_room
    await self._sync_telegram_users(user, users)
  File "/opt/matrix-bridges/mautrix-telegram/lib/python3.7/site-packages/mautrix_telegram/portal/metadata.py", line 460, in _sync_telegram_users
    await puppet.intent_for(self).ensure_joined(self.mxid)
  File "/opt/matrix-bridges/mautrix-telegram/lib/python3.7/site-packages/mautrix/appservice/api/intent.py", line 353, in ensure_joined
    if not ignore_cache and self.state_store.is_joined(room_id, self.mxid):
  File "/opt/matrix-bridges/mautrix-telegram/lib/python3.7/site-packages/mautrix/appservice/state_store/abstract.py", line 100, in is_joined
    return self.get_membership(room_id, user_id) == Membership.JOIN
  File "/opt/matrix-bridges/mautrix-telegram/lib/python3.7/site-packages/mautrix/appservice/state_store/abstract.py", line 97, in get_membership
    return self.get_member(room_id, user_id).membership or Membership.LEAVE
  File "/opt/matrix-bridges/mautrix-telegram/lib/python3.7/site-packages/mautrix/bridge/db/sqlstatestore.py", line 62, in get_member
    return self._get_user_profile(room_id, user_id).member()
  File "/opt/matrix-bridges/mautrix-telegram/lib/python3.7/site-packages/mautrix/bridge/db/sqlstatestore.py", line 48, in _get_user_profile
    profile = UserProfile.get(*key)
  File "/opt/matrix-bridges/mautrix-telegram/lib/python3.7/site-packages/mautrix/bridge/db/mx_user_profile.py", line 30, in get
    return cls._select_one_or_none(and_(cls.c.room_id == room_id, cls.c.user_id == user_id))
  File "/opt/matrix-bridges/mautrix-telegram/lib/python3.7/site-packages/mautrix/util/db/base.py", line 135, in _select_one_or_none
    return cls._one_or_none(cls.db.execute(cls._make_simple_select(*args)))
  File "/opt/matrix-bridges/mautrix-telegram/lib/python3.7/site-packages/mautrix/util/db/base.py", line 59, in _one_or_none
    return cls.scan(next(rows))
  File "/opt/matrix-bridges/mautrix-telegram/lib/python3.7/site-packages/mautrix/util/db/base.py", line 88, in scan
    return cls(**dict(zip(cls.column_names, row)))
  File "/opt/matrix-bridges/mautrix-telegram/lib/python3.7/site-packages/sqlalchemy/sql/sqltypes.py", line 1599, in process
    value = self._object_value_for_elem(value)
  File "/opt/matrix-bridges/mautrix-telegram/lib/python3.7/site-packages/sqlalchemy/sql/sqltypes.py", line 1516, in _object_value_for_elem
    '"%s" is not among the defined enum values' % elem
LookupError: "join" is not among the defined enum values
[2019-12-28 12:12:49,795] [ERROR@mau.portal.391205546] Fatal error updating Matrix room
Traceback (most recent call last):
  File "/opt/matrix-bridges/mautrix-telegram/lib/python3.7/site-packages/sqlalchemy/sql/sqltypes.py", line 1513, in _object_value_for_elem
    return self._object_lookup[elem]
KeyError: 'join'
```

i already updated pip dependencies like SQLAlchemy to 1.3.12

reverting back to 0.7.0rc2 keeps this error now so bridge is dead :-(

has anyone some tip for me?

regards, Mario

**Comment by tulir** [comment]
All the membership values in the `mx_user_profile` table should be uppercase. No idea how that ended up there, especially if you had already upgraded to a 0.7.0 rc successfully.

**Comment by vmario89** [comment]
hmmmm :-/ is it possible to perform some sql statement to the sqlite easily?

**Comment by tulir** [comment]
Yeah you can just run https://github.com/tulir/mautrix-telegram/blob/master/alembic/versions/4f7d7ed5792a_switch_mx_user_profile_to_native_enum.py#L20 manually

**Comment by vmario89** [comment]
hi. i ran the script with pthon3.7 interpreter without any error but it did not change anything. i opened the database with DB Browser für SQLite and executed the statements inside db explorer.  

![grafik](https://user-images.githubusercontent.com/5631071/71544389-29608c00-297f-11ea-8e3b-4ac85c41aa66.png)

saved it back to the directory. now it works again. Thanks for your quick and precise help! :-)
