### ISSUE TITLE
The authorization key (session file) was used under two different IP addresses simultaneously

### ISSUE THREAD

**Issue by anoadragon453** [tulir/mautrix-telegram#408]
So I ran the bridge with the same credentials on two different servers accidentally and now get the following traceback and bridge crash whenever the bridge is started:

```
Traceback (most recent call last):
  File "/home/synapse/mautrix-telegram/env/lib/python3.6/site-packages/mautrix/bridge/commands/handler.py", line 359, in handle
    await self._run_handler(handler, evt)
  File "/home/synapse/mautrix-telegram/mautrix_telegram/commands/handler.py", line 130, in _run_handler
    return await handler(evt)
  File "/home/synapse/mautrix-telegram/env/lib/python3.6/site-packages/mautrix/bridge/commands/handler.py", line 253, in __call__
    return await self._handler(evt)
  File "/home/synapse/mautrix-telegram/mautrix_telegram/commands/telegram/auth.py", line 37, in ping
    me = await evt.sender.client.get_me() if await evt.sender.is_logged_in() else None
  File "/home/synapse/mautrix-telegram/env/lib/python3.6/site-packages/telethon/client/users.py", line 139, in get_me
    functions.users.GetUsersRequest([types.InputUserSelf()])))[0]
  File "/home/synapse/mautrix-telegram/env/lib/python3.6/site-packages/telethon/client/users.py", line 74, in __call__
    result = await future
telethon.errors.rpcerrorlist.AuthKeyDuplicatedError: The authorization key (session file) was used under two different IP addresses simultaneously, and can no longer be used. Use the same session exclusively, or use different sessions (caused by GetUsersRequest)
```

and I can't logout since the bridge keeps crashing after restart :) Is there a safe way to clear the credentials by editing the db?

(Also the bridge should probably handle this error case and log the user out)

**Comment by anoadragon453** [comment]
I ended up reinstalling (but still have the old folder and db lying around if you want to try and find a workable solution to this).

**Comment by tulir** [comment]
Moved to #543
