### ISSUE TITLE
telethon.errors.rpcerrorlist.PeerIdInvalidError: An invalid Peer was used. Make sure to pass the right peer type (caused by ExportChatInviteRequest)

### ISSUE THREAD

**Issue by vranki** [tulir/mautrix-telegram#426]
I have a old room bridged to Telegram. There are TG ghosts in the room, but not sure if the bridge actually works.

!tg invite-link causes Unhandled error:

```
helmi 17 21:13:37 morpheus python[1406]: [2020-02-17 21:13:37,872] [ERROR@mau.commands] Unhandled error while handling command invite-link  from @xxx:yyyyy.fi (ref: 12345678)
helmi 17 21:13:37 morpheus python[1406]: Traceback (most recent call last):
helmi 17 21:13:37 morpheus python[1406]:   File "/opt/telegrambot/lib/python3.7/site-packages/mautrix/bridge/commands/handler.py", line 359, in handle
helmi 17 21:13:37 morpheus python[1406]:     await self._run_handler(handler, evt)
helmi 17 21:13:37 morpheus python[1406]:   File "/opt/telegrambot/lib/python3.7/site-packages/mautrix_telegram/commands/handler.py", line 130, in _run_handler
helmi 17 21:13:37 morpheus python[1406]:     return await handler(evt)
helmi 17 21:13:37 morpheus python[1406]:   File "/opt/telegrambot/lib/python3.7/site-packages/mautrix/bridge/commands/handler.py", line 253, in __call__
helmi 17 21:13:37 morpheus python[1406]:     return await self._handler(evt)
helmi 17 21:13:37 morpheus python[1406]:   File "/opt/telegrambot/lib/python3.7/site-packages/mautrix_telegram/commands/portal/misc.py", line 94, in invite_link
helmi 17 21:13:37 morpheus python[1406]:     link = await portal.get_invite_link(evt.sender)
helmi 17 21:13:37 morpheus python[1406]:   File "/opt/telegrambot/lib/python3.7/site-packages/mautrix_telegram/portal/base.py", line 251, in get_invite_link
helmi 17 21:13:37 morpheus python[1406]:     link = await user.client(ExportChatInviteRequest(peer=await self.get_input_entity(user)))
helmi 17 21:13:37 morpheus python[1406]:   File "/opt/telegrambot/lib/python3.7/site-packages/telethon/client/users.py", line 74, in __call__
helmi 17 21:13:37 morpheus python[1406]:     result = await future
helmi 17 21:13:37 morpheus python[1406]: telethon.errors.rpcerrorlist.PeerIdInvalidError: An invalid Peer was used. Make sure to pass the right peer type (caused by ExportChatInviteRequest)
```

!tg upgrade also fails - bot replies with Unhandled error while handling command. Check logs for more details (ref: 123456788).

**Comment by tionis** [comment]
I can second this issue. In my setup it now always occurs on startup.

**Comment by felixx9** [comment]
see #793
