### ISSUE TITLE
Bridge failed to create private group chat room for puppet

### ISSUE THREAD

**Issue by Half-Shot** [tulir/mautrix-telegram#430]
```
[2020-02-20 09:26:26,714] [DEBUG@mau.user.@Half-Shot:half-shot.uk] Unhandled update: UpdateReadChannelInbox(channel_id=1102658012, max_id=68991, still_unread_count=0, pts=70596, folder_id=None)
[2020-02-20 09:26:50,102] [DEBUG@telethon.383627852.network.mtprotosender] Handling update UpdateShort
[2020-02-20 09:26:50,103] [DEBUG@telethon.383627852.network.mtprotosender] Receiving items from the network...
[2020-02-20 09:26:55,220] [DEBUG@telethon.383627852.network.mtprotosender] Handling update UpdateShort
[2020-02-20 09:26:55,220] [DEBUG@telethon.383627852.network.mtprotosender] Receiving items from the network...
[2020-02-20 09:27:01,071] [DEBUG@telethon.383627852.network.mtprotosender] Handling update UpdateShortChatMessage
[2020-02-20 09:27:01,071] [DEBUG@telethon.383627852.network.mtprotosender] Receiving items from the network...
[2020-02-20 09:27:01,072] [ERROR@mau.portal.328330156] Fatal error creating Matrix room
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mautrix_telegram/portal/metadata.py", line 244, in create_matrix_room
    return await self._create_matrix_room(user, entity, invites)
  File "/usr/lib/python3.8/site-packages/mautrix_telegram/portal/metadata.py", line 259, in _create_matrix_room
    entity = await self.get_entity(user)
  File "/usr/lib/python3.8/site-packages/mautrix_telegram/portal/base.py", line 233, in get_entity
    return await user.client.get_entity(self.peer)
  File "/usr/lib/python3.8/site-packages/telethon/client/users.py", line 283, in get_entity
    chats = (await self(
  File "/usr/lib/python3.8/site-packages/telethon/client/users.py", line 53, in __call__
    future = self._sender.send(request, ordered=ordered)
  File "/usr/lib/python3.8/site-packages/telethon/network/mtprotosender.py", line 172, in send
    state = RequestState(request, self._loop)
  File "/usr/lib/python3.8/site-packages/telethon/network/requeststate.py", line 17, in __init__
    self.data = bytes(request)
  File "/usr/lib/python3.8/site-packages/telethon/tl/functions/messages.py", line 1141, in __bytes__
    b'\x15\xc4\xb5\x1c',struct.pack('<i', len(self.id)),b''.join(struct.pack('<i', x) for x in self.id),
  File "/usr/lib/python3.8/site-packages/telethon/tl/functions/messages.py", line 1141, in <genexpr>
    b'\x15\xc4\xb5\x1c',struct.pack('<i', len(self.id)),b''.join(struct.pack('<i', x) for x in self.id),
struct.error: required argument is not an integer
[2020-02-20 09:27:01,073] [DEBUG@mau.portal.328330156] Sending Could at least provide covered outdoor seating to None by @tg_137665402:half-shot.uk
[2020-02-20 09:27:01,074] [ERROR@mau.user.@Half-Shot:half-shot.uk] Failed to handle Telegram update UpdateShortChatMessage(id=186935, from_id=137665402, chat_id=328330156, message='Could at least provide covered outdoor seating', pts=360889, pts_count=1, date=datetime.datetime(2020, 2, 20, 9, 27, 1, tzinfo=datetime.timezone.utc), out=False, mentioned=False, media_unread=False, silent=False, fwd_from=None, via_bot_id=None, reply_to_msg_id=None, entities=[])
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mautrix_telegram/abstract_user.py", line 194, in _update_catch
    await self._update(update)
  File "/usr/lib/python3.8/site-packages/mautrix_telegram/abstract_user.py", line 241, in _update
    await self.update_message(update)
  File "/usr/lib/python3.8/site-packages/mautrix_telegram/abstract_user.py", line 440, in update_message
    return await portal.handle_telegram_message(self, sender, update)
  File "/usr/lib/python3.8/site-packages/mautrix_telegram/portal/telegram.py", line 408, in handle_telegram_message
    event_id = await self.handle_telegram_text(source, intent, is_bot, evt)
  File "/usr/lib/python3.8/site-packages/mautrix_telegram/portal/telegram.py", line 226, in handle_telegram_text
    await intent.set_typing(self.mxid, is_typing=False)
  File "/usr/lib/python3.8/site-packages/mautrix/appservice/api/intent.py", line 250, in set_typing
    await self.ensure_joined(room_id)
  File "/usr/lib/python3.8/site-packages/mautrix/appservice/api/intent.py", line 352, in ensure_joined
    raise ValueError("Room ID not given")
ValueError: Room ID not given
```

**Comment by Half-Shot** [comment]
Restarting fixed it, soooooo :man_shrugging:

**Comment by tulir** [comment]
LonamiWebs/Telethon@1e94fe25fa399d196f004a26fc4fb3b82dba9bfd added more logging for this. Closing for now until someone reproduces it with the new logging.

**Comment by TheJonny** [comment]
Hi, i am having the same issue - is the version with more logging released in pip?

**Comment by TheJonny** [comment]
> [LonamiWebs/Telethon@1e94fe2](https://github.com/LonamiWebs/Telethon/commit/1e94fe25fa399d196f004a26fc4fb3b82dba9bfd) added more logging for this. Closing for now until someone reproduces it with the new logging.

this is not used, as long as setup.py wants telethon<1.11

i forced the installation and will wait for more log.

and yes, if the bridge is restarted, all missing invites come through, but then, the problem reappears.
