### ISSUE TITLE
TypeError: 'async for' requires an object when integration manager hits /provisioner/chats

### ISSUE THREAD

**Issue by halkeye** [tulir/mautrix-telegram#448]
I'll take a look deeper at the code later, I don't know anything about async python though.

```
[2020-04-06 06:25:52,059] [ERROR@aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/lib/python3.8/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/lib/python3.8/site-packages/mautrix_telegram/web/provisioning/__init__.py", line 371, in middleware_handler
    return await handler(request)
  File "/usr/lib/python3.8/site-packages/mautrix_telegram/web/provisioning/__init__.py", line 317, in get_chats
    return web.json_response([{
TypeError: 'async for' requires an object with __aiter__ method, got coroutine
[2020-04-06 06:25:52,060] [INFO@aiohttp.access] 10.244.0.159 [06/Apr/2020:06:25:52 +0000] "GET /_matrix/provision/v1/user/@halkeye:g4v.dev/chats?user_id=@halkeye:g4v.dev HTTP/1.1" 500 244 "-" "-"
```

**Comment by halkeye** [comment]
OH! Just updated to latest master, seems to be fixed now.

**Comment by halkeye** [comment]
Ah, nope, same stacktrace, needed to refresh the integration manager.

**Comment by halkeye** [comment]
Wow your fast, got another one for you.
