### ISSUE TITLE
Cannot cast Dialog to any kind of int.

### ISSUE THREAD

**Issue by halkeye** [tulir/mautrix-telegram#450]
```
mautrix-telegram-6454f7c896-6fgbc mautrix-telegram [2020-04-06 07:12:03,392] [ERROR@aiohttp.server] Error handling request
mautrix-telegram-6454f7c896-6fgbc mautrix-telegram Traceback (most recent call last):
mautrix-telegram-6454f7c896-6fgbc mautrix-telegram   File "/usr/lib/python3.8/site-packages/telethon/utils.py", line 910, in get_peer_id
mautrix-telegram-6454f7c896-6fgbc mautrix-telegram     peer = get_peer(peer)
mautrix-telegram-6454f7c896-6fgbc mautrix-telegram   File "/usr/lib/python3.8/site-packages/telethon/utils.py", line 883, in get_peer
mautrix-telegram-6454f7c896-6fgbc mautrix-telegram     _raise_cast_fail(peer, 'Peer')
mautrix-telegram-6454f7c896-6fgbc mautrix-telegram   File "/usr/lib/python3.8/site-packages/telethon/utils.py", line 136, in _raise_cast_fail
mautrix-telegram-6454f7c896-6fgbc mautrix-telegram     raise TypeError('Cannot cast {} to any kind of {}.'.format(
mautrix-telegram-6454f7c896-6fgbc mautrix-telegram TypeError: Cannot cast Dialog to any kind of Peer.
mautrix-telegram-6454f7c896-6fgbc mautrix-telegram
mautrix-telegram-6454f7c896-6fgbc mautrix-telegram During handling of the above exception, another exception occurred:
mautrix-telegram-6454f7c896-6fgbc mautrix-telegram
mautrix-telegram-6454f7c896-6fgbc mautrix-telegram Traceback (most recent call last):
mautrix-telegram-6454f7c896-6fgbc mautrix-telegram   File "/usr/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 418, in start
mautrix-telegram-6454f7c896-6fgbc mautrix-telegram     resp = await task
mautrix-telegram-6454f7c896-6fgbc mautrix-telegram   File "/usr/lib/python3.8/site-packages/aiohttp/web_app.py", line 458, in _handle
mautrix-telegram-6454f7c896-6fgbc mautrix-telegram     resp = await handler(request)
mautrix-telegram-6454f7c896-6fgbc mautrix-telegram   File "/usr/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
mautrix-telegram-6454f7c896-6fgbc mautrix-telegram     return await handler(request)
mautrix-telegram-6454f7c896-6fgbc mautrix-telegram   File "/usr/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
mautrix-telegram-6454f7c896-6fgbc mautrix-telegram     return await handler(request)
mautrix-telegram-6454f7c896-6fgbc mautrix-telegram   File "/opt/mautrix-telegram/mautrix_telegram/web/provisioning/__init__.py", line 371, in middleware_handler
mautrix-telegram-6454f7c896-6fgbc mautrix-telegram     return await handler(request)
mautrix-telegram-6454f7c896-6fgbc mautrix-telegram   File "/opt/mautrix-telegram/mautrix_telegram/web/provisioning/__init__.py", line 317, in get_chats
mautrix-telegram-6454f7c896-6fgbc mautrix-telegram     return web.json_response([{
mautrix-telegram-6454f7c896-6fgbc mautrix-telegram   File "/opt/mautrix-telegram/mautrix_telegram/web/provisioning/__init__.py", line 318, in <listcomp>
mautrix-telegram-6454f7c896-6fgbc mautrix-telegram     "id": get_peer_id(chat),
mautrix-telegram-6454f7c896-6fgbc mautrix-telegram   File "/usr/lib/python3.8/site-packages/telethon/utils.py", line 912, in get_peer_id
mautrix-telegram-6454f7c896-6fgbc mautrix-telegram     _raise_cast_fail(peer, 'int')
mautrix-telegram-6454f7c896-6fgbc mautrix-telegram   File "/usr/lib/python3.8/site-packages/telethon/utils.py", line 136, in _raise_cast_fail
mautrix-telegram-6454f7c896-6fgbc mautrix-telegram     raise TypeError('Cannot cast {} to any kind of {}.'.format(
mautrix-telegram-6454f7c896-6fgbc mautrix-telegram TypeError: Cannot cast Dialog to any kind of int.
mautrix-telegram-6454f7c896-6fgbc mautrix-telegram [2020-04-06 07:12:03,394] [INFO@aiohttp.access] 10.244.0.159 [06/Apr/2020:07:12:03 +0000] "GET /_matrix/provision/v1/user/@halkeye:g4v.dev/chats?user_id=@halkeye:g4v.dev HTTP/1.1" 500 244 "-" "-"```

**Comment by halkeye** [comment]
pulled master right after #448

**Comment by halkeye** [comment]
Awesome, seems to work now thanks
