### ISSUE TITLE
Service fails to connect to synapse

### ISSUE THREAD

**Issue by jdemel** [tulir/mautrix-telegram#479]
I try to set up mautrix telegram to talk to my Matrix Synapse homeserver. 
I followed the [Docker setup manual](https://github.com/tulir/mautrix-telegram/wiki/Bridge-setup-with-Docker) to achieve this. Unfortunately, my container is unable to connect to my homeserver on the same machine.
This is my container log:
```
[2020-06-06 17:12:23,536] [INFO@mau.init] Initializing mautrix-telegram 0.8.0+dev.72a45d7d,
[2020-06-06 17:12:23,613] [INFO@mau.init] Initialization complete in 0.65 seconds,
[2020-06-06 17:12:23,613] [DEBUG@mau.init] Running startup actions...,
[2020-06-06 17:12:23,614] [DEBUG@mau.init] Starting appservice...,
[2020-06-06 17:12:23,614] [DEBUG@mau.as] Starting appservice web server on 0.0.0.0:29317,
[2020-06-06 17:12:23,616] [INFO@mau.mx] Ensuring connectivity to homeserver,
[2020-06-06 17:12:23,725] [CRITICAL@mau.init] Unexpected error in main event loop,
Traceback (most recent call last):,
  File "/usr/lib/python3.8/site-packages/mautrix/util/program.py", line 170, in _run,
    self.loop.run_until_complete(self.start()),
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete,
    return future.result(),
  File "/usr/lib/python3.8/site-packages/mautrix/bridge/bridge.py", line 125, in start,
    await self.matrix.wait_for_connection(),
  File "/usr/lib/python3.8/site-packages/mautrix/bridge/matrix.py", line 74, in wait_for_connection,
    await self.az.intent.whoami(),
  File "/usr/lib/python3.8/site-packages/mautrix/client/api/authentication.py", line 32, in whoami,
    resp = await self.api.request(Method.GET, Path.account.whoami),
  File "/usr/lib/python3.8/site-packages/mautrix/api/http.py", line 203, in request,
    return await self._send(method, endpoint, content, query_params, headers or {}),
  File "/usr/lib/python3.8/site-packages/mautrix/api/http.py", line 143, in _send,
    raise make_request_error(http_status=response.status,,
mautrix.errors.request.MForbidden: Application service has not registered this user,
```
And this is what I see in my homeserver log:
```
2020-06-06 19:12:23,723 - synapse.access.http.8008 - 311 - INFO - GET-775 - 172.17.0.4 - 8008 - {None} Processed request: 0.005sec/0.000sec (0.003sec, 0.000sec) (0.000sec/0.000sec/0) 84B 403 "GET /_matrix/client/r0/account/whoami?user_id=@telegrambot:my.domain HTTP/1.0" "Python/3.8 aiohttp/3.6.2" [0 dbevts]
```

It looks like there is something wrong with registration. I redid the manual several times and still, I run into the same issue again. What's wrong here? What have I missed?

Do you need any further info on that issue? Is there a proper way to debug this issue? e.g. How do I figure out if Synapse fails to properly set up my service?

**Comment by wvffle** [comment]
The same just happened for me

**Comment by jdemel** [comment]
@tulir Thanks for taking care of this so quickly!
Is the Docker image already updated too?
