### ISSUE TITLE
Bot can't start and crashes when trying to connect to puppet

### ISSUE THREAD

**Issue by JuniorJPDJ** [tulir/mautrix-telegram#485]
Bot started crashing and restarting itself after updating synapse to v1.15.1.
I didn't change anything other ;/
I updated bots yesterday after your commits and it was working ok, so it's not change in your code (?!).
mautrix-facebook keeps working good

```
mautrix-telegram_1  | INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
mautrix-telegram_1  | INFO  [alembic.runtime.migration] Will assume transactional DDL.
mautrix-telegram_1  | [2020-06-16 12:14:40,601] [INFO@mau.init] Initializing mautrix-telegram 0.8.1+dev.59d76148
mautrix-telegram_1  | [2020-06-16 12:14:40,652] [INFO@mau.init] Initialization complete in 0.3 seconds
mautrix-telegram_1  | [2020-06-16 12:14:40,653] [INFO@mau.mx] Ensuring connectivity to homeserver
mautrix-telegram_1  | [2020-06-16 12:14:40,685] [ERROR@mau.mx] Connection to homeserver failed, retrying in 10 seconds
mautrix-telegram_1  | Traceback (most recent call last):
mautrix-telegram_1  |   File "/usr/lib/python3.8/site-packages/mautrix/bridge/matrix.py", line 75, in wait_for_connection
mautrix-telegram_1  |     await self.az.intent.whoami()
mautrix-telegram_1  |   File "/usr/lib/python3.8/site-packages/mautrix/client/api/authentication.py", line 32, in whoami
mautrix-telegram_1  |     resp = await self.api.request(Method.GET, Path.account.whoami)
mautrix-telegram_1  |   File "/usr/lib/python3.8/site-packages/mautrix/api/http.py", line 203, in request
mautrix-telegram_1  |     return await self._send(method, endpoint, content, query_params, headers or {})
mautrix-telegram_1  |   File "/usr/lib/python3.8/site-packages/mautrix/api/http.py", line 143, in _send
mautrix-telegram_1  |     raise make_request_error(http_status=response.status,
mautrix-telegram_1  | mautrix.errors.request.MMissingToken: Missing access token
mautrix-telegram_1  | [2020-06-16 12:14:50,706] [ERROR@mau.mx] Connection to homeserver failed, retrying in 10 seconds
mautrix-telegram_1  | Traceback (most recent call last):
mautrix-telegram_1  |   File "/usr/lib/python3.8/site-packages/mautrix/bridge/matrix.py", line 75, in wait_for_connection
mautrix-telegram_1  |     await self.az.intent.whoami()
mautrix-telegram_1  |   File "/usr/lib/python3.8/site-packages/mautrix/client/api/authentication.py", line 32, in whoami
mautrix-telegram_1  |     resp = await self.api.request(Method.GET, Path.account.whoami)
mautrix-telegram_1  |   File "/usr/lib/python3.8/site-packages/mautrix/api/http.py", line 203, in request
mautrix-telegram_1  |     return await self._send(method, endpoint, content, query_params, headers or {})
mautrix-telegram_1  |   File "/usr/lib/python3.8/site-packages/mautrix/api/http.py", line 143, in _send
mautrix-telegram_1  |     raise make_request_error(http_status=response.status,
mautrix-telegram_1  | mautrix.errors.request.MMissingToken: Missing access token
mautrix-telegram_1  | [2020-06-16 12:15:00,719] [ERROR@mau.mx] Connection to homeserver failed, retrying in 10 seconds
mautrix-telegram_1  | Traceback (most recent call last):
mautrix-telegram_1  |   File "/usr/lib/python3.8/site-packages/mautrix/bridge/matrix.py", line 75, in wait_for_connection
mautrix-telegram_1  |     await self.az.intent.whoami()
mautrix-telegram_1  |   File "/usr/lib/python3.8/site-packages/mautrix/client/api/authentication.py", line 32, in whoami
mautrix-telegram_1  |     resp = await self.api.request(Method.GET, Path.account.whoami)
mautrix-telegram_1  |   File "/usr/lib/python3.8/site-packages/mautrix/api/http.py", line 203, in request
mautrix-telegram_1  |     return await self._send(method, endpoint, content, query_params, headers or {})
mautrix-telegram_1  |   File "/usr/lib/python3.8/site-packages/mautrix/api/http.py", line 143, in _send
mautrix-telegram_1  |     raise make_request_error(http_status=response.status,
mautrix-telegram_1  | mautrix.errors.request.MMissingToken: Missing access token
mautrix-telegram_1  | [2020-06-16 12:15:10,736] [ERROR@mau.mx] Connection to homeserver failed, retrying in 10 seconds
mautrix-telegram_1  | Traceback (most recent call last):
mautrix-telegram_1  |   File "/usr/lib/python3.8/site-packages/mautrix/bridge/matrix.py", line 75, in wait_for_connection
mautrix-telegram_1  |     await self.az.intent.whoami()
mautrix-telegram_1  |   File "/usr/lib/python3.8/site-packages/mautrix/client/api/authentication.py", line 32, in whoami
mautrix-telegram_1  |     resp = await self.api.request(Method.GET, Path.account.whoami)
mautrix-telegram_1  |   File "/usr/lib/python3.8/site-packages/mautrix/api/http.py", line 203, in request
mautrix-telegram_1  |     return await self._send(method, endpoint, content, query_params, headers or {})
mautrix-telegram_1  |   File "/usr/lib/python3.8/site-packages/mautrix/api/http.py", line 143, in _send
mautrix-telegram_1  |     raise make_request_error(http_status=response.status,
mautrix-telegram_1  | mautrix.errors.request.MMissingToken: Missing access token
mautrix-telegram_1  | [2020-06-16 12:15:20,756] [ERROR@mau.mx] Connection to homeserver failed, retrying in 10 seconds
mautrix-telegram_1  | Traceback (most recent call last):
mautrix-telegram_1  |   File "/usr/lib/python3.8/site-packages/mautrix/bridge/matrix.py", line 75, in wait_for_connection
mautrix-telegram_1  |     await self.az.intent.whoami()
mautrix-telegram_1  |   File "/usr/lib/python3.8/site-packages/mautrix/client/api/authentication.py", line 32, in whoami
mautrix-telegram_1  |     resp = await self.api.request(Method.GET, Path.account.whoami)
mautrix-telegram_1  |   File "/usr/lib/python3.8/site-packages/mautrix/api/http.py", line 203, in request
mautrix-telegram_1  |     return await self._send(method, endpoint, content, query_params, headers or {})
mautrix-telegram_1  |   File "/usr/lib/python3.8/site-packages/mautrix/api/http.py", line 143, in _send
mautrix-telegram_1  |     raise make_request_error(http_status=response.status,
mautrix-telegram_1  | mautrix.errors.request.MMissingToken: Missing access token
mautrix-telegram_1  | [2020-06-16 12:15:30,923] [ERROR@mau.mx] Connection to homeserver failed, retrying in 10 seconds
mautrix-telegram_1  | Traceback (most recent call last):
mautrix-telegram_1  |   File "/usr/lib/python3.8/site-packages/mautrix/bridge/matrix.py", line 75, in wait_for_connection
mautrix-telegram_1  |     await self.az.intent.whoami()
mautrix-telegram_1  |   File "/usr/lib/python3.8/site-packages/mautrix/client/api/authentication.py", line 32, in whoami
mautrix-telegram_1  |     resp = await self.api.request(Method.GET, Path.account.whoami)
mautrix-telegram_1  |   File "/usr/lib/python3.8/site-packages/mautrix/api/http.py", line 203, in request
mautrix-telegram_1  |     return await self._send(method, endpoint, content, query_params, headers or {})
mautrix-telegram_1  |   File "/usr/lib/python3.8/site-packages/mautrix/api/http.py", line 143, in _send
mautrix-telegram_1  |     raise make_request_error(http_status=response.status,
mautrix-telegram_1  | mautrix.errors.request.MMissingToken: Missing access token
mautrix-telegram_1  | [2020-06-16 12:15:40,945] [CRITICAL@mau.init] Unexpected error in main event loop
mautrix-telegram_1  | Traceback (most recent call last):
mautrix-telegram_1  |   File "/usr/lib/python3.8/site-packages/mautrix/util/program.py", line 170, in _run
mautrix-telegram_1  |     self.loop.run_until_complete(self.start())
mautrix-telegram_1  |   File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
mautrix-telegram_1  |     return future.result()
mautrix-telegram_1  |   File "/usr/lib/python3.8/site-packages/mautrix/bridge/bridge.py", line 125, in start
mautrix-telegram_1  |     await self.matrix.wait_for_connection()
mautrix-telegram_1  |   File "/usr/lib/python3.8/site-packages/mautrix/bridge/matrix.py", line 75, in wait_for_connection
mautrix-telegram_1  |     await self.az.intent.whoami()
mautrix-telegram_1  |   File "/usr/lib/python3.8/site-packages/mautrix/client/api/authentication.py", line 32, in whoami
mautrix-telegram_1  |     resp = await self.api.request(Method.GET, Path.account.whoami)
mautrix-telegram_1  |   File "/usr/lib/python3.8/site-packages/mautrix/api/http.py", line 203, in request
mautrix-telegram_1  |     return await self._send(method, endpoint, content, query_params, headers or {})
mautrix-telegram_1  |   File "/usr/lib/python3.8/site-packages/mautrix/api/http.py", line 143, in _send
mautrix-telegram_1  |     raise make_request_error(http_status=response.status,
mautrix-telegram_1  | mautrix.errors.request.MMissingToken: Missing access token
```

**Comment by JuniorJPDJ** [comment]
Oh, I changed address and forgot s after http..
Sorry for issue
