### ISSUE TITLE
Can send from Telegram to Matrix but not vice versa

### ISSUE THREAD

**Issue by Mebus** [tulir/mautrix-telegram#490]
Hallo,

 * I bridget a Telegram group chat and a Matrix room. Unfortunately now I can send from Telegram to Matrix, but not from Matrix to Telegram.

 * Also the !tg command is just ignored.

Why is that happening?

Mebus

**Comment by Mebus** [comment]
This seems to be a problem with the encryption. Unecrypted channels work, but encrypted ones don't.

```
mautrix-telegram    | [2020-06-29 15:36:39,849] [ERROR@mau.as] Exception in Matrix event handler
mautrix-telegram    | Traceback (most recent call last):
mautrix-telegram    |   File "/usr/lib/python3.8/site-packages/mautrix/appservice/as_handler.py", line 147, in try_handle
mautrix-telegram    |     await handler_func(event)
mautrix-telegram    |   File "/usr/lib/python3.8/site-packages/mautrix/bridge/matrix.py", line 380, in int_handle_event
mautrix-telegram    |     await self.handle_encrypted(evt)
mautrix-telegram    |   File "/usr/lib/python3.8/site-packages/mautrix/bridge/matrix.py", line 314, in handle_encrypted
mautrix-telegram    |     await self.int_handle_event(self.e2ee.decrypt(evt))
mautrix-telegram    |   File "/usr/lib/python3.8/site-packages/mautrix/bridge/e2ee.py", line 138, in decrypt
mautrix-telegram    |     event = self.client.decrypt_event(NioEvent.parse_encrypted_event(serialized))
mautrix-telegram    |   File "/usr/lib/python3.8/site-packages/nio/client/base_client.py", line 116, in inner
mautrix-telegram    |     return fn(self, *args, **kwargs)
mautrix-telegram    |   File "/usr/lib/python3.8/site-packages/nio/client/base_client.py", line 608, in decrypt_event
mautrix-telegram    |     return self.olm.decrypt_megolm_event(event)
mautrix-telegram    |   File "/usr/lib/python3.8/site-packages/nio/crypto/olm_machine.py", line 1528, in decrypt_megolm_event
mautrix-telegram    |     raise EncryptionError(message)
mautrix-telegram    | nio.exceptions.EncryptionError: Error decrypting megolm event, no session found with session id fjwEAZb3mnAFZlP+0SElEtgaO4ps+qP0EcVEl7DuSvQ for room !RMmUYbdbVJYAPOoEaz:matrix.XXXXX.com```

Mebus

**Comment by tulir** [comment]
Assuming this was the same as #478
