### ISSUE TITLE
deleting messages from matrix-side (for logged in user) is broken in 0.8.1

### ISSUE THREAD

**Issue by bendschs** [tulir/mautrix-telegram#498]
When i try to delete messages in a telegram-room from matrix-side the following error message comes up in the logs, the message appears to be deleted in matrix room, but the deletion is not bridged to the actual telegram chat. this happens when i am logged in as my telegram user. everything else is being bridged from both sides, so double puppeting works just fine except for delete from matrix side.  

```
Traceback (most recent call last):
  File "/opt/synapse/lib/python3.7/site-packages/mautrix/appservice/as_handler.py", line 147, in try_handle
    await handler_func(event)
  File "/opt/synapse/lib/python3.7/site-packages/mautrix/bridge/matrix.py", line 335, in int_handle_event
    if self.filter_matrix_event(evt):
  File "/opt/synapse/lib/python3.7/site-packages/mautrix_telegram/matrix.py", line 395, in filter_matrix_event
    if evt.content.get("net.maunium.telegram.puppet", False):
AttributeError: '_Nothing' object has no attribute 'get'
[2020-07-19 00:53:20,929] [INFO@aiohttp.access] 127.0.0.1 [18/Jul/2020:22:53:20 +0000] "PUT /transactions/71100?access_token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  HTTP/1.1" 200 158 "-" "Synapse/1.17.0"
``` 
(access token was replaced for privacy reasons)

**Comment by tulir** [comment]
Fixed in mautrix-python v0.5.8 and v0.6.0
