### ISSUE TITLE
DBMS migration as described on the wiki fails with missing module

### ISSUE THREAD

**Issue by Omar007** [tulir/mautrix-telegram#500]
Migrating the DBMS as described on https://github.com/tulir/mautrix-telegram/wiki/Database-management-system-migration fails due to missing referenced modules.

Command used:
```
python3 -m mautrix_telegram.scripts.dbms_migrate -f sqlite:////data/database.db -t postgres://user:pass@host/db
```
Result:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.8/site-packages/mautrix_telegram/scripts/dbms_migrate/__main__.py", line 63, in <module>
    session, tables = connect(args.from_url)
  File "/usr/lib/python3.8/site-packages/mautrix_telegram/scripts/dbms_migrate/__main__.py", line 28, in connect
    from mautrix.bridge.db import RoomState, UserProfile
ModuleNotFoundError: No module named 'mautrix.bridge.db'
```

This is at least happening when using the Docker image to perform the operation, have not verified with manual installations but it doesn't show on https://mautrix.readthedocs.io/en/latest/py-modindex.html as a valid/existing module (nor on the source repo) so I highly doubt there would be a change.

**Comment by SharkyRawr** [comment]
I made a PR to fix this: https://github.com/tulir/mautrix-telegram/pull/503
