### ISSUE TITLE
MatrixUnknownRequestError: 404 - No Such Resource

### ISSUE THREAD

**Issue by SharkyRawr** [tulir/mautrix-telegram#501]
```
[2020-07-22 15:33:09,580] [INFO@telethon.2540353008715562232.client.downloads] Starting direct file download in chunks of 65536 at 0, stride 65536
[2020-07-22 15:33:09,630] [INFO@telethon.2540353008715562232.client.downloads] File lives in another DC
[2020-07-22 15:33:10,202] [ERROR@mau.puppet.1028850182] Failed to update info from source 1070511267
Traceback (most recent call last):
  File "/home/matrix/telegram-bridge/venv/lib/python3.8/site-packages/mautrix_telegram/puppet.py", line 245, in update_info
    changed = await self.update_avatar(source, info.photo) or changed
  File "/home/matrix/telegram-bridge/venv/lib/python3.8/site-packages/mautrix_telegram/puppet.py", line 321, in update_avatar
    file = await util.transfer_file_to_matrix(source.client, self.default_mxid_intent, loc)
  File "/home/matrix/telegram-bridge/venv/lib/python3.8/site-packages/mautrix_telegram/util/file_transfer.py", line 182, in transfer_file_to_matrix
    return await _unlocked_transfer_file_to_matrix(client, intent, location_id, location,
  File "/home/matrix/telegram-bridge/venv/lib/python3.8/site-packages/mautrix_telegram/util/file_transfer.py", line 238, in _unlocked_transfer_file_to_matrix
    content_uri = await intent.upload_media(file, upload_mime_type)
  File "/home/matrix/telegram-bridge/venv/lib/python3.8/site-packages/mautrix/appservice/api/intent.py", line 79, in wrapper
    return await __method(*args, **kwargs)
  File "/home/matrix/telegram-bridge/venv/lib/python3.8/site-packages/mautrix/client/api/modules/media_repository.py", line 58, in upload_media
    resp = await self.api.request(Method.POST, MediaPath.upload, content=data,
  File "/home/matrix/telegram-bridge/venv/lib/python3.8/site-packages/mautrix/api.py", line 205, in request
    return await self._send(method, endpoint, content, query_params, headers or {})
  File "/home/matrix/telegram-bridge/venv/lib/python3.8/site-packages/mautrix/api.py", line 144, in _send
    raise make_request_error(http_status=response.status,
mautrix.errors.request.MatrixUnknownRequestError: 404:
<html>
  <head><title>404 - No Such Resource</title></head>
  <body>
    <h1>No Such Resource</h1>
    <p>Sorry. No luck finding that resource.</p>
  </body>
</html>

[2020-07-22 15:33:10,206] [INFO@telethon.2540353008715562232.client.downloads] Starting direct file download in chunks of 65536 at 0, stride 65536
[2020-07-22 15:33:10,255] [INFO@telethon.2540353008715562232.client.downloads] File lives in another DC
[2020-07-22 15:33:10,437] [ERROR@mau.puppet.464063178] Failed to update info from source 1070511267
Traceback (most recent call last):
  File "/home/matrix/telegram-bridge/venv/lib/python3.8/site-packages/mautrix_telegram/puppet.py", line 245, in update_info
    changed = await self.update_avatar(source, info.photo) or changed
  File "/home/matrix/telegram-bridge/venv/lib/python3.8/site-packages/mautrix_telegram/puppet.py", line 321, in update_avatar
    file = await util.transfer_file_to_matrix(source.client, self.default_mxid_intent, loc)
  File "/home/matrix/telegram-bridge/venv/lib/python3.8/site-packages/mautrix_telegram/util/file_transfer.py", line 182, in transfer_file_to_matrix
    return await _unlocked_transfer_file_to_matrix(client, intent, location_id, location,
  File "/home/matrix/telegram-bridge/venv/lib/python3.8/site-packages/mautrix_telegram/util/file_transfer.py", line 238, in _unlocked_transfer_file_to_matrix
    content_uri = await intent.upload_media(file, upload_mime_type)
  File "/home/matrix/telegram-bridge/venv/lib/python3.8/site-packages/mautrix/appservice/api/intent.py", line 79, in wrapper
    return await __method(*args, **kwargs)
  File "/home/matrix/telegram-bridge/venv/lib/python3.8/site-packages/mautrix/client/api/modules/media_repository.py", line 58, in upload_media
    resp = await self.api.request(Method.POST, MediaPath.upload, content=data,
  File "/home/matrix/telegram-bridge/venv/lib/python3.8/site-packages/mautrix/api.py", line 205, in request
    return await self._send(method, endpoint, content, query_params, headers or {})
  File "/home/matrix/telegram-bridge/venv/lib/python3.8/site-packages/mautrix/api.py", line 144, in _send
    raise make_request_error(http_status=response.status,
mautrix.errors.request.MatrixUnknownRequestError: 404:
<html>
  <head><title>404 - No Such Resource</title></head>
  <body>
    <h1>No Such Resource</h1>
    <p>Sorry. No luck finding that resource.</p>
  </body>
</html>

[2020-07-22 15:33:10,638] [DEBUG@mau.user.@sharky:shark.pm] Dialog syncing complete
[2020-07-22 15:33:10,741] [INFO@aiohttp.access] 127.0.0.1 [22/Jul/2020:15:33:10 +0000] "PUT /transactions/647?access_token=snip HTTP/1.1" 200 158 "-" "Synapse/1.17.0"
```

Getting a lot of these errors in a fresh install from master branch.

**Comment by tulir** [comment]
Doesn't seem like it's related to the bridge, probably the wrong homeserver URL in the config.

**Comment by SharkyRawr** [comment]
Yes I do use media-repo and it's working fine for clients. ... and I think that's where the issue lies. The bridge was setup to use `localhost:8008` as its URL which has media stuff disabled in favor of matrix-media-repo hosted by the frontend nginx. Exchanged the URLs to the frontent and it seems to be working. Thanks!
