### ISSUE TITLE
matrix->telegram media upload stopped working

### ISSUE THREAD

**Issue by JuniorJPDJ** [tulir/mautrix-telegram#506]
Hi,
I updated to master version and now I'm getting errors like this.
Any media sent to matrix doesn't get sent to telegram.
```
mautrix-telegram_1  | [2020-08-04 11:35:27,303] [ERROR@mau.as] Exception in Matrix event handler
mautrix-telegram_1  | Traceback (most recent call last):
mautrix-telegram_1  |   File "/usr/lib/python3.8/site-packages/mautrix/appservice/as_handler.py", line 157, in try_handle
mautrix-telegram_1  |     await handler_func(event)
mautrix-telegram_1  |   File "/usr/lib/python3.8/site-packages/mautrix/bridge/matrix.py", line 364, in int_handle_event
mautrix-telegram_1  |     await self.handle_message(evt.room_id, evt.sender, evt.content, evt.event_id)
mautrix-telegram_1  |   File "/usr/lib/python3.8/site-packages/mautrix/bridge/matrix.py", line 277, in handle_message
mautrix-telegram_1  |     await portal.handle_matrix_message(sender, message, event_id)
mautrix-telegram_1  |   File "/usr/lib/python3.8/site-packages/mautrix_telegram/portal/matrix.py", line 370, in handle_matrix_message
mautrix-telegram_1  |     await self._handle_matrix_message(sender, content, event_id)
mautrix-telegram_1  |   File "/usr/lib/python3.8/site-packages/mautrix_telegram/portal/matrix.py", line 417, in _handle_matrix_message
mautrix-telegram_1  |     await self._handle_matrix_file(sender_id, event_id, space, client, content, reply_to,
mautrix-telegram_1  |   File "/usr/lib/python3.8/site-packages/mautrix_telegram/portal/matrix.py", line 261, in _handle_matrix_file
mautrix-telegram_1  |     file_handle, file_size = await parallel_transfer_to_telegram(client, self.main_intent,
mautrix-telegram_1  |   File "/usr/lib/python3.8/site-packages/mautrix_telegram/util/parallel_file_transfer.py", line 320, in parallel_transfer_to_telegram
mautrix-telegram_1  |     return await _internal_transfer_to_telegram(client, response)
mautrix-telegram_1  |   File "/usr/lib/python3.8/site-packages/mautrix_telegram/util/parallel_file_transfer.py", line 288, in _internal_transfer_to_telegram
mautrix-telegram_1  |     part_size, part_count, is_large = await uploader.init_upload(file_id, file_size)
mautrix-telegram_1  |   File "/usr/lib/python3.8/site-packages/mautrix_telegram/util/parallel_file_transfer.py", line 209, in init_upload
mautrix-telegram_1  |     await self._init_upload(connection_count, file_id, part_count, is_large)
mautrix-telegram_1  |   File "/usr/lib/python3.8/site-packages/mautrix_telegram/util/parallel_file_transfer.py", line 176, in _init_upload
mautrix-telegram_1  |     await self._create_upload_sender(file_id, part_count, big, 0, connections),
mautrix-telegram_1  |   File "/usr/lib/python3.8/site-packages/mautrix_telegram/util/parallel_file_transfer.py", line 184, in _create_upload_sender
mautrix-telegram_1  |     return UploadSender(await self._create_sender(), file_id, part_count, big, index, stride,
mautrix-telegram_1  |   File "/usr/lib/python3.8/site-packages/mautrix_telegram/util/parallel_file_transfer.py", line 189, in _create_sender
mautrix-telegram_1  |     sender = MTProtoSender(self.auth_key, self.loop, loggers=self.client._log)
mautrix-telegram_1  | TypeError: __init__() takes 2 positional arguments but 3 positional arguments (and 1 keyword-only argument) were given
```

**Comment by JuniorJPDJ** [comment]
Fixed in https://github.com/tulir/mautrix-telegram/commit/92c572d761e851c8c77a8d8b9d013d7898c0857e
