### ISSUE TITLE
[ERROR@mau.mx] Connection to homeserver failed

### ISSUE THREAD

**Issue by maeries** [tulir/mautrix-telegram#528]
I followed the [guide](https://github.com/tulir/mautrix-telegram/wiki/Bridge-setup-with-Docker) step 0 through 6 using docker-compose, but when I start mautrix-telegram I get an error

```
mautrix-telegram    | INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
mautrix-telegram    | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
mautrix-telegram    | [2020-10-13 12:35:45,947] [INFO@mau.init] Initializing mautrix-telegram 0.8.1+dev.f4b8e856
mautrix-telegram    | [2020-10-13 12:35:45,999] [INFO@mau.init] Initialization complete in 0.62 seconds
mautrix-telegram    | [2020-10-13 12:35:45,999] [DEBUG@mau.init] Running startup actions...
mautrix-telegram    | [2020-10-13 12:35:46,000] [DEBUG@mau.init] Starting appservice...
mautrix-telegram    | [2020-10-13 12:35:46,000] [DEBUG@mau.as] Starting appservice web server on 0.0.0.0:29317
mautrix-telegram    | [2020-10-13 12:35:46,003] [INFO@mau.mx] Ensuring connectivity to homeserver
mautrix-telegram    | [2020-10-13 12:35:46,009] [ERROR@mau.mx] Connection to homeserver failed, retrying in 10 seconds
mautrix-telegram    | Traceback (most recent call last):
mautrix-telegram    |   File "/usr/lib/python3.8/site-packages/aiohttp/connector.py", line 936, in _wrap_create_connection
mautrix-telegram    |     return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
mautrix-telegram    |   File "/usr/lib/python3.8/asyncio/base_events.py", line 1025, in create_connection
mautrix-telegram    |     raise exceptions[0]
mautrix-telegram    |   File "/usr/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection
mautrix-telegram    |     sock = await self._connect_sock(
mautrix-telegram    |   File "/usr/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock
mautrix-telegram    |     await self.sock_connect(sock, address)
mautrix-telegram    |   File "/usr/lib/python3.8/asyncio/selector_events.py", line 494, in sock_connect
mautrix-telegram    |     return await fut
mautrix-telegram    |   File "/usr/lib/python3.8/asyncio/selector_events.py", line 526, in _sock_connect_cb
mautrix-telegram    |     raise OSError(err, f'Connect call failed {address}')
mautrix-telegram    | ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.112.10', 80)
mautrix-telegram    | 
mautrix-telegram    | The above exception was the direct cause of the following exception:
mautrix-telegram    | 
mautrix-telegram    | Traceback (most recent call last):
mautrix-telegram    |   File "/usr/lib/python3.8/site-packages/mautrix/api.py", line 208, in request
mautrix-telegram    |     return await self._send(method, endpoint, content, query_params, headers or {})
mautrix-telegram    |   File "/usr/lib/python3.8/site-packages/mautrix/api.py", line 138, in _send
mautrix-telegram    |     async with request as response:
mautrix-telegram    |   File "/usr/lib/python3.8/site-packages/aiohttp/client.py", line 1012, in __aenter__
mautrix-telegram    |     self._resp = await self._coro
mautrix-telegram    |   File "/usr/lib/python3.8/site-packages/aiohttp/client.py", line 480, in _request
mautrix-telegram    |     conn = await self._connector.connect(
mautrix-telegram    |   File "/usr/lib/python3.8/site-packages/aiohttp/connector.py", line 523, in connect
mautrix-telegram    |     proto = await self._create_connection(req, traces, timeout)
mautrix-telegram    |   File "/usr/lib/python3.8/site-packages/aiohttp/connector.py", line 858, in _create_connection
mautrix-telegram    |     _, proto = await self._create_direct_connection(
mautrix-telegram    |   File "/usr/lib/python3.8/site-packages/aiohttp/connector.py", line 1004, in _create_direct_connection
mautrix-telegram    |     raise last_exc
mautrix-telegram    |   File "/usr/lib/python3.8/site-packages/aiohttp/connector.py", line 980, in _create_direct_connection
mautrix-telegram    |     transp, proto = await self._wrap_create_connection(
mautrix-telegram    |   File "/usr/lib/python3.8/site-packages/aiohttp/connector.py", line 943, in _wrap_create_connection
mautrix-telegram    |     raise client_error(req.connection_key, exc) from exc
mautrix-telegram    | aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host synapse:80 ssl:default [Connect call failed ('192.168.112.10', 80)]
mautrix-telegram    | 
mautrix-telegram    | The above exception was the direct cause of the following exception:
mautrix-telegram    | 
mautrix-telegram    | Traceback (most recent call last):
mautrix-telegram    |   File "/usr/lib/python3.8/site-packages/mautrix/bridge/matrix.py", line 92, in wait_for_connection
mautrix-telegram    |     await self.az.intent.whoami()
mautrix-telegram    |   File "/usr/lib/python3.8/site-packages/mautrix/client/api/authentication.py", line 154, in whoami
mautrix-telegram    |     resp = await self.api.request(Method.GET, Path.account.whoami)
mautrix-telegram    |   File "/usr/lib/python3.8/site-packages/mautrix/api.py", line 210, in request
mautrix-telegram    |     raise MatrixConnectionError(str(e)) from e
mautrix-telegram    | mautrix.errors.base.MatrixConnectionError: Cannot connect to host synapse:80 ssl:default [Connect call failed ('192.168.112.10', 80)]
```

I put both mautrix-telegram and synapse in the same docker network and then I docker-compose exec into the mautrix docker, I can ping "synapse" and get a response. Then why can't mautrix connect to it?

My config.yaml starts with
```
homeserver:
    # The address that this appservice can use to connect to the homeserver.
    address: http://synapse
```

**Comment by tulir** [comment]
Synapse usually doesn't listen on port 80

**Comment by maeries** [comment]
You're right. So I changed `address` to http://synapse:8008 and now the error looks a little bit different

```
mautrix-telegram    | INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
mautrix-telegram    | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
mautrix-telegram    | [2020-10-13 14:49:59,877] [INFO@mau.init] Initializing mautrix-telegram 0.8.1+dev.f4b8e856
mautrix-telegram    | [2020-10-13 14:49:59,929] [INFO@mau.init] Initialization complete in 0.63 seconds
mautrix-telegram    | [2020-10-13 14:49:59,930] [DEBUG@mau.init] Running startup actions...
mautrix-telegram    | [2020-10-13 14:49:59,931] [DEBUG@mau.init] Starting appservice...
mautrix-telegram    | [2020-10-13 14:49:59,931] [DEBUG@mau.as] Starting appservice web server on 0.0.0.0:29317
mautrix-telegram    | [2020-10-13 14:49:59,933] [INFO@mau.mx] Ensuring connectivity to homeserver
mautrix-telegram    | [2020-10-13 14:49:59,944] [ERROR@mau.mx] Connection to homeserver failed, retrying in 10 seconds
mautrix-telegram    | Traceback (most recent call last):
mautrix-telegram    |   File "/usr/lib/python3.8/site-packages/mautrix/bridge/matrix.py", line 92, in wait_for_connection
mautrix-telegram    |     await self.az.intent.whoami()
mautrix-telegram    |   File "/usr/lib/python3.8/site-packages/mautrix/client/api/authentication.py", line 154, in whoami
mautrix-telegram    |     resp = await self.api.request(Method.GET, Path.account.whoami)
mautrix-telegram    |   File "/usr/lib/python3.8/site-packages/mautrix/api.py", line 208, in request
mautrix-telegram    |     return await self._send(method, endpoint, content, query_params, headers or {})
mautrix-telegram    |   File "/usr/lib/python3.8/site-packages/mautrix/api.py", line 147, in _send
mautrix-telegram    |     raise make_request_error(http_status=response.status,
mautrix-telegram    | mautrix.errors.request.MUnknownToken: Invalid macaroon passed.
```

**Comment by tulir** [comment]
That's a registration error. Also, it's better to use the discussion room for debugging setup issues.
