### ISSUE TITLE
Error when cleaning unidentified rooms

### ISSUE THREAD

**Issue by karlprieb** [tulir/mautrix-telegram#541]
When I try clean some rooms I get this error:

Unhandled error while handling command:

```traceback
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mautrix/bridge/commands/handler.py", line 404, in handle
    await self._run_handler(handler, evt)
  File "/usr/lib/python3.8/site-packages/mautrix_telegram/commands/handler.py", line 121, in _run_handler
    return await handler(evt)
  File "/usr/lib/python3.8/site-packages/mautrix/bridge/commands/clean_rooms.py", line 184, in execute_room_cleanup
    await BasePortal.cleanup_room(evt.az.intent, room, "Room deleted")
  File "/usr/lib/python3.8/site-packages/mautrix/bridge/portal.py", line 95, in cleanup_room
    puppet = await cls.bridge.get_puppet(user_id, create=False)
AttributeError: type object 'BasePortal' has no attribute 'bridge'
```

**Comment by karlprieb** [comment]
Thanks @tulir 👍
