### ISSUE TITLE
Invalid user localpart for this application service

### ISSUE THREAD

**Issue by error10** [tulir/mautrix-telegram#542]
I'm initially setting up mautrix-telegram and after restarting Synapse with its registration.yaml, mautrix-telegram fails to run:

```
[2020-11-16 04:41:10,165] [INFO@mau.init] Initializing mautrix-telegram 0.8.1
[2020-11-16 04:41:10,202] [INFO@mau.init] Initialization complete in 0.26 seconds
[2020-11-16 04:41:10,202] [DEBUG@mau.init] Running startup actions...
[2020-11-16 04:41:10,203] [DEBUG@mau.init] Starting appservice...
[2020-11-16 04:41:10,203] [DEBUG@mau.as] Starting appservice web server on 0.0.0.0:29317
[2020-11-16 04:41:10,204] [INFO@mau.mx] Ensuring connectivity to homeserver
[2020-11-16 04:41:10,241] [DEBUG@mau.mx] Whoami endpoint returned M_FORBIDDEN, trying to register bridge bot before retrying...
[2020-11-16 04:41:10,249] [CRITICAL@mau.init] Unexpected error in main event loop
Traceback (most recent call last):
  File "/home/telegrambot/mautrix-telegram/lib/python3.8/site-packages/mautrix/bridge/matrix.py", line 75, in wait_for_connection
    await self.az.intent.whoami()
  File "/home/telegrambot/mautrix-telegram/lib/python3.8/site-packages/mautrix/client/api/authentication.py", line 32, in whoami
    resp = await self.api.request(Method.GET, Path.account.whoami)
  File "/home/telegrambot/mautrix-telegram/lib/python3.8/site-packages/mautrix/api/http.py", line 203, in request
    return await self._send(method, endpoint, content, query_params, headers or {})
  File "/home/telegrambot/mautrix-telegram/lib/python3.8/site-packages/mautrix/api/http.py", line 143, in _send
    raise make_request_error(http_status=response.status,
mautrix.errors.request.MForbidden: Application service has not registered this user
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/telegrambot/mautrix-telegram/lib/python3.8/site-packages/mautrix/appservice/api/intent.py", line 392, in ensure_registered
    await self._register()
  File "/home/telegrambot/mautrix-telegram/lib/python3.8/site-packages/mautrix/api/http.py", line 203, in request
    return await self._send(method, endpoint, content, query_params, headers or {})
  File "/home/telegrambot/mautrix-telegram/lib/python3.8/site-packages/mautrix/api/http.py", line 143, in _send
    raise make_request_error(http_status=response.status,
mautrix.errors.request.MExclusive: Invalid user localpart for this application service.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/telegrambot/mautrix-telegram/lib/python3.8/site-packages/mautrix/util/program.py", line 170, in _run
    self.loop.run_until_complete(self.start())
  File "/usr/lib64/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/telegrambot/mautrix-telegram/lib/python3.8/site-packages/mautrix/bridge/bridge.py", line 125, in start
    await self.matrix.wait_for_connection()
  File "/home/telegrambot/mautrix-telegram/lib/python3.8/site-packages/mautrix/bridge/matrix.py", line 81, in wait_for_connection
    await self.az.intent.ensure_registered()
  File "/home/telegrambot/mautrix-telegram/lib/python3.8/site-packages/mautrix/appservice/api/intent.py", line 395, in ensure_registered
    raise IntentError(f"Failed to register {self.mxid}", e)
mautrix.errors.base.IntentError: ('Failed to register @telegrambot:lrn.fm', MExclusive('Invalid user localpart for this application service.'))
```

Synapse appears to have correctly registered the appservice.

```
2020-11-16 04:40:03,598 - synapse.config.appservice - 87 - INFO - None - Loaded application service: ApplicationService: {'token': '<redacted>', 'url': 'http://localhost:29317', 'hs_token': '<redacted>', 'sender': '@ofomzzaf0pqxkabeycwe5bygwgp1z8g3j9f50xto01mrjgq5ro2ctvk2kep8ori9:matrix.lrn.fm', 'server_name': 'matrix.lrn.fm', 'namespaces': {'users': [{'exclusive': True, 'regex': re.compile('@telegram_.+:lrn.fm')}, {'exclusive': True, 'regex': re.compile('@telegrambot:lrn\\.fm')}], 'aliases': [{'exclusive': True, 'regex': re.compile('#telegram_.+:lrn.fm')}], 'rooms': []}, 'id': 'telegram', 'ip_range_whitelist': None, 'supports_ephemeral': False, 'protocols': set(), 'rate_limited': False}
````

But it doesn't want to register the user?

```
2020-11-16 04:41:10,239 - synapse.http.server - 74 - INFO - GET-912 - <XForwardedForRequest at 0x7fa46d766df0 method='GET' uri='/_matrix/client/r0/account/whoami?user_id=@telegrambot:lrn.fm' clientproto='HTTP/1.0' site=8008> SynapseError: 403 - Application service has not registered this user
2020-11-16 04:41:10,240 - synapse.access.http.8008 - 290 - INFO - GET-912 - 2607:5300:120:61d:3733::fe1c - 8008 - {None} Processed request: 0.003sec/-0.000sec (0.002sec, 0.000sec) (0.000sec/0.001sec/1) 84B 403 "GET /_matrix/client/r0/account/whoami?user_id=@telegrambot:lrn.fm HTTP/1.0" "Python/3.8 aiohttp/3.7.2" [0 dbevts]
2020-11-16 04:41:10,247 - synapse.http.server - 74 - INFO - POST-913 - <XForwardedForRequest at 0x7fa46c0b4190 method='POST' uri='/_matrix/client/r0/register?kind=user&user_id=@telegrambot:lrn.fm' clientproto='HTTP/1.0' site=8008> SynapseError: 400 - Invalid user localpart for this application service.
2020-11-16 04:41:10,248 - synapse.access.http.8008 - 290 - INFO - POST-913 - 2607:5300:120:61d:3733::fe1c - 8008 - {@ofomzzaf0pqxkabeycwe5bygwgp1z8g3j9f50xto01mrjgq5ro2ctvk2kep8ori9:matrix.lrn.fm} Processed request: 0.001sec/-0.000sec (0.001sec, 0.000sec) (0.000sec/0.000sec/0) 88B 400 "POST /_matrix/client/r0/register?kind=user&user_id=@telegrambot:lrn.fm HTTP/1.0" "Python/3.8 aiohttp/3.7.2" [0 dbevts]
```

I tried regenerating registration.yaml and restarting synapse again with the same results.

I'd love a pointer in the right direction here. Let me know if I failed to provide any relevant information.

**Comment by tulir** [comment]
You have the wrong `server_name` in the bridge config (although you might want to reset your synapse to remove the unnecessary `matrix.` subdomain)

**Comment by error10** [comment]
> You have the wrong `server_name` in the bridge config (although you might want to reset your synapse to remove the unnecessary `matrix.` subdomain)

I'm not following this. I can't find a server_name in the bridge config? There certainly is one in the homeserver config but it apparently cannot be changed.

**Comment by benwaffle** [comment]
@error10 changing `homeserver.domain` in mautrix-telegram's config fixed it for me
