### ISSUE TITLE
login-matrix causes pyscopg2.ProgrammingError: can't adapt type 'URL'

### ISSUE THREAD

**Issue by 14mRh4X0r** [tulir/mautrix-telegram#546]
It seems like it *does* get stored, because the error repeats itself every few seconds. Below is the first traceback with personal data redacted/omitted

```
Nov 23 16:30:26 matrix-integrations python[4030]: [WARNING@mau.puppet.XXX] Error when leaving rooms with default user
Nov 23 16:30:26 matrix-integrations python[4030]: Traceback (most recent call last):
Nov 23 16:30:26 matrix-integrations python[4030]:   File "/opt/mautrix-telegram/lib/python3.7/site-packages/mautrix/bridge/custom_puppet.py", line 208, in switch_mxid
Nov 23 16:30:26 matrix-integrations python[4030]:     await self._leave_rooms_with_default_user()
Nov 23 16:30:26 matrix-integrations python[4030]:   File "/opt/mautrix-telegram/lib/python3.7/site-packages/mautrix/bridge/custom_puppet.py", line 267, in _leave_rooms_with_default_user
Nov 23 16:30:26 matrix-integrations python[4030]:     if await self.default_puppet_should_leave_room(room_id):
Nov 23 16:30:26 matrix-integrations python[4030]: TypeError: object bool can't be used in 'await' expression
Nov 23 16:30:26 matrix-integrations python[4030]: [ERROR@aiohttp.server] Error handling request
Nov 23 16:30:26 matrix-integrations python[4030]: Traceback (most recent call last):
Nov 23 16:30:26 matrix-integrations python[4030]:   File "/opt/mautrix-telegram/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
Nov 23 16:30:26 matrix-integrations python[4030]:     cursor, statement, parameters, context
Nov 23 16:30:26 matrix-integrations python[4030]:   File "/opt/mautrix-telegram/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
Nov 23 16:30:26 matrix-integrations python[4030]:     cursor.execute(statement, parameters)
Nov 23 16:30:26 matrix-integrations python[4030]: psycopg2.ProgrammingError: can't adapt type 'URL'
Nov 23 16:30:26 matrix-integrations python[4030]: The above exception was the direct cause of the following exception:
Nov 23 16:30:26 matrix-integrations python[4030]: Traceback (most recent call last):
Nov 23 16:30:26 matrix-integrations python[4030]:   File "/opt/mautrix-telegram/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
Nov 23 16:30:26 matrix-integrations python[4030]:     resp = await self._request_handler(request)
Nov 23 16:30:26 matrix-integrations python[4030]:   File "/opt/mautrix-telegram/lib/python3.7/site-packages/aiohttp/web_app.py", line 499, in _handle
Nov 23 16:30:26 matrix-integrations python[4030]:     resp = await handler(request)
Nov 23 16:30:26 matrix-integrations python[4030]:   File "/opt/mautrix-telegram/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 118, in impl
Nov 23 16:30:26 matrix-integrations python[4030]:     return await handler(request)
Nov 23 16:30:26 matrix-integrations python[4030]:   File "/opt/mautrix-telegram/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 118, in impl
Nov 23 16:30:26 matrix-integrations python[4030]:     return await handler(request)
Nov 23 16:30:26 matrix-integrations python[4030]:   File "/opt/mautrix-telegram/lib/python3.7/site-packages/mautrix_telegram/web/public/__init__.py", line 150, in post_matrix_login
Nov 23 16:30:26 matrix-integrations python[4030]:     return await self.post_matrix_token(user, data["value"])
Nov 23 16:30:26 matrix-integrations python[4030]:   File "/opt/mautrix-telegram/lib/python3.7/site-packages/mautrix_telegram/web/common/auth_api.py", line 62, in post_matrix_token
Nov 23 16:30:26 matrix-integrations python[4030]:     await puppet.switch_mxid(token.strip(), user.mxid)
Nov 23 16:30:26 matrix-integrations python[4030]:   File "/opt/mautrix-telegram/lib/python3.7/site-packages/mautrix/bridge/custom_puppet.py", line 211, in switch_mxid
Nov 23 16:30:26 matrix-integrations python[4030]:     await self.save()
Nov 23 16:30:26 matrix-integrations python[4030]:   File "/opt/mautrix-telegram/lib/python3.7/site-packages/mautrix_telegram/puppet.py", line 174, in save
Nov 23 16:30:26 matrix-integrations python[4030]:     self.db_instance.edit(**self._fields)
Nov 23 16:30:26 matrix-integrations python[4030]:   File "/opt/mautrix-telegram/lib/python3.7/site-packages/mautrix/util/db/base.py", line 159, in edit
Nov 23 16:30:26 matrix-integrations python[4030]:     .values(**values))
Nov 23 16:30:26 matrix-integrations python[4030]:   File "/opt/mautrix-telegram/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
Nov 23 16:30:26 matrix-integrations python[4030]:     return meth(self, multiparams, params)
Nov 23 16:30:26 matrix-integrations python[4030]:   File "/opt/mautrix-telegram/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
Nov 23 16:30:26 matrix-integrations python[4030]:     return connection._execute_clauseelement(self, multiparams, params)
Nov 23 16:30:26 matrix-integrations python[4030]:   File "/opt/mautrix-telegram/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1130, in _execute_clauseelement
Nov 23 16:30:26 matrix-integrations python[4030]:     distilled_params,
Nov 23 16:30:26 matrix-integrations python[4030]:   File "/opt/mautrix-telegram/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
Nov 23 16:30:26 matrix-integrations python[4030]:     e, statement, parameters, cursor, context
Nov 23 16:30:26 matrix-integrations python[4030]:   File "/opt/mautrix-telegram/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
Nov 23 16:30:26 matrix-integrations python[4030]:     sqlalchemy_exception, with_traceback=exc_info[2], from_=e
Nov 23 16:30:26 matrix-integrations python[4030]:   File "/opt/mautrix-telegram/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
Nov 23 16:30:26 matrix-integrations python[4030]:     raise exception
Nov 23 16:30:26 matrix-integrations python[4030]:   File "/opt/mautrix-telegram/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
Nov 23 16:30:26 matrix-integrations python[4030]:     cursor, statement, parameters, context
Nov 23 16:30:26 matrix-integrations python[4030]:   File "/opt/mautrix-telegram/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
Nov 23 16:30:26 matrix-integrations python[4030]:     cursor.execute(statement, parameters)
Nov 23 16:30:26 matrix-integrations python[4030]: sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) can't adapt type 'URL'
Nov 23 16:30:26 matrix-integrations python[4030]: [SQL: UPDATE puppet SET custom_mxid=%(custom_mxid)s, access_token=%(access_token)s, next_batch=%(next_batch)s, base_url=%(base_url)s, displayname=%(displayname)s, displayname_source=%(displayname_source)s, username=%(username)s, photo_id=%(photo_id)s, is_bot=%(is_bot)s, matrix_registered=%(matrix_registered)s, disable_updates=%(disable_updates)s WHERE puppet.id = %(id_1)s]
```

**Comment by mpaulon** [comment]
I've fixed it on my side by doing `base_url=str(self.base_url) ` here: https://github.com/tulir/mautrix-telegram/blob/140fcae403789dd6172754f19ab8d226efdb3df0/mautrix_telegram/puppet.py#L168
I don't know if there is a better way to tell sqlalchemy to cast the URL as a string.
