### ISSUE TITLE
AttributeError: 'MessageFwdHeader' object has no attribute 'channel_id'

### ISSUE THREAD

**Issue by Bubu** [tulir/mautrix-telegram#549]
I get a bunch of these in my log:

```
Dec 01 13:27:31 bubu python[29675]: [2020-12-01 13:27:31,032] [ERROR@mau.user.@X] Error while backfilling [abc]
Dec 01 13:27:31 bubu python[29675]: Traceback (most recent call last):
Dec 01 13:27:31 bubu python[29675]:   File "/usr/lib/python3.8/site-packages/mautrix_telegram/user.py", line 368, in _catch
Dec 01 13:27:31 bubu python[29675]:     await task
Dec 01 13:27:31 bubu python[29675]:   File "/usr/lib/python3.8/site-packages/mautrix_telegram/portal/telegram.py", line 444, in backfill
Dec 01 13:27:31 bubu python[29675]:     await self._locked_backfill(source, is_initial, limit, last_id)
Dec 01 13:27:31 bubu python[29675]:   File "/usr/lib/python3.8/site-packages/mautrix_telegram/portal/telegram.py", line 484, in _locked_backfill
Dec 01 13:27:31 bubu python[29675]:     await self._backfill(source, min_id, limit)
Dec 01 13:27:31 bubu python[29675]:   File "/usr/lib/python3.8/site-packages/mautrix_telegram/portal/telegram.py", line 503, in _backfill
Dec 01 13:27:31 bubu python[29675]:     count = await self._backfill_messages(source, min_id, limit, client)
Dec 01 13:27:31 bubu python[29675]:   File "/usr/lib/python3.8/site-packages/mautrix_telegram/portal/telegram.py", line 530, in _backfill_messages
Dec 01 13:27:31 bubu python[29675]:     await self.handle_telegram_message(source, sender, message)
Dec 01 13:27:31 bubu python[29675]:   File "/usr/lib/python3.8/site-packages/mautrix_telegram/portal/telegram.py", line 552, in handle_telegram_message
Dec 01 13:27:31 bubu python[29675]:     duplicate_found = self.dedup.check(evt, (temporary_identifier, tg_space))
Dec 01 13:27:31 bubu python[29675]:   File "/usr/lib/python3.8/site-packages/mautrix_telegram/portal/deduplication.py", line 109, in check
Dec 01 13:27:31 bubu python[29675]:     evt_hash = (self._hash_event(event)
Dec 01 13:27:31 bubu python[29675]:   File "/usr/lib/python3.8/site-packages/mautrix_telegram/portal/deduplication.py", line 66, in _hash_event
Dec 01 13:27:31 bubu python[29675]:     hash_content += [event.fwd_from.from_id, event.fwd_from.channel_id]
Dec 01 13:27:31 bubu python[29675]: AttributeError: 'MessageFwdHeader' object has no attribute 'channel_id'
```

**Comment by JuniorJPDJ** [comment]
Same:
```
mautrix-telegram_1           | [2020-12-10 09:43:32,059] [ERROR@mau.user.@juniorjpdj:juniorjpdj.pl] Failed to handle Telegram update UpdateNewMessage(message=Message(id=1099764, peer_id=PeerChat(chat_id=391369173), date=datetime.datetime(2020, 12, 10, 9, 43, 32, tzinfo=datetime.timezone.utc), message='coraz słabiej', out=False, mentioned=False, media_unread=False, silent=False, post=False, from_scheduled=False, legacy=False, edit_hide=False, pinned=False, from_id=PeerUser(user_id=638392877), fwd_from=MessageFwdHeader(date=datetime.datetime(2020, 12, 10, 9, 42, 1, tzinfo=datetime.timezone.utc), from_id=PeerUser(user_id=638392877), from_name=None, channel_post=None, post_author=None, saved_from_peer=None, saved_from_msg_id=None, psa_type=None), via_bot_id=None, reply_to=None, media=None, reply_markup=None, entities=[], views=None, forwards=None, replies=None, edit_date=None, post_author=None, grouped_id=None, restriction_reason=[]), pts=1919865, pts_count=1)
mautrix-telegram_1           | Traceback (most recent call last):
mautrix-telegram_1           |   File "/usr/lib/python3.8/site-packages/mautrix_telegram/abstract_user.py", line 195, in _update_catch
mautrix-telegram_1           |     await self._update(update)
mautrix-telegram_1           |   File "/usr/lib/python3.8/site-packages/mautrix_telegram/abstract_user.py", line 242, in _update
mautrix-telegram_1           |     await self.update_message(update)
mautrix-telegram_1           |   File "/usr/lib/python3.8/site-packages/mautrix_telegram/abstract_user.py", line 477, in update_message
mautrix-telegram_1           |     return await portal.handle_telegram_message(self, sender, update)
mautrix-telegram_1           |   File "/usr/lib/python3.8/site-packages/mautrix_telegram/portal/telegram.py", line 552, in handle_telegram_message
mautrix-telegram_1           |     duplicate_found = self.dedup.check(evt, (temporary_identifier, tg_space))
mautrix-telegram_1           |   File "/usr/lib/python3.8/site-packages/mautrix_telegram/portal/deduplication.py", line 109, in check
mautrix-telegram_1           |     evt_hash = (self._hash_event(event)
mautrix-telegram_1           |   File "/usr/lib/python3.8/site-packages/mautrix_telegram/portal/deduplication.py", line 66, in _hash_event
mautrix-telegram_1           |     hash_content += [event.fwd_from.from_id, event.fwd_from.channel_id]
mautrix-telegram_1           | AttributeError: 'MessageFwdHeader' object has no attribute 'channel_id'
```
