### ISSUE TITLE
read receipts in tg chat with ouble puppeted user cause issues

### ISSUE THREAD

**Issue by Bubu** [tulir/mautrix-telegram#567]
I'm not sure if this is a user but the chat works completely fine except TG -> matrix RR:

The user I'm chatting with is also double-puppeted via the same bridge... which I guess is the issue.

```
Dec 27 17:30:29 bubu python[65009]: [2020-12-27 17:30:29,453] [ERROR@mau.user.@bubu:bubu1.eu] Failed to handle Telegram update UpdateReadHistoryOutbox(peer=PeerUser(user_id=92404833), max_id=196646,>
Dec 27 17:30:29 bubu python[65009]: Traceback (most recent call last):
Dec 27 17:30:29 bubu python[65009]:   File "/usr/lib/python3.9/site-packages/mautrix/appservice/api/intent.py", line 320, in ensure_joined
Dec 27 17:30:29 bubu python[65009]:     await self.join_room(room_id, max_retries=0)
Dec 27 17:30:29 bubu python[65009]:   File "/usr/lib/python3.9/site-packages/mautrix/appservice/api/intent.py", line 79, in wrapper
Dec 27 17:30:29 bubu python[65009]:     return await __method(*args, **kwargs)
Dec 27 17:30:29 bubu python[65009]:   File "/usr/lib/python3.9/site-packages/mautrix/client/api/rooms.py", line 252, in join_room
Dec 27 17:30:29 bubu python[65009]:     content = await self.api.request(Method.POST, Path.join[room_id_or_alias],
Dec 27 17:30:29 bubu python[65009]:   File "/usr/lib/python3.9/site-packages/mautrix/api.py", line 233, in request
Dec 27 17:30:29 bubu python[65009]:     return await self._send(method, full_url, content, query_params, headers or {})
Dec 27 17:30:29 bubu python[65009]:   File "/usr/lib/python3.9/site-packages/mautrix/api.py", line 158, in _send
Dec 27 17:30:29 bubu python[65009]:     raise make_request_error(http_status=response.status,
Dec 27 17:30:29 bubu python[65009]: mautrix.errors.request.MForbidden: You are not invited to this room.
Dec 27 17:30:29 bubu python[65009]: During handling of the above exception, another exception occurred:
Dec 27 17:30:29 bubu python[65009]: Traceback (most recent call last):
Dec 27 17:30:29 bubu python[65009]:   File "/usr/lib/python3.9/site-packages/mautrix/appservice/api/intent.py", line 320, in ensure_joined
Dec 27 17:30:29 bubu python[65009]:     await self.join_room(room_id, max_retries=0)
Dec 27 17:30:29 bubu python[65009]:   File "/usr/lib/python3.9/site-packages/mautrix/appservice/api/intent.py", line 79, in wrapper
Dec 27 17:30:29 bubu python[65009]:     return await __method(*args, **kwargs)
Dec 27 17:30:29 bubu python[65009]:   File "/usr/lib/python3.9/site-packages/mautrix/client/api/rooms.py", line 252, in join_room
Dec 27 17:30:29 bubu python[65009]:     content = await self.api.request(Method.POST, Path.join[room_id_or_alias],
Dec 27 17:30:29 bubu python[65009]:   File "/usr/lib/python3.9/site-packages/mautrix/api.py", line 233, in request
Dec 27 17:30:29 bubu python[65009]:     return await self._send(method, full_url, content, query_params, headers or {})
Dec 27 17:30:29 bubu python[65009]:   File "/usr/lib/python3.9/site-packages/mautrix/api.py", line 158, in _send
Dec 27 17:30:29 bubu python[65009]:     raise make_request_error(http_status=response.status,
Dec 27 17:30:29 bubu python[65009]: mautrix.errors.request.MForbidden: You are not invited to this room.
Dec 27 17:30:29 bubu python[65009]: The above exception was the direct cause of the following exception:
Dec 27 17:30:29 bubu python[65009]: Traceback (most recent call last):
Dec 27 17:30:29 bubu python[65009]:   File "/usr/lib/python3.9/site-packages/mautrix_telegram/abstract_user.py", line 195, in _update_catch
Dec 27 17:30:29 bubu python[65009]:     await self._update(update)
Dec 27 17:30:29 bubu python[65009]:   File "/usr/lib/python3.9/site-packages/mautrix_telegram/abstract_user.py", line 260, in _update
Dec 27 17:30:29 bubu python[65009]:     await self.update_read_receipt(update)
Dec 27 17:30:29 bubu python[65009]:   File "/usr/lib/python3.9/site-packages/mautrix_telegram/abstract_user.py", line 297, in update_read_receipt
Dec 27 17:30:29 bubu python[65009]:     await puppet.intent.mark_read(portal.mxid, message.mxid)
Dec 27 17:30:29 bubu python[65009]:   File "/usr/lib/python3.9/site-packages/mautrix/appservice/api/intent.py", line 307, in mark_read
Dec 27 17:30:29 bubu python[65009]:     await self.set_fully_read_marker(room_id, fully_read=event_id, read_receipt=event_id)
Dec 27 17:30:29 bubu python[65009]:   File "/usr/lib/python3.9/site-packages/mautrix/appservice/api/intent.py", line 90, in wrapper
Dec 27 17:30:29 bubu python[65009]:     await __self.ensure_joined(room_id)
Dec 27 17:30:29 bubu python[65009]:   File "/usr/lib/python3.9/site-packages/mautrix/appservice/api/intent.py", line 326, in ensure_joined
Dec 27 17:30:29 bubu python[65009]:     await self.bot.invite_user(room_id, self.mxid)
Dec 27 17:30:29 bubu python[65009]:   File "/usr/lib/python3.9/site-packages/mautrix/appservice/api/intent.py", line 90, in wrapper
Dec 27 17:30:29 bubu python[65009]:     await __self.ensure_joined(room_id)
Dec 27 17:30:29 bubu python[65009]:   File "/usr/lib/python3.9/site-packages/mautrix/appservice/api/intent.py", line 324, in ensure_joined
Dec 27 17:30:29 bubu python[65009]:     raise IntentError(f"Failed to join room {room_id} as {self.mxid}") from e
Dec 27 17:30:29 bubu python[65009]: mautrix.errors.base.IntentError: Failed to join room !tpxuCYboyuYEhEpOyf:bubu1.eu as @telegrambot:bubu1.eu
```

**Comment by benjajaja** [comment]
Same problem here, pasting log here because I guess the files/lines are a bit more up to date.

I really don't understand why this fails, literally everything else re: double-puppetting works, it's just that sometimes messages are not marked as read in matrix.

```
Aug 24 11:24:26 ops mautrix-telegram[143144]: [2025-08-24 11:24:26,356] [DEBUG@mau.as.api.@benjajaja:qdice.wtf] req #3558: POST http://localhost:8008/_matrix/client/v3/rooms/%21rLpLTbdYZJfYVcwTUJ%3Aqdice.wtf/read_markers?user_id=@benjajaja:qdice.wtf {"m.fully_read": "$k6uDjba3IaGqQ-dMMh4MPujOfdfve3q2AceZLCXMX-s", "m.read": "$k6uDjba3IaGqQ-dMMh4MPujOfdfve3q2AceZLCXMX-s", "com.beeper.fully_read.extra": {"fi.mau.double_puppet_source": "mautrix-telegram"}, "com.beeper.read.extra": {"fi.mau.double_puppet_source": "mautrix-telegram"}}
Aug 24 11:24:26 ops mautrix-telegram[143144]: [2025-08-24 11:24:26,387] [DEBUG@mau.as.api.@benjajaja:qdice.wtf] req #3558 (/v3/rooms/%21rLpLTbdYZJfYVcwTUJ%3Aqdice.wtf/read_markers) completed in 30.6ms with status 403
Aug 24 11:24:26 ops mautrix-telegram[143144]: [2025-08-24 11:24:26,387] [ERROR@mau.user.@dcam:qdice.wtf] Failed to handle Telegram update
Aug 24 11:24:26 ops mautrix-telegram[143144]: Traceback (most recent call last):
Aug 24 11:24:26 ops mautrix-telegram[143144]:   File "/nix/store/kx9y9qawsabibysnh9dmj4l91ida84ly-python3.12-mautrix-telegram-0.15.2/lib/python3.12/site-packages/mautrix_telegram/abstract_user.py", line 302, in _update_catch
Aug 24 11:24:26 ops mautrix-telegram[143144]:     await self._update(update)
Aug 24 11:24:26 ops mautrix-telegram[143144]:   File "/nix/store/kx9y9qawsabibysnh9dmj4l91ida84ly-python3.12-mautrix-telegram-0.15.2/lib/python3.12/site-packages/mautrix_telegram/abstract_user.py", line 402, in _update
Aug 24 11:24:26 ops mautrix-telegram[143144]:     await self.update_read_receipt(update)
Aug 24 11:24:26 ops mautrix-telegram[143144]:   File "/nix/store/kx9y9qawsabibysnh9dmj4l91ida84ly-python3.12-mautrix-telegram-0.15.2/lib/python3.12/site-packages/mautrix_telegram/abstract_user.py", line 468, in update_read_receipt
Aug 24 11:24:26 ops mautrix-telegram[143144]:     await puppet.intent.mark_read(portal.mxid, message.mxid)
Aug 24 11:24:26 ops mautrix-telegram[143144]:   File "/nix/store/4wz4q70h84xn7vli33qcmygslzshnm39-python3.12-mautrix-0.20.7/lib/python3.12/site-packages/mautrix/appservice/api/intent.py", line 493, in mark_read
Aug 24 11:24:26 ops mautrix-telegram[143144]:     await self.set_fully_read_marker(
Aug 24 11:24:26 ops mautrix-telegram[143144]:   File "/nix/store/4wz4q70h84xn7vli33qcmygslzshnm39-python3.12-mautrix-0.20.7/lib/python3.12/site-packages/mautrix/appservice/api/intent.py", line 130, in wrapper
Aug 24 11:24:26 ops mautrix-telegram[143144]:     return await __method(*args, **kwargs)
Aug 24 11:24:26 ops mautrix-telegram[143144]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 24 11:24:26 ops mautrix-telegram[143144]:   File "/nix/store/4wz4q70h84xn7vli33qcmygslzshnm39-python3.12-mautrix-0.20.7/lib/python3.12/site-packages/mautrix/client/api/modules/misc.py", line 113, in set_fully_read_marker
Aug 24 11:24:26 ops mautrix-telegram[143144]:     await self.api.request(Method.POST, Path.v3.rooms[room_id].read_markers, content)
Aug 24 11:24:26 ops mautrix-telegram[143144]:   File "/nix/store/4wz4q70h84xn7vli33qcmygslzshnm39-python3.12-mautrix-0.20.7/lib/python3.12/site-packages/mautrix/api.py", line 425, in request
Aug 24 11:24:26 ops mautrix-telegram[143144]:     resp_data, resp = await self._send(
Aug 24 11:24:26 ops mautrix-telegram[143144]:                       ^^^^^^^^^^^^^^^^^
Aug 24 11:24:26 ops mautrix-telegram[143144]:   File "/nix/store/4wz4q70h84xn7vli33qcmygslzshnm39-python3.12-mautrix-0.20.7/lib/python3.12/site-packages/mautrix/api.py", line 265, in _send
Aug 24 11:24:26 ops mautrix-telegram[143144]:     raise make_request_error(
Aug 24 11:24:26 ops mautrix-telegram[143144]: mautrix.errors.request.MForbidden: You don't have permission to access that event.
```
