### ISSUE TITLE
probably related to me not having any memory or deleting local_thumbnails

### ISSUE THREAD

**Issue by chagai95** [tulir/mautrix-telegram#588]
```
Feb 21 22:21:58 chagai-server matrix-mautrix-telegram[561323]: WARNING: Error loading config file: .dockercfg: $HOME is not defined
Feb 21 22:21:58 chagai-server matrix-mautrix-telegram[561323]: Error response from daemon: Cannot kill container: matrix-mautrix-telegram: No such container: matrix-mautrix-telegram
Feb 21 22:21:58 chagai-server matrix-mautrix-telegram[561344]: WARNING: Error loading config file: .dockercfg: $HOME is not defined
Feb 21 22:21:58 chagai-server matrix-mautrix-telegram[561344]: Error: No such container: matrix-mautrix-telegram
Feb 21 22:21:58 chagai-server matrix-mautrix-telegram[561353]: WARNING: Error loading config file: .dockercfg: $HOME is not defined
Feb 21 22:22:00 chagai-server matrix-mautrix-telegram[561353]: Traceback (most recent call last):
Feb 21 22:22:00 chagai-server matrix-mautrix-telegram[561353]:   File "/usr/lib/python3.8/site-packages/mautrix_telegram/config.py", line 32, in __getitem__
Feb 21 22:22:00 chagai-server matrix-mautrix-telegram[561353]:     return os.environ[f"MAUTRIX_TELEGRAM_{key.replace('.', '_').upper()}"]
Feb 21 22:22:00 chagai-server matrix-mautrix-telegram[561353]:   File "/usr/lib/python3.8/os.py", line 675, in __getitem__
Feb 21 22:22:00 chagai-server matrix-mautrix-telegram[561353]:     raise KeyError(key) from None
Feb 21 22:22:00 chagai-server matrix-mautrix-telegram[561353]: KeyError: 'MAUTRIX_TELEGRAM_APPSERVICE_DATABASE'
Feb 21 22:22:00 chagai-server matrix-mautrix-telegram[561353]: During handling of the above exception, another exception occurred:
Feb 21 22:22:00 chagai-server matrix-mautrix-telegram[561353]: Traceback (most recent call last):
Feb 21 22:22:00 chagai-server matrix-mautrix-telegram[561353]:   File "/usr/bin/alembic", line 11, in <module>
Feb 21 22:22:00 chagai-server matrix-mautrix-telegram[561353]:     load_entry_point('alembic==1.4.2', 'console_scripts', 'alembic')()
Feb 21 22:22:00 chagai-server matrix-mautrix-telegram[561353]:   File "/usr/lib/python3.8/site-packages/alembic/config.py", line 577, in main
Feb 21 22:22:00 chagai-server matrix-mautrix-telegram[561353]:     CommandLine(prog=prog).main(argv=argv)
Feb 21 22:22:00 chagai-server matrix-mautrix-telegram[561353]:   File "/usr/lib/python3.8/site-packages/alembic/config.py", line 571, in main
Feb 21 22:22:00 chagai-server matrix-mautrix-telegram[561353]:     self.run_cmd(cfg, options)
Feb 21 22:22:00 chagai-server matrix-mautrix-telegram[561353]:   File "/usr/lib/python3.8/site-packages/alembic/config.py", line 548, in run_cmd
Feb 21 22:22:00 chagai-server matrix-mautrix-telegram[561353]:     fn(
Feb 21 22:22:00 chagai-server matrix-mautrix-telegram[561353]:   File "/usr/lib/python3.8/site-packages/alembic/command.py", line 298, in upgrade
Feb 21 22:22:00 chagai-server matrix-mautrix-telegram[561353]:     script.run_env()
Feb 21 22:22:00 chagai-server matrix-mautrix-telegram[561353]:   File "/usr/lib/python3.8/site-packages/alembic/script/base.py", line 489, in run_env
Feb 21 22:22:00 chagai-server matrix-mautrix-telegram[561353]:     util.load_python_file(self.dir, "env.py")
Feb 21 22:22:00 chagai-server matrix-mautrix-telegram[561353]:   File "/usr/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 98, in load_python_file
Feb 21 22:22:00 chagai-server matrix-mautrix-telegram[561353]:     module = load_module_py(module_id, path)
Feb 21 22:22:00 chagai-server matrix-mautrix-telegram[561353]:   File "/usr/lib/python3.8/site-packages/alembic/util/compat.py", line 184, in load_module_py
Feb 21 22:22:00 chagai-server matrix-mautrix-telegram[561353]:     spec.loader.exec_module(module)
Feb 21 22:22:00 chagai-server matrix-mautrix-telegram[561353]:   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
Feb 21 22:22:00 chagai-server matrix-mautrix-telegram[561353]:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
Feb 21 22:22:00 chagai-server matrix-mautrix-telegram[561353]:   File "alembic/env.py", line 22, in <module>
Feb 21 22:22:00 chagai-server matrix-mautrix-telegram[561353]:     config.set_main_option("sqlalchemy.url", mxtg_config["appservice.database"].replace("%", "%%"))
Feb 21 22:22:00 chagai-server matrix-mautrix-telegram[561353]:   File "/usr/lib/python3.8/site-packages/mautrix_telegram/config.py", line 34, in __getitem__
Feb 21 22:22:00 chagai-server matrix-mautrix-telegram[561353]:     return super().__getitem__(key)
Feb 21 22:22:00 chagai-server matrix-mautrix-telegram[561353]:   File "/usr/lib/python3.8/site-packages/mautrix/util/config/recursive_dict.py", line 49, in __getitem__
Feb 21 22:22:00 chagai-server matrix-mautrix-telegram[561353]:     return self.get(key, None)
Feb 21 22:22:00 chagai-server matrix-mautrix-telegram[561353]:   File "/usr/lib/python3.8/site-packages/mautrix/util/config/recursive_dict.py", line 45, in get
Feb 21 22:22:00 chagai-server matrix-mautrix-telegram[561353]:     return self._recursive_get(self._data, key, default_value)
Feb 21 22:22:00 chagai-server matrix-mautrix-telegram[561353]:   File "/usr/lib/python3.8/site-packages/mautrix/util/config/recursive_dict.py", line 36, in _recursive_get
Feb 21 22:22:00 chagai-server matrix-mautrix-telegram[561353]:     next_data = data.get(key, self._dict_factory())
Feb 21 22:22:00 chagai-server matrix-mautrix-telegram[561353]: AttributeError: 'NoneType' object has no attribute 'get'


```

**Comment by chagai95** [comment]
I restarted  the bridge and synapse and now the bridge bot is broken but the double puppeting is fine:


```

Feb 22 08:29:54 chagai-server matrix-mautrix-telegram[585986]: [2021-02-22 07:29:54,549] [DEBUG@telethon.299986122.network.mtprotosender] Handling update UpdateShort
Feb 22 08:29:54 chagai-server matrix-mautrix-telegram[585986]: [2021-02-22 07:29:54,550] [DEBUG@telethon.299986122.network.mtprotosender] Receiving items from the network...
Feb 22 08:29:55 chagai-server matrix-mautrix-telegram[585986]: [2021-02-22 07:29:55,194] [DEBUG@telethon.299986122.network.mtprotosender] Handling update UpdateShort
Feb 22 08:29:55 chagai-server matrix-mautrix-telegram[585986]: [2021-02-22 07:29:55,194] [DEBUG@telethon.299986122.network.mtprotosender] Receiving items from the network...
Feb 22 08:29:56 chagai-server matrix-mautrix-telegram[585986]: [2021-02-22 07:29:56,064] [DEBUG@telethon.299986122.extensions.messagepacker] Assigned msg_id = 6931987004507578136 to UpdateStatusRequest (7f887b042880)
Feb 22 08:29:56 chagai-server matrix-mautrix-telegram[585986]: [2021-02-22 07:29:56,064] [DEBUG@telethon.299986122.network.mtprotosender] Encrypting 1 message(s) in 24 bytes for sending
Feb 22 08:29:56 chagai-server matrix-mautrix-telegram[585986]: [2021-02-22 07:29:56,064] [DEBUG@telethon.299986122.network.mtprotosender] Encrypted messages put in a queue to be sent
Feb 22 08:29:56 chagai-server matrix-mautrix-telegram[585986]: [2021-02-22 07:29:56,064] [DEBUG@telethon.299986122.network.mtprotosender] Waiting for messages to send...
Feb 22 08:29:56 chagai-server matrix-mautrix-telegram[585986]: [2021-02-22 07:29:56,064] [DEBUG@telethon.299986122.extensions.messagepacker] Assigned msg_id = 6931987004510407688 to MsgsAck (7f887963da90)
Feb 22 08:29:56 chagai-server matrix-mautrix-telegram[585986]: [2021-02-22 07:29:56,065] [DEBUG@telethon.299986122.network.mtprotosender] Encrypting 1 message(s) in 68 bytes for sending
Feb 22 08:29:56 chagai-server matrix-mautrix-telegram[585986]: [2021-02-22 07:29:56,065] [DEBUG@telethon.299986122.network.mtprotosender] Encrypted messages put in a queue to be sent
Feb 22 08:29:56 chagai-server matrix-mautrix-telegram[585986]: [2021-02-22 07:29:56,065] [DEBUG@telethon.299986122.network.mtprotosender] Waiting for messages to send...
Feb 22 08:29:56 chagai-server matrix-mautrix-telegram[585986]: [2021-02-22 07:29:56,117] [DEBUG@telethon.299986122.network.mtprotosender] Handling RPC result for message 6931987004507578136
Feb 22 08:29:56 chagai-server matrix-mautrix-telegram[585986]: [2021-02-22 07:29:56,117] [DEBUG@telethon.299986122.network.mtprotosender] Receiving items from the network...
Feb 22 08:29:56 chagai-server matrix-mautrix-telegram[585986]: [2021-02-22 07:29:56,597] [DEBUG@telethon.299986122.network.mtprotosender] Handling update Updates
Feb 22 08:29:56 chagai-server matrix-mautrix-telegram[585986]: [2021-02-22 07:29:56,612] [DEBUG@telethon.299986122.network.mtprotosender] Receiving items from the network...
Feb 22 08:29:56 chagai-server matrix-mautrix-telegram[585986]: [2021-02-22 07:29:56,613] [ERROR@mau.user.@chagai:chagai.website] Failed to handle Telegram update UpdateNewChannelMessage(message=Message(id=452, peer_id=PeerChannel(channel_id=1468629521), date=datetime.datetime(2021, 2, 22, 7, 29, 56, tzinfo=datetime.timezone.utc), message='test', out=False, mentioned=False, media_unread=False, silent=False, post=False, from_scheduled=False, legacy=False, edit_hide=False, from_id=PeerUser(user_id=1128218481), fwd_from=None, via_bot_id=None, reply_to=None, media=None, reply_markup=None, entities=[], views=None, forwards=None, replies=MessageReplies(replies=0, replies_pts=499, comments=False, recent_repliers=[], channel_id=None, max_id=None, read_max_id=None), edit_date=None, post_author=None, grouped_id=None, restriction_reason=[]), pts=499, pts_count=1)
Feb 22 08:29:56 chagai-server matrix-mautrix-telegram[585986]: Traceback (most recent call last):
Feb 22 08:29:56 chagai-server matrix-mautrix-telegram[585986]:   File "/usr/lib/python3.8/site-packages/mautrix_telegram/abstract_user.py", line 195, in _update_catch
Feb 22 08:29:56 chagai-server matrix-mautrix-telegram[585986]:     await self._update(update)
Feb 22 08:29:56 chagai-server matrix-mautrix-telegram[585986]:   File "/usr/lib/python3.8/site-packages/mautrix_telegram/abstract_user.py", line 242, in _update
Feb 22 08:29:56 chagai-server matrix-mautrix-telegram[585986]:     await self.update_message(update)
Feb 22 08:29:56 chagai-server matrix-mautrix-telegram[585986]:   File "/usr/lib/python3.8/site-packages/mautrix_telegram/abstract_user.py", line 476, in update_message
Feb 22 08:29:56 chagai-server matrix-mautrix-telegram[585986]:     return await portal.handle_telegram_message(self, sender, update)
Feb 22 08:29:56 chagai-server matrix-mautrix-telegram[585986]:   File "/usr/lib/python3.8/site-packages/mautrix_telegram/portal/telegram.py", line 594, in handle_telegram_message
Feb 22 08:29:56 chagai-server matrix-mautrix-telegram[585986]:     event_id = await self.handle_telegram_text(source, intent, is_bot, evt)
Feb 22 08:29:56 chagai-server matrix-mautrix-telegram[585986]:   File "/usr/lib/python3.8/site-packages/mautrix_telegram/portal/telegram.py", line 280, in handle_telegram_text
Feb 22 08:29:56 chagai-server matrix-mautrix-telegram[585986]:     return await self._send_message(intent, content, timestamp=evt.date)
Feb 22 08:29:56 chagai-server matrix-mautrix-telegram[585986]:   File "/usr/lib/python3.8/site-packages/mautrix/bridge/portal.py", line 68, in _send_message
Feb 22 08:29:56 chagai-server matrix-mautrix-telegram[585986]:     return await call_with_net_retry(intent.send_message_event, self.mxid, event_type, content,
Feb 22 08:29:56 chagai-server matrix-mautrix-telegram[585986]:   File "/usr/lib/python3.8/site-packages/mautrix/util/network_retry.py", line 33, in call_with_net_retry
Feb 22 08:29:56 chagai-server matrix-mautrix-telegram[585986]:     return await func(*args, **kwargs)
Feb 22 08:29:56 chagai-server matrix-mautrix-telegram[585986]:   File "/usr/lib/python3.8/site-packages/mautrix/appservice/api/intent.py", line 91, in wrapper
Feb 22 08:29:56 chagai-server matrix-mautrix-telegram[585986]:     return await __method(*args, **kwargs)
Feb 22 08:29:56 chagai-server matrix-mautrix-telegram[585986]:   File "/usr/lib/python3.8/site-packages/mautrix/appservice/api/intent.py", line 266, in send_message_event
Feb 22 08:29:56 chagai-server matrix-mautrix-telegram[585986]:     await self._ensure_has_power_level_for(room_id, event_type)
Feb 22 08:29:56 chagai-server matrix-mautrix-telegram[585986]:   File "/usr/lib/python3.8/site-packages/mautrix/appservice/api/intent.py", line 372, in _ensure_has_power_level_for
Feb 22 08:29:56 chagai-server matrix-mautrix-telegram[585986]:     raise IntentError(f"Power level of {self.mxid} is not enough "
Feb 22 08:29:56 chagai-server matrix-mautrix-telegram[585986]: mautrix.errors.base.IntentError: Power level of @telegram_1128218481:chagai.website is not enough for m.room.message in !HfmMaonCLBRRYKkOfl:chagai.website
Feb 22 08:29:56 chagai-server matrix-mautrix-telegram[585986]: [2021-02-22 07:29:56,990] [DEBUG@telethon.relaybot.network.mtprotosender] Handling update Updates
Feb 22 08:29:57 chagai-server matrix-mautrix-telegram[585986]: [2021-02-22 07:29:57,000] [DEBUG@telethon.relaybot.network.mtprotosender] Receiving items from the network...
Feb 22 08:29:57 chagai-server matrix-mautrix-telegram[585986]: [2021-02-22 07:29:57,001] [DEBUG@mau.portal.1468629521] Ignoring message 452@1468629521 (src 1469886687) as it was already handled (in space 1468629521)
Feb 22 08:29:57 chagai-server matrix-mautrix-telegram[585986]: [2021-02-22 07:29:57,850] [DEBUG@telethon.299986122.network.mtprotosender] Handling update UpdateShort
Feb 22 08:29:57 chagai-server matrix-mautrix-telegram[585986]: [2021-02-22 07:29:57,850] [DEBUG@telethon.299986122.network.mtprotosender] Receiving items from the network...

```

**Comment by chagai95** [comment]
Ok so the last issue was just because I played around with the permissions in the specific room I was testing in. Not sure what the first issue was but I'm gonna close it because restarting Slavi's playbook solved it...
