### ISSUE TITLE
clean-rooms response: event too large

### ISSUE THREAD

**Issue by olmari** [tulir/mautrix-telegram#590]
I issued `clean-rooms` to our bot, and it errors out with:

```
Traceback (most recent call last):
  File "/opt/telegrambot/lib/python3.7/site-packages/mautrix/bridge/commands/handler.py", line 405, in handle
    await self._run_handler(handler, evt)
  File "/opt/telegrambot/lib/python3.7/site-packages/mautrix_telegram/commands/handler.py", line 121, in _run_handler
    return await handler(evt)
  File "/opt/telegrambot/lib/python3.7/site-packages/mautrix/bridge/commands/handler.py", line 290, in __call__
    return await self._handler(evt)
  File "/opt/telegrambot/lib/python3.7/site-packages/mautrix/bridge/commands/clean_rooms.py", line 116, in clean_rooms
    return await evt.reply("\n".join(reply))
  File "/opt/telegrambot/lib/python3.7/site-packages/mautrix/appservice/api/intent.py", line 95, in wrapper
    return await __method(*args, **kwargs)
  File "/opt/telegrambot/lib/python3.7/site-packages/mautrix/appservice/api/intent.py", line 275, in send_message_event
    return await super().send_message_event(room_id, event_type, content, **kwargs)
  File "/opt/telegrambot/lib/python3.7/site-packages/mautrix/client/api/events.py", line 315, in send_message_event
    resp = await self.api.request(Method.PUT, url, content, **kwargs)
  File "/opt/telegrambot/lib/python3.7/site-packages/mautrix/api.py", line 233, in request
    return await self._send(method, full_url, content, query_params, headers or {})
  File "/opt/telegrambot/lib/python3.7/site-packages/mautrix/api.py", line 160, in _send
    errcode=errcode, message=message)
mautrix.errors.request.MTooLarge: event too large
```

So there is propably so much crap rooms in the response that it literally exceeds matrix event size. Now I was able to still run `clean-recommended` and confirming it, but obvivously clean-rooms response needs to be rethought for larger servers to be able to see responses of that :)

**Comment by tulir** [comment]
tulir/mautrix-python#33
