### ISSUE TITLE
AttributeError: 'ChannelParticipantBanned' object has no attribute 'user_id'

### ISSUE THREAD

**Issue by JuniorJPDJ** [tulir/mautrix-telegram#635]
```
mautrix-telegram_1           | 2021-06-23T16:13:43.886553783Z [2021-06-23 16:13:43,885] [ERROR@mau.portal.XXX] Fatal error updating Matrix room
mautrix-telegram_1           | 2021-06-23T16:13:43.886590606Z Traceback (most recent call last):
mautrix-telegram_1           | 2021-06-23T16:13:43.886598303Z   File "/usr/lib/python3.8/site-packages/mautrix_telegram/portal/metadata.py", line 203, in update_matrix_room
mautrix-telegram_1           | 2021-06-23T16:13:43.886604323Z     await self._update_matrix_room(user, entity, direct, puppet, levels, users)
mautrix-telegram_1           | 2021-06-23T16:13:43.886610100Z   File "/usr/lib/python3.8/site-packages/mautrix_telegram/portal/metadata.py", line 214, in _update_matrix_room
mautrix-telegram_1           | 2021-06-23T16:13:43.886615980Z     users = await self._get_users(user, entity)
mautrix-telegram_1           | 2021-06-23T16:13:43.886621644Z   File "/usr/lib/python3.8/site-packages/mautrix_telegram/portal/metadata.py", line 836, in _get_users
mautrix-telegram_1           | 2021-06-23T16:13:43.886627115Z     return await self._get_channel_users(user, entity, limit)
mautrix-telegram_1           | 2021-06-23T16:13:43.886632661Z   File "/usr/lib/python3.8/site-packages/mautrix_telegram/portal/metadata.py", line 815, in _get_channel_users
mautrix-telegram_1           | 2021-06-23T16:13:43.886638102Z     users += self._filter_participants(response.users, response.participants)
mautrix-telegram_1           | 2021-06-23T16:13:43.886643327Z   File "/usr/lib/python3.8/site-packages/mautrix_telegram/portal/metadata.py", line 787, in _filter_participants
mautrix-telegram_1           | 2021-06-23T16:13:43.886648661Z     participant_map = {part.user_id: part for part in participants}
mautrix-telegram_1           | 2021-06-23T16:13:43.886653776Z   File "/usr/lib/python3.8/site-packages/mautrix_telegram/portal/metadata.py", line 787, in <dictcomp>
mautrix-telegram_1           | 2021-06-23T16:13:43.886659278Z     participant_map = {part.user_id: part for part in participants}
mautrix-telegram_1           | 2021-06-23T16:13:43.886664407Z AttributeError: 'ChannelParticipantBanned' object has no attribute 'user_id'
```
Probably should be handled and skipped, not crash backfill.

**Comment by oscarmlage** [comment]
Same error here with python-3.9
