### ISSUE TITLE
telethon.errors.rpcerrorlist.FileReferenceExpiredError

### ISSUE THREAD

**Issue by JuniorJPDJ** [tulir/mautrix-telegram#636]
```
mautrix-telegram_1           | 2021-06-23T16:13:41.843210557Z [2021-06-23 16:13:41,842] [ERROR@mau.user.@XXX:juniorjpdj.pl] Error while backfilling XXXXXXXXXX                                                
mautrix-telegram_1           | 2021-06-23T16:13:41.843236118Z Traceback (most recent call last):                                                                                                                     
mautrix-telegram_1           | 2021-06-23T16:13:41.843241764Z   File "/usr/lib/python3.8/site-packages/mautrix_telegram/user.py", line 472, in _sync_dialog                                                          
mautrix-telegram_1           | 2021-06-23T16:13:41.843246815Z     await portal.backfill(self, last_id=dialog.message.id)                                                                                             
mautrix-telegram_1           | 2021-06-23T16:13:41.843268389Z   File "/usr/lib/python3.8/site-packages/mautrix_telegram/portal/telegram.py", line 517, in backfill                                                   
mautrix-telegram_1           | 2021-06-23T16:13:41.843273895Z     await self._locked_backfill(source, is_initial, limit, last_id)                                                                                    
mautrix-telegram_1           | 2021-06-23T16:13:41.843277821Z   File "/usr/lib/python3.8/site-packages/mautrix_telegram/portal/telegram.py", line 557, in _locked_backfill                                           
mautrix-telegram_1           | 2021-06-23T16:13:41.843281678Z     await self._backfill(source, min_id, limit)                                                                                                        
mautrix-telegram_1           | 2021-06-23T16:13:41.843285368Z   File "/usr/lib/python3.8/site-packages/mautrix_telegram/portal/telegram.py", line 576, in _backfill                                                  
mautrix-telegram_1           | 2021-06-23T16:13:41.843289127Z     count = await self._backfill_messages(source, min_id, limit, client)                                                                               
mautrix-telegram_1           | 2021-06-23T16:13:41.843292712Z   File "/usr/lib/python3.8/site-packages/mautrix_telegram/portal/telegram.py", line 595, in _backfill_messages                                         
mautrix-telegram_1           | 2021-06-23T16:13:41.843296441Z     await self.handle_telegram_message(source, sender, message)                                                                                        
mautrix-telegram_1           | 2021-06-23T16:13:41.843300001Z   File "/usr/lib/python3.8/site-packages/mautrix_telegram/portal/telegram.py", line 672, in handle_telegram_message                                    
mautrix-telegram_1           | 2021-06-23T16:13:41.843303719Z     event_id = await {                                                                                                                                 
mautrix-telegram_1           | 2021-06-23T16:13:41.843307227Z   File "/usr/lib/python3.8/site-packages/mautrix_telegram/portal/telegram.py", line 225, in handle_telegram_document                                   
mautrix-telegram_1           | 2021-06-23T16:13:41.843310955Z     file = await util.transfer_file_to_matrix(source.client, intent, document, thumb_loc,                                                              
mautrix-telegram_1           | 2021-06-23T16:13:41.843314778Z   File "/usr/lib/python3.8/site-packages/mautrix_telegram/util/file_transfer.py", line 189, in transfer_file_to_matrix                                 
mautrix-telegram_1           | 2021-06-23T16:13:41.843318640Z     return await _unlocked_transfer_file_to_matrix(client, intent, location_id, location,                                                              
mautrix-telegram_1           | 2021-06-23T16:13:41.843322361Z   File "/usr/lib/python3.8/site-packages/mautrix_telegram/util/file_transfer.py", line 254, in _unlocked_transfer_file_to_matrix                       
mautrix-telegram_1           | 2021-06-23T16:13:41.843326116Z     db_file.thumbnail = await transfer_thumbnail_to_matrix(client, intent, thumbnail,                                                                  
mautrix-telegram_1           | 2021-06-23T16:13:41.843329790Z   File "/usr/lib/python3.8/site-packages/mautrix_telegram/util/file_transfer.py", line 140, in transfer_thumbnail_to_matrix                            
mautrix-telegram_1           | 2021-06-23T16:13:41.843333635Z     file = await client.download_file(thumbnail_loc)                                                                                                   
mautrix-telegram_1           | 2021-06-23T16:13:41.843337177Z   File "/usr/lib/python3.8/site-packages/telethon/client/downloads.py", line 490, in download_file                                                     
mautrix-telegram_1           | 2021-06-23T16:13:41.843341836Z     return await self._download_file(                                                                                                                  
mautrix-telegram_1           | 2021-06-23T16:13:41.843345517Z   File "/usr/lib/python3.8/site-packages/telethon/client/downloads.py", line 538, in _download_file                                                    
mautrix-telegram_1           | 2021-06-23T16:13:41.843349277Z     async for chunk in self._iter_download(                                                                                                            
mautrix-telegram_1           | 2021-06-23T16:13:41.843352780Z   File "/usr/lib/python3.8/site-packages/telethon/requestiter.py", line 74, in __anext__
mautrix-telegram_1           | 2021-06-23T16:13:41.843356449Z     if await self._load_next_chunk():
mautrix-telegram_1           | 2021-06-23T16:13:41.843360041Z   File "/usr/lib/python3.8/site-packages/telethon/client/downloads.py", line 66, in _load_next_chunk
mautrix-telegram_1           | 2021-06-23T16:13:41.843363735Z     cur = await self._request()
mautrix-telegram_1           | 2021-06-23T16:13:41.843372232Z   File "/usr/lib/python3.8/site-packages/telethon/client/downloads.py", line 76, in _request
mautrix-telegram_1           | 2021-06-23T16:13:41.843376370Z     result = await self.client._call(self._sender, self.request)
mautrix-telegram_1           | 2021-06-23T16:13:41.843379987Z   File "/usr/lib/python3.8/site-packages/telethon/client/users.py", line 79, in _call
mautrix-telegram_1           | 2021-06-23T16:13:41.843383626Z     result = await future
mautrix-telegram_1           | 2021-06-23T16:13:41.843387379Z telethon.errors.rpcerrorlist.FileReferenceExpiredError: The file reference has expired and is no longer valid or it belongs to self-destructing media a
nd cannot be resent (caused by GetFileRequest)
```

Probably should be handled and skipped and not crash backfill.

**Comment by JuniorJPDJ** [comment]
It seems to still crash backfill ;/

```
mautrix-telegram_1           | 2021-11-01T17:11:38.397440552Z [2021-11-01 17:11:38,391] [ERROR@mau.user.@XXXXXXXX:juniorjpdj.pl] Error while backfilling XXXXXXXXXX                                                                             
mautrix-telegram_1           | 2021-11-01T17:11:38.397478432Z Traceback (most recent call last):                                                                                                                                                
mautrix-telegram_1           | 2021-11-01T17:11:38.397487574Z   File "/usr/lib/python3.9/site-packages/mautrix_telegram/user.py", line 513, in _sync_dialog                                                                                     
mautrix-telegram_1           | 2021-11-01T17:11:38.397494756Z     await portal.backfill(self, last_id=dialog.message.id)                                                                                                                        
mautrix-telegram_1           | 2021-11-01T17:11:38.397501004Z   File "/usr/lib/python3.9/site-packages/mautrix_telegram/portal/telegram.py", line 524, in backfill                                                                              
mautrix-telegram_1           | 2021-11-01T17:11:38.397507386Z     await self._locked_backfill(source, is_initial, limit, last_id)                                                                                                               
mautrix-telegram_1           | 2021-11-01T17:11:38.397513762Z   File "/usr/lib/python3.9/site-packages/mautrix_telegram/portal/telegram.py", line 564, in _locked_backfill                                                                      
mautrix-telegram_1           | 2021-11-01T17:11:38.397520138Z     await self._backfill(source, min_id, limit)                                                                                                                                   
mautrix-telegram_1           | 2021-11-01T17:11:38.397525976Z   File "/usr/lib/python3.9/site-packages/mautrix_telegram/portal/telegram.py", line 583, in _backfill                                                                             
mautrix-telegram_1           | 2021-11-01T17:11:38.397532264Z     count = await self._backfill_messages(source, min_id, limit, client)                                                                                                          
mautrix-telegram_1           | 2021-11-01T17:11:38.397538150Z   File "/usr/lib/python3.9/site-packages/mautrix_telegram/portal/telegram.py", line 602, in _backfill_messages                                                                    
mautrix-telegram_1           | 2021-11-01T17:11:38.397544634Z     await self.handle_telegram_message(source, sender, message)                                                                                                                   
mautrix-telegram_1           | 2021-11-01T17:11:38.397550492Z   File "/usr/lib/python3.9/site-packages/mautrix_telegram/portal/telegram.py", line 679, in handle_telegram_message                                                               
mautrix-telegram_1           | 2021-11-01T17:11:38.397556628Z     event_id = await {                                                                                                                                                            
mautrix-telegram_1           | 2021-11-01T17:11:38.397562410Z   File "/usr/lib/python3.9/site-packages/mautrix_telegram/portal/telegram.py", line 225, in handle_telegram_document                                                              
mautrix-telegram_1           | 2021-11-01T17:11:38.397568584Z     file = await util.transfer_file_to_matrix(source.client, intent, document, thumb_loc,                                                                                         
mautrix-telegram_1           | 2021-11-01T17:11:38.397574551Z   File "/usr/lib/python3.9/site-packages/mautrix_telegram/util/file_transfer.py", line 189, in transfer_file_to_matrix                                                            
mautrix-telegram_1           | 2021-11-01T17:11:38.397580697Z     return await _unlocked_transfer_file_to_matrix(client, intent, location_id, location,                                                                                         
mautrix-telegram_1           | 2021-11-01T17:11:38.397586831Z   File "/usr/lib/python3.9/site-packages/mautrix_telegram/util/file_transfer.py", line 254, in _unlocked_transfer_file_to_matrix                                                  
mautrix-telegram_1           | 2021-11-01T17:11:38.397593006Z     db_file.thumbnail = await transfer_thumbnail_to_matrix(client, intent, thumbnail,                                                                                             
mautrix-telegram_1           | 2021-11-01T17:11:38.397598917Z   File "/usr/lib/python3.9/site-packages/mautrix_telegram/util/file_transfer.py", line 140, in transfer_thumbnail_to_matrix                                                       
mautrix-telegram_1           | 2021-11-01T17:11:38.397605105Z     file = await client.download_file(thumbnail_loc)                                                                                                                              
mautrix-telegram_1           | 2021-11-01T17:11:38.397610997Z   File "/usr/lib/python3.9/site-packages/telethon/client/downloads.py", line 490, in download_file                                                                                
mautrix-telegram_1           | 2021-11-01T17:11:38.397639913Z     return await self._download_file(                                                                                                                                             
mautrix-telegram_1           | 2021-11-01T17:11:38.397648429Z   File "/usr/lib/python3.9/site-packages/telethon/client/downloads.py", line 538, in _download_file                                                                               
mautrix-telegram_1           | 2021-11-01T17:11:38.397655005Z     async for chunk in self._iter_download(                                                                                                                                       
mautrix-telegram_1           | 2021-11-01T17:11:38.397661055Z   File "/usr/lib/python3.9/site-packages/telethon/requestiter.py", line 74, in __anext__                                                                                          
mautrix-telegram_1           | 2021-11-01T17:11:38.397667527Z     if await self._load_next_chunk():                                                                                                                                             
mautrix-telegram_1           | 2021-11-01T17:11:38.397673571Z   File "/usr/lib/python3.9/site-packages/telethon/client/downloads.py", line 66, in _load_next_chunk                                                                              
mautrix-telegram_1           | 2021-11-01T17:11:38.397679783Z     cur = await self._request()                                                                                                                                                   
mautrix-telegram_1           | 2021-11-01T17:11:38.397685645Z   File "/usr/lib/python3.9/site-packages/telethon/client/downloads.py", line 76, in _request                                                                                      
mautrix-telegram_1           | 2021-11-01T17:11:38.397691809Z     result = await self.client._call(self._sender, self.request)                                                                                                                  
mautrix-telegram_1           | 2021-11-01T17:11:38.397697861Z   File "/usr/lib/python3.9/site-packages/telethon/client/users.py", line 84, in _call
mautrix-telegram_1           | 2021-11-01T17:11:38.397703934Z     result = await future
mautrix-telegram_1           | 2021-11-01T17:11:38.397709925Z telethon.errors.rpcerrorlist.FileReferenceExpiredError: The file reference has expired and is no longer valid or it belongs to self-destructing media and cannot be resent (caused
 by GetFileRequest)
```

**Comment by frebib** [comment]
This happens reasonably frequently to me when sending images in both directions. It's quite annoying because the bridge doesn't even warn that something wasn't bridged and instead I have to find out through embarrassment of "what picture?"

**Comment by frebib** [comment]
Strangely images seem to be fine, but videos reliably fail to be bridged telegram->matrix
```
[2022-03-28 22:19:21,054] [ERROR@mau.user.@frebib:chat.nerdhouse.io] Failed to handle Telegram update
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/abstract_user.py", line 252, in _update_catch
    await self._update(update)
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/abstract_user.py", line 312, in _update
    await self.update_message(update)
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/abstract_user.py", line 623, in update_message
    return await portal.handle_telegram_message(self, sender, update)
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/portal.py", line 3197, in handle_telegram_message
    event_id = await handler(source, intent, evt, relates_to)
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/portal.py", line 2393, in _handle_telegram_document
    file = await util.transfer_file_to_matrix(
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/util/file_transfer.py", line 240, in transfer_file_to_matrix
    return await _unlocked_transfer_file_to_matrix(
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/util/file_transfer.py", line 331, in _unlocked_transfer_file_to_matrix
    db_file.thumbnail = await transfer_thumbnail_to_matrix(
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/util/file_transfer.py", line 173, in transfer_thumbnail_to_matrix
    file = await client.download_file(thumbnail_loc)
  File "/usr/lib/python3.9/site-packages/telethon/client/downloads.py", line 490, in download_file
    return await self._download_file(
  File "/usr/lib/python3.9/site-packages/telethon/client/downloads.py", line 538, in _download_file
    async for chunk in self._iter_download(
  File "/usr/lib/python3.9/site-packages/telethon/requestiter.py", line 74, in __anext__
    if await self._load_next_chunk():
  File "/usr/lib/python3.9/site-packages/telethon/client/downloads.py", line 66, in _load_next_chunk
    cur = await self._request()
  File "/usr/lib/python3.9/site-packages/telethon/client/downloads.py", line 76, in _request
    result = await self.client._call(self._sender, self.request)
  File "/usr/lib/python3.9/site-packages/telethon/client/users.py", line 84, in _call
    result = await future
telethon.errors.rpcerrorlist.FileReferenceExpiredError: The file reference has expired and is no longer valid or it belongs to self-destructing media and cannot be resent (caused by GetFileRequest)
```

**Comment by frebib** [comment]
Disabling `parallel_file_transfer` yields a different but still similar error
```
[2022-03-28 22:29:50,801] [INFO@telethon.367043320.client.downloads] Starting direct file download in chunks of 65536 at 0, stride 65536
[2022-03-28 22:29:51,568] [ERROR@mau.user.@frebib:chat.nerdhouse.io] Failed to handle Telegram update
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/abstract_user.py", line 252, in _update_catch
    await self._update(update)
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/abstract_user.py", line 312, in _update
    await self.update_message(update)
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/abstract_user.py", line 623, in update_message
    return await portal.handle_telegram_message(self, sender, update)
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/portal.py", line 3197, in handle_telegram_message
    event_id = await handler(source, intent, evt, relates_to)
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/portal.py", line 2393, in _handle_telegram_document
    file = await util.transfer_file_to_matrix(
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/util/file_transfer.py", line 240, in transfer_file_to_matrix
    return await _unlocked_transfer_file_to_matrix(
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/util/file_transfer.py", line 312, in _unlocked_transfer_file_to_matrix
    content_uri = await intent.upload_media(file, upload_mime_type, async_upload=async_upload)
  File "/usr/lib/python3.9/site-packages/mautrix/appservice/api/intent.py", line 123, in wrapper
    return await __method(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/mautrix/client/api/modules/media_repository.py", line 105, in upload_media
    mxc = await self.unstable_create_mxc()
  File "/usr/lib/python3.9/site-packages/mautrix/appservice/api/intent.py", line 123, in wrapper
    return await __method(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/mautrix/client/api/modules/media_repository.py", line 50, in unstable_create_mxc
    resp = await self.api.request(Method.POST, MediaPath.unstable["fi.mau.msc2246"].create)
  File "/usr/lib/python3.9/site-packages/mautrix/api.py", line 383, in request
    return await self._send(method, full_url, req_content, query_params, headers or {})
  File "/usr/lib/python3.9/site-packages/mautrix/api.py", line 258, in _send
    raise make_request_error(
mautrix.errors.request.MatrixUnknownRequestError: 404:
<html>
  <head><title>404 - No Such Resource</title></head>
  <body>
    <h1>No Such Resource</h1>
    <p>Sorry. No luck finding that resource.</p>
  </body>
</html>
```

**Comment by frebib** [comment]
Here are DEBUG logs that I redacted
https://gist.github.com/frebib/ddfc0f169f681c572aa31b578523c4b6/raw

I see notably this strange line suggesting that the file reference is a binary string- that doesn't seem right. Is that a bug?
```
[2022-03-28 22:40:00,378] [DEBUG@mau.util] Starting parallel download: 1 131072 8 InputDocumentFileLocation(id=<snip>, access_hash=<snip>, file_reference=b"\x01\x00\x06E\x14bB9@>\xa6\x1e\x8e\x179N\xac\xa6\xf0\x05\xe6\xe1'7\x91", thumb_size='')
```
