### ISSUE TITLE
Invalidated session error on startup even with new token

### ISSUE THREAD

**Issue by w3bb** [tulir/mautrix-telegram#642]
```
[2021-07-08 05:59:44,116] [CRITICAL@mau.init] Unexpected error in main event loop
Traceback (most recent call last):
  File "/home/tgm/.local/lib/python3.9/site-packages/mautrix/util/program.py", line 190, in _run
    self.loop.run_until_complete(self.start())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/tgm/.local/lib/python3.9/site-packages/mautrix/bridge/bridge.py", line 159, in start
    await super().start()
  File "/home/tgm/.local/lib/python3.9/site-packages/mautrix/util/program.py", line 213, in start
    await asyncio.gather(*(self.startup_actions or []))
  File "/home/tgm/.local/lib/python3.9/site-packages/mautrix_telegram/bot.py", line 92, in start
    await super().start(delete_unless_authenticated)
  File "/home/tgm/.local/lib/python3.9/site-packages/mautrix_telegram/abstract_user.py", line 220, in start
    await self.client.connect()
  File "/home/tgm/.local/lib/python3.9/site-packages/telethon/client/telegrambaseclient.py", line 529, in connect
    await self._sender.send(functions.InvokeWithLayerRequest(
telethon.errors.rpcerrorlist.AuthKeyDuplicatedError: The authorization key (session file) was used under two different IP addresses simultaneously, and can no
longer be used. Use the same session exclusively, or use different sessions (caused by InvokeWithLayerRequest)
```

```
willow:~$ pip show mautrix_telegram
Name: mautrix-telegram
Version: 0.10.0
```

I was migrating servers and this error started appearing. I stopped the old server's, and created a new token, but it's still appearing.

**Comment by w3bb** [comment]
What I ended up doing was removing the sessions from the telethon_sessions table. Keep in mind all users need to log in again.

**Comment by Kitanit** [comment]
recently received the same error, the solution is still identical

**Comment by luochen1990** [comment]
> removing the sessions from the telethon_sessions table

Here is the operations for who see this:

```
sudo -u postgres psql

# \l
# \c mautrix-telegram
# \d
# select * from telethon_sessions ;
# delete from telethon_sessions ;
```
